package modulesgen

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/dvmrry/infrawright-dev/go/internal/metadata"
)

type dataModuleFixtureOptions struct {
	lookupNameField         string
	includeLookupSource     bool
	includeDataSourceSchema bool
	dataSourceAttributes    metadata.JsonObject
}

func writeSyntheticModulePack(
	t *testing.T,
	root string,
	name string,
	manifest metadata.JsonObject,
	registry metadata.JsonObject,
	resourceSchemas metadata.JsonObject,
	dataSourceSchemas ...metadata.JsonObject,
) {
	t.Helper()
	dataSources := metadata.JsonObject{}
	if len(dataSourceSchemas) > 1 {
		t.Fatalf("writeSyntheticModulePack(%q) received %d data_source_schemas values, want at most one", name, len(dataSourceSchemas))
	}
	if len(dataSourceSchemas) == 1 && dataSourceSchemas[0] != nil {
		dataSources = dataSourceSchemas[0]
	}
	writeJSONFile(t, filepath.Join(root, name, "pack.json"), manifest)
	writeJSONFile(t, filepath.Join(root, name, "registry.json"), registry)
	writeJSONFile(t, filepath.Join(root, name, "schemas", "provider", name+".json"), metadata.JsonObject{
		"resource_schemas":    resourceSchemas,
		"data_source_schemas": dataSources,
	})
}

func syntheticDataModuleLoadOptions(t *testing.T, options dataModuleFixtureOptions) metadata.LoadPackRootOptions {
	t.Helper()

	packsRoot := t.TempDir()
	manifest := metadata.JsonObject{
		"pin":               "1.0.0",
		"provider_prefixes": metadata.JsonObject{"zia_": "zia"},
		"provider_sources":  metadata.JsonObject{"zia": "zscaler/zia"},
	}
	if options.includeLookupSource {
		nameField := options.lookupNameField
		if nameField == "" {
			nameField = "name"
		}
		manifest["lookup_sources"] = metadata.JsonObject{
			"zia_location_groups": metadata.JsonObject{"name_field": nameField},
		}
	}

	const dataReferentType = "zia_location_groups"
	registry := metadata.JsonObject{
		dataReferentType: metadata.JsonObject{
			"data_referent": true,
			"fetch": metadata.JsonObject{
				"pagination": "zia",
				"path":       "locations/groups",
			},
			"product": "zia",
		},
	}
	dataSourceSchemas := metadata.JsonObject{}
	if options.includeDataSourceSchema {
		attributes := options.dataSourceAttributes
		if attributes == nil {
			attributes = metadata.JsonObject{
				"id": metadata.JsonObject{
					"computed": true,
					"type":     "number",
				},
				"name": metadata.JsonObject{
					"optional": true,
					"type":     "string",
				},
			}
		}
		dataSourceSchemas[dataReferentType] = metadata.JsonObject{
			"block": metadata.JsonObject{
				"attributes": attributes,
			},
		}
	}

	writeSyntheticModulePack(t, packsRoot, "zia", manifest, registry, metadata.JsonObject{}, dataSourceSchemas)
	profilePath := packsRoot + "/synthetic.packset.json"
	writeJSONFile(t, profilePath, metadata.JsonObject{
		"kind":    metadata.PackSetKind,
		"version": 1,
		"packs":   []any{"zia"},
		"shared":  []any{},
	})

	return metadata.LoadPackRootOptions{
		PacksRoot:   packsRoot,
		ProfilePath: &profilePath,
	}
}

func syntheticDataModuleRoot(t *testing.T, options dataModuleFixtureOptions) metadata.LoadedPackRoot {
	t.Helper()
	loaded, err := metadata.LoadPackRoot(syntheticDataModuleLoadOptions(t, options))
	if err != nil {
		t.Fatalf("LoadPackRoot(data module fixture): %v", err)
	}
	return loaded
}

func TestDataModuleRendersItemsOutputForTwoItems(t *testing.T) {
	root := syntheticDataModuleRoot(t, dataModuleFixtureOptions{
		lookupNameField:         "name",
		includeLookupSource:     true,
		includeDataSourceSchema: true,
	})
	items := metadata.JsonObject{
		"group-a": metadata.JsonObject{"name": "Group A"},
		"group-b": metadata.JsonObject{"name": "Group B"},
	}

	rendered, err := renderModuleFilesWithDataSample(root, "zia_location_groups", items)
	if err != nil {
		t.Fatalf("RenderModuleFiles(zia_location_groups): %v", err)
	}
	wantNames := ExpectedModuleFiles
	if got := rendered.Names(); !reflect.DeepEqual(got, wantNames) {
		t.Fatalf("RenderModuleFiles(zia_location_groups).Names() = %v, want %v", got, wantNames)
	}

	main, ok := rendered.Get(FileMain)
	if !ok {
		t.Fatal("RenderModuleFiles(zia_location_groups) omitted main.tf")
	}
	wantMain := "# GENERATED by iw modules generate from packs/zia/schemas/provider/zia.json — do not edit.\n# Regenerate: make gen-modules\n\ndata \"zia_location_groups\" \"items\" {\n  for_each = var.items\n  name = each.value.name\n}\n\noutput \"items\" {\n  description = \"All read-only zia_location_groups data source objects, keyed as in var.items.\"\n  value       = data.zia_location_groups.items\n}\n"
	if main != wantMain {
		t.Errorf("RenderModuleFiles(zia_location_groups).main.tf = %q, want %q", main, wantMain)
	}
	wantVariables := "# GENERATED by iw modules generate from packs/zia/schemas/provider/zia.json — do not edit.\n# Regenerate: make gen-modules\n\nvariable \"items\" {\n  description = \"zia_location_groups instances, keyed by a stable identifier.\"\n  type = map(object({\n    name = string\n  }))\n}\n"
	if variables, ok := rendered.Get(FileVariables); !ok || variables != wantVariables {
		t.Errorf("RenderModuleFiles(zia_location_groups).variables.tf = %q, want %q", variables, wantVariables)
	}
	sample, ok := rendered.Get(FileSampleTfvars)
	if !ok {
		t.Fatal("RenderModuleFiles(zia_location_groups) omitted tests/sample.auto.tfvars.json")
	}
	wantSample := "{\n  \"items\": {\n    \"group-a\": {\n      \"name\": \"Group A\"\n    },\n    \"group-b\": {\n      \"name\": \"Group B\"\n    }\n  }\n}\n"
	if sample != wantSample {
		t.Errorf("RenderModuleFiles(zia_location_groups).sample.auto.tfvars.json = %q, want %q", sample, wantSample)
	}
	readme, ok := rendered.Get(FileReadme)
	if !ok {
		t.Fatal("RenderModuleFiles(zia_location_groups) omitted README.md")
	}
	wantReadme := "# zia_location_groups (generated module)\n\nReads `zia_location_groups` from the provider; managed nowhere — data source only. GENERATED — do not edit by\nhand (AGENTS.md rule 6). Regenerate with `iw modules generate` or `make gen-modules`.\n"
	if readme != wantReadme {
		t.Errorf("RenderModuleFiles(zia_location_groups).README.md = %q, want %q", readme, wantReadme)
	}
}

func TestDataModuleRequiresLookupSourceNameField(t *testing.T) {
	_, err := metadata.LoadPackRoot(syntheticDataModuleLoadOptions(t, dataModuleFixtureOptions{
		includeDataSourceSchema: true,
	}))
	if err == nil {
		t.Fatal("LoadPackRoot(zia_location_groups) with missing lookup_sources name_field: expected error, got nil")
	}
	if !strings.Contains(err.Error(), "lookup_sources") || !strings.Contains(err.Error(), "name_field") {
		t.Errorf("LoadPackRoot(zia_location_groups) missing name_field error = %q, want lookup_sources/name_field context", err)
	}
}

func TestDataModuleUsesLookupSourceNameField(t *testing.T) {
	root := syntheticDataModuleRoot(t, dataModuleFixtureOptions{
		lookupNameField:         "display_name",
		includeLookupSource:     true,
		includeDataSourceSchema: true,
		dataSourceAttributes: metadata.JsonObject{
			"display_name": metadata.JsonObject{"optional": true, "type": "string"},
			"id":           metadata.JsonObject{"computed": true, "type": "number"},
		},
	})
	items := metadata.JsonObject{
		"group-a": metadata.JsonObject{"display_name": "Group A"},
		"group-b": metadata.JsonObject{"display_name": "Group B"},
	}
	rendered, err := renderModuleFilesWithDataSample(root, "zia_location_groups", items)
	if err != nil {
		t.Fatalf("RenderModuleFiles(zia_location_groups) with display_name lookup: %v", err)
	}
	main, ok := rendered.Get(FileMain)
	if !ok {
		t.Fatal("RenderModuleFiles(zia_location_groups) omitted main.tf")
	}
	wantMain := "# GENERATED by iw modules generate from packs/zia/schemas/provider/zia.json — do not edit.\n# Regenerate: make gen-modules\n\ndata \"zia_location_groups\" \"items\" {\n  for_each = var.items\n  display_name = each.value.display_name\n}\n\noutput \"items\" {\n  description = \"All read-only zia_location_groups data source objects, keyed as in var.items.\"\n  value       = data.zia_location_groups.items\n}\n"
	if main != wantMain {
		t.Errorf("RenderModuleFiles(zia_location_groups).main.tf = %q, want %q", main, wantMain)
	}
	variables, ok := rendered.Get(FileVariables)
	if !ok {
		t.Fatal("RenderModuleFiles(zia_location_groups) omitted variables.tf")
	}
	wantVariables := "# GENERATED by iw modules generate from packs/zia/schemas/provider/zia.json — do not edit.\n# Regenerate: make gen-modules\n\nvariable \"items\" {\n  description = \"zia_location_groups instances, keyed by a stable identifier.\"\n  type = map(object({\n    display_name = string\n  }))\n}\n"
	if variables != wantVariables {
		t.Errorf("RenderModuleFiles(zia_location_groups).variables.tf = %q, want %q", variables, wantVariables)
	}
}

func TestDataModuleRejectsInvalidDataSourceAttributesBeforeWriting(t *testing.T) {
	validID := metadata.JsonObject{"computed": true, "type": "number"}
	cases := []struct {
		name               string
		attributes         metadata.JsonObject
		wantErrorFragments []string
	}{
		{
			name: "missing name field attribute",
			attributes: metadata.JsonObject{
				"id":   metadata.JsonObject{"computed": true, "type": "number"},
				"name": metadata.JsonObject{"optional": true, "type": "string"},
			},
			wantErrorFragments: []string{"missing input attribute", "display_name"},
		},
		{
			name: "computed-only name field",
			attributes: metadata.JsonObject{
				"display_name": metadata.JsonObject{"computed": true, "type": "string"},
				"id":           validID,
			},
			wantErrorFragments: []string{"computed-only", "display_name"},
		},
		{
			name: "non-string name field",
			attributes: metadata.JsonObject{
				"display_name": metadata.JsonObject{"optional": true, "type": "number"},
				"id":           validID,
			},
			wantErrorFragments: []string{"string-typed", "display_name"},
		},
		{
			name: "missing id",
			attributes: metadata.JsonObject{
				"display_name": metadata.JsonObject{"optional": true, "type": "string"},
			},
			wantErrorFragments: []string{"missing readable id attribute"},
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			root := syntheticDataModuleRoot(t, dataModuleFixtureOptions{
				lookupNameField:         "display_name",
				includeLookupSource:     true,
				includeDataSourceSchema: true,
				dataSourceAttributes:    testCase.attributes,
			})
			output := t.TempDir()
			_, err := GenerateModule(root, "zia_location_groups", GenerateModuleOptions{
				OutputRoot: output,
				FormatHCL:  IdentityFormatter,
			})
			if err == nil {
				t.Fatalf("GenerateModule(%q, %s) error = nil, want validation failure", "zia_location_groups", testCase.name)
			}
			for _, fragment := range testCase.wantErrorFragments {
				if !strings.Contains(err.Error(), fragment) {
					t.Errorf("GenerateModule(%q, %s) error = %q, want fragment %q", "zia_location_groups", testCase.name, err, fragment)
				}
			}
			entries, readErr := os.ReadDir(output)
			if readErr != nil {
				t.Fatalf("GenerateModule(%q, %s) output directory read error = %v, want empty directory", "zia_location_groups", testCase.name, readErr)
			}
			if len(entries) != 0 {
				t.Errorf("GenerateModule(%q, %s) wrote %d output entries, want 0 before validation succeeds", "zia_location_groups", testCase.name, len(entries))
			}
		})
	}
}

func TestDataModuleRequiresDataSourceSchema(t *testing.T) {
	_, err := metadata.LoadPackRoot(syntheticDataModuleLoadOptions(t, dataModuleFixtureOptions{
		lookupNameField:     "name",
		includeLookupSource: true,
	}))
	if err == nil {
		t.Fatal("LoadPackRoot(zia_location_groups) with missing data_source_schemas entry: expected error, got nil")
	}
	if !strings.Contains(err.Error(), "data_source_schemas") || !strings.Contains(err.Error(), "zia_location_groups") {
		t.Errorf("LoadPackRoot(zia_location_groups) missing data source schema error = %q, want data_source_schemas/type context", err)
	}
}

func TestActiveDataReferentModulesGenerateAndValidate(t *testing.T) {
	root := syntheticDataModuleRoot(t, dataModuleFixtureOptions{
		lookupNameField:         "name",
		includeLookupSource:     true,
		includeDataSourceSchema: true,
	})
	if got := ActiveGeneratedResourceTypes(root); len(got) != 0 {
		t.Fatalf("ActiveGeneratedResourceTypes(data-only fixture) = %v, want no generated resource types", got)
	}
	wantTypes := []string{"zia_location_groups"}
	if got := ActiveDataReferentResourceTypes(root); !reflect.DeepEqual(got, wantTypes) {
		t.Fatalf("ActiveDataReferentResourceTypes(data-only fixture) = %v, want %v", got, wantTypes)
	}
	if got := ActiveModuleResourceTypes(root); !reflect.DeepEqual(got, wantTypes) {
		t.Fatalf("ActiveModuleResourceTypes(data-only fixture) = %v, want %v", got, wantTypes)
	}

	output := t.TempDir()
	generated, err := GenerateActiveModules(root, GenerateModuleOptions{
		OutputRoot: output,
		FormatHCL:  NewHCLFormatter(),
	})
	if err != nil {
		t.Fatalf("GenerateActiveModules(data-only fixture): %v", err)
	}
	if got := len(generated); got != 1 {
		t.Fatalf("GenerateActiveModules(data-only fixture) returned %d modules, want 1", got)
	}
	if generated[0].ResourceType != "zia_location_groups" {
		t.Errorf("GenerateActiveModules(data-only fixture)[0].ResourceType = %q, want zia_location_groups", generated[0].ResourceType)
	}
	generatedMain, err := os.ReadFile(filepath.Join(output, "zia_location_groups", string(FileMain)))
	if err != nil {
		t.Fatalf("ReadFile generated data module main.tf: %v", err)
	}
	wantGeneratedMain := "# GENERATED by iw modules generate from packs/zia/schemas/provider/zia.json — do not edit.\n# Regenerate: make gen-modules\n\ndata \"zia_location_groups\" \"items\" {\n  for_each = var.items\n  name     = each.value.name\n}\n\noutput \"items\" {\n  description = \"All read-only zia_location_groups data source objects, keyed as in var.items.\"\n  value       = data.zia_location_groups.items\n}\n"
	if string(generatedMain) != wantGeneratedMain {
		t.Errorf("GenerateActiveModules(data-only fixture).main.tf = %q, want %q", generatedMain, wantGeneratedMain)
	}
	generatedVariables, err := os.ReadFile(filepath.Join(output, "zia_location_groups", string(FileVariables)))
	if err != nil {
		t.Fatalf("ReadFile generated data module variables.tf: %v", err)
	}
	wantGeneratedVariables := "# GENERATED by iw modules generate from packs/zia/schemas/provider/zia.json — do not edit.\n# Regenerate: make gen-modules\n\nvariable \"items\" {\n  description = \"zia_location_groups instances, keyed by a stable identifier.\"\n  type = map(object({\n    name = string\n  }))\n}\n"
	if string(generatedVariables) != wantGeneratedVariables {
		t.Errorf("GenerateActiveModules(data-only fixture).variables.tf = %q, want %q", generatedVariables, wantGeneratedVariables)
	}
	validated, err := ValidateGeneratedModuleTree(output, wantTypes)
	if err != nil {
		t.Fatalf("ValidateGeneratedModuleTree(data-only fixture): %v", err)
	}
	if !reflect.DeepEqual(validated, wantTypes) {
		t.Errorf("ValidateGeneratedModuleTree(data-only fixture) = %v, want %v", validated, wantTypes)
	}
}
