package modulesgen

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/dvmrry/infrawright-dev/go/internal/metadata"
)

// TestRendererPreservesCompleteSevenFileContractAndCoreShapes verifies the
// module file contract against current packs.
func TestRendererPreservesCompleteSevenFileContractAndCoreShapes(t *testing.T) {
	root := committedRoot(t)
	segment, err := RenderModuleFiles(root, "zpa_segment_group")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zpa_segment_group): %v", err)
	}
	if names := segment.Names(); !reflect.DeepEqual(names, ExpectedModuleFiles) {
		t.Fatalf("Names() = %v, want %v", names, ExpectedModuleFiles)
	}

	mainTf, _ := segment.Get(FileMain)
	mustMatch(t, mainTf, `^# GENERATED by iw modules generate from packs/zpa/schemas/provider/zpa\.json — do not edit\.\n# Regenerate: make gen-modules\n`)
	mustNotMatch(t, mainTf, `python|engine\.gen_module`)
	readme, _ := segment.Get(FileReadme)
	mustMatch(t, readme, "Regenerate with `iw modules generate` or `make gen-modules`\\.")
	mustNotMatch(t, readme, `python|engine\.gen_module`)
	mustMatch(t, mainTf, `for_each = var\.items`)
	mustMatch(t, mainTf, `(?s)dynamic "applications".*each\.value\.applications == null \? \[\] : each\.value\.applications`)
	mustNotMatch(t, mainTf, `\n  id =`)

	variablesTf, _ := segment.Get(FileVariables)
	mustMatch(t, variablesTf, `(?s)type = map\(object\(\{.*name = string.*description = optional\(string\)`)

	outputsTf, _ := segment.Get(FileOutputs)
	mustMatch(t, outputsTf, `output "name_to_id"`)

	sample, _ := segment.Get(FileSampleTfvars)
	wantSample := "{\n  \"items\": {\n    \"example\": {\n      \"name\": \"example\"\n    }\n  }\n}\n"
	if sample != wantSample {
		t.Errorf("sample.auto.tfvars.json = %q, want %q", sample, wantSample)
	}

	categories, err := RenderModuleFiles(root, "zia_url_categories")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zia_url_categories): %v", err)
	}
	categoriesVariables, _ := categories.Get(FileVariables)
	mustMatch(t, categoriesVariables, `scopes = optional\(set\(object\(\{`)
	mustMatch(t, categoriesVariables, `url_keyword_counts = optional\(object\(\{`)
	mustMatch(t, categoriesVariables, `scope_entities = optional\(object\(\{`)
	mustNotMatch(t, categoriesVariables, `category_id`)
	categoriesOutputs, _ := categories.Get(FileOutputs)
	mustNotMatch(t, categoriesOutputs, `name_to_id`)
}

// TestSamplesSensitiveOutputsDeprecatedProjectionAndNestedTypesMatchAuthority
// ports "samples, sensitive outputs, deprecated projection, and nested
// types match authority".
func TestSamplesSensitiveOutputsDeprecatedProjectionAndNestedTypesMatchAuthority(t *testing.T) {
	root := committedRoot(t)

	filtering, err := RenderModuleFiles(root, "zia_url_filtering_rules")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zia_url_filtering_rules): %v", err)
	}
	filteringSample, _ := filtering.Get(FileSampleTfvars)
	var filteringDecoded struct {
		Items struct {
			Example struct {
				Protocols []string `json:"protocols"`
			} `json:"example"`
		} `json:"items"`
	}
	if err := json.Unmarshal([]byte(filteringSample), &filteringDecoded); err != nil {
		t.Fatalf("unmarshal filtering sample: %v", err)
	}
	if want := []string{"ANY_RULE"}; !reflect.DeepEqual(filteringDecoded.Items.Example.Protocols, want) {
		t.Errorf("protocols = %v, want %v", filteringDecoded.Items.Example.Protocols, want)
	}

	sensitive, err := RenderModuleFiles(root, "zia_location_management")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zia_location_management): %v", err)
	}
	sensitiveOutputs, _ := sensitive.Get(FileOutputs)
	mustMatch(t, sensitiveOutputs, `sensitive\s+= true`)

	deprecated, err := RenderModuleFiles(root, "zpa_policy_access_rule")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zpa_policy_access_rule): %v", err)
	}
	deprecatedOutputs, _ := deprecated.Get(FileOutputs)
	mustMatch(t, deprecatedOutputs, `excludes deprecated: rule_order`)
	mustNotMatch(t, deprecatedOutputs, `rule_order = v\.rule_order`)

	framework, err := RenderModuleFiles(root, "zcc_zia_posture")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zcc_zia_posture): %v", err)
	}
	frameworkVariables, _ := framework.Get(FileVariables)
	mustMatch(t, frameworkVariables, `high_trust_criteria = optional\(object\(\{`)
	mustMatch(t, frameworkVariables, `cs = optional\(list\(object\(\{`)

	requiredBlock, err := RenderModuleFiles(root, "zpa_policy_access_rule_reorder")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zpa_policy_access_rule_reorder): %v", err)
	}
	requiredSample, _ := requiredBlock.Get(FileSampleTfvars)
	var requiredDecoded struct {
		Items struct {
			Example struct {
				Rules []json.RawMessage `json:"rules"`
			} `json:"example"`
		} `json:"items"`
	}
	if err := json.Unmarshal([]byte(requiredSample), &requiredDecoded); err != nil {
		t.Fatalf("unmarshal required-block sample: %v", err)
	}
	if got := len(requiredDecoded.Items.Example.Rules); got != 1 {
		t.Errorf("rules length = %d, want 1", got)
	}
}

func TestZPAProvider449ModuleShapesMatchReviewedSchemaTransitions(t *testing.T) {
	root := committedRoot(t)
	for _, test := range []struct {
		resourceType string
		pattern      string
	}{
		{"zpa_application_segment_browser_access", `clientless_apps = optional\(set\(object\(\{`},
		{"zpa_browser_access", `clientless_apps = optional\(set\(object\(\{`},
		{"zpa_application_segment_pra", `apps_config = optional\(set\(object\(\{`},
	} {
		files, err := RenderModuleFiles(root, test.resourceType)
		if err != nil {
			t.Fatalf("RenderModuleFiles(%s): %v", test.resourceType, err)
		}
		variables, _ := files.Get(FileVariables)
		mustMatch(t, variables, test.pattern)
	}

	for _, resourceType := range []string{"zpa_policy_access_rule", "zpa_policy_access_rule_v2"} {
		files, err := RenderModuleFiles(root, resourceType)
		if err != nil {
			t.Fatalf("RenderModuleFiles(%s): %v", resourceType, err)
		}
		variables, _ := files.Get(FileVariables)
		main, _ := files.Get(FileMain)
		mustMatch(t, variables, `device_posture_failure_notification_enabled = optional\(bool\)`)
		mustMatch(t, main, `device_posture_failure_notification_enabled = each\.value\.device_posture_failure_notification_enabled`)
	}

	capabilities, err := RenderModuleFiles(root, "zpa_policy_capabilities_rule")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zpa_policy_capabilities_rule): %v", err)
	}
	capabilityVariables, _ := capabilities.Get(FileVariables)
	mustMatch(t, capabilityVariables, `control_session\s+= optional\(bool\)`)
	mustMatch(t, capabilityVariables, `join_session\s+= optional\(bool\)`)

	portal, err := RenderModuleFiles(root, "zpa_policy_portal_access_rule")
	if err != nil {
		t.Fatalf("RenderModuleFiles(zpa_policy_portal_access_rule): %v", err)
	}
	portalVariables, _ := portal.Get(FileVariables)
	for _, field := range []string{"access_uninspected_file_sandbox", "upload_inspected_sandbox", "upload_inspected_scan"} {
		mustMatch(t, portalVariables, field+`\s+= optional\(bool\)`)
	}
	mustMatch(t, portalVariables, `privileged_portal_capabilities = optional\(tuple\(\[object\(\{`)
	mustNotMatch(t, portalVariables, `privileged_portal_capabilities = optional\(list\(`)
	mustNotMatch(t, portalVariables, `privileged_portal_capabilities = optional\(object\(`)
	portalMain, _ := portal.Get(FileMain)
	mustMatch(t, portalMain, `for_each = each\.value\.privileged_portal_capabilities == null \? \[\] : each\.value\.privileged_portal_capabilities`)
}

func TestModuleSingleBlocksConstrainGeneratedShapeWithoutMutatingProviderSchema(t *testing.T) {
	schema := metadata.JsonObject{
		"block": metadata.JsonObject{
			"attributes": metadata.JsonObject{
				"name": metadata.JsonObject{"type": "string", "required": true},
			},
			"block_types": metadata.JsonObject{
				"capabilities": metadata.JsonObject{
					"nesting_mode": "list",
					"block": metadata.JsonObject{
						"attributes": metadata.JsonObject{
							"enabled": metadata.JsonObject{"type": "bool", "optional": true},
						},
					},
				},
			},
		},
	}
	_, root := syntheticRoot(t, syntheticRootOptions{
		Schema:       schema,
		OverrideText: `{"module_single_blocks":["capabilities"]}`,
	})
	rendered, err := RenderModuleFiles(root, "sample_resource")
	if err != nil {
		t.Fatalf("RenderModuleFiles(module_single_blocks): %v", err)
	}
	variables, _ := rendered.Get(FileVariables)
	mustMatch(t, variables, `capabilities = optional\(tuple\(\[object\(\{`)
	mustNotMatch(t, variables, `capabilities = optional\(list\(`)
	mustNotMatch(t, variables, `capabilities = optional\(object\(`)
	main, _ := rendered.Get(FileMain)
	mustMatch(t, main, `for_each = each\.value\.capabilities == null \? \[\] : each\.value\.capabilities`)

	authority, err := root.LoadResourceSchema("sample_resource")
	if err != nil {
		t.Fatalf("LoadResourceSchema(sample_resource): %v", err)
	}
	block, err := metadata.TerraformBlockForSchema(authority, "sample_resource")
	if err != nil {
		t.Fatalf("TerraformBlockForSchema(sample_resource): %v", err)
	}
	blockTypes, err := metadata.TerraformBlockTypesForBlock(block, "sample_resource.block")
	if err != nil {
		t.Fatalf("TerraformBlockTypesForBlock(sample_resource): %v", err)
	}
	capabilities, err := metadata.TerraformRequireObject(blockTypes["capabilities"], "capabilities")
	if err != nil {
		t.Fatalf("TerraformRequireObject(capabilities): %v", err)
	}
	if _, mutated := capabilities["max_items"]; mutated {
		t.Fatal("module_single_blocks mutated the cached provider schema authority")
	}
	if _, mutated := capabilities[moduleSingleBlockMarker]; mutated {
		t.Fatal("module_single_blocks leaked its generator marker into the cached provider schema authority")
	}
}

// TestModuleSingleBlocksTerraformCardinality is the cheap, pack-independent
// Terraform contract for the singleton encoding. The V2 checkpoint separately
// proves that the real ZPA portal resource selects this generic behavior.
func TestModuleSingleBlocksTerraformCardinality(t *testing.T) {
	executable := terraformExecutable(t)
	schema := metadata.JsonObject{
		"block": metadata.JsonObject{
			"attributes": metadata.JsonObject{
				"name": metadata.JsonObject{"type": "string", "required": true},
			},
			"block_types": metadata.JsonObject{
				"capabilities": metadata.JsonObject{
					"nesting_mode": "list",
					"block": metadata.JsonObject{
						"attributes": metadata.JsonObject{
							"enabled": metadata.JsonObject{"type": "bool", "optional": true},
						},
					},
				},
			},
		},
	}
	_, packRoot := syntheticRoot(t, syntheticRootOptions{
		Schema:       schema,
		OverrideText: `{"module_single_blocks":["capabilities"]}`,
	})
	generatedRoot := t.TempDir()
	if _, err := GenerateModule(packRoot, "sample_resource", GenerateModuleOptions{
		OutputRoot: generatedRoot,
		FormatHCL:  NewHCLFormatter(),
	}); err != nil {
		t.Fatalf("GenerateModule(module_single_blocks Terraform contract): %v", err)
	}
	variables, err := os.ReadFile(filepath.Join(generatedRoot, "sample_resource", "variables.tf"))
	if err != nil {
		t.Fatalf("read generated variables.tf: %v", err)
	}

	root := t.TempDir()
	moduleDirectory := filepath.Join(root, "module")
	writeRawFile(t, filepath.Join(moduleDirectory, "variables.tf"), string(variables))
	writeRawFile(t, filepath.Join(moduleDirectory, "outputs.tf"), `output "capabilities" {
  value = var.items["example"].capabilities
}
`)
	writeRawFile(t, filepath.Join(root, "tests", "cardinality.tftest.hcl"), `run "one_capability_plan" {
  command = plan

  assert {
    condition     = output.capabilities[0].enabled == true
    error_message = "the singleton capability value was not preserved"
  }
}
`)
	writeConfiguration := func(capabilities string) {
		t.Helper()
		writeRawFile(t, filepath.Join(root, "main.tf"), fmt.Sprintf(`module "subject" {
  source = "./module"
  items = {
    example = {
      name         = "example"
      capabilities = %s
    }
  }
}

output "capabilities" {
  value = module.subject.capabilities
}
`, capabilities))
	}

	home := t.TempDir()
	environment := append(os.Environ(),
		"CHECKPOINT_DISABLE=1",
		"HOME="+home,
		"TF_DATA_DIR="+filepath.Join(root, ".terraform-data"),
		"TF_IN_AUTOMATION=1",
		"TF_INPUT=0",
	)
	run := func(arguments ...string) ([]byte, error) {
		t.Helper()
		command := exec.Command(executable, arguments...)
		command.Dir = root
		command.Env = environment
		return command.CombinedOutput()
	}

	writeConfiguration(`[
      { enabled = true },
    ]`)
	if output, err := run("init", "-backend=false", "-no-color"); err != nil {
		t.Fatalf("terraform init failed: %v\n%s", err, output)
	}
	if output, err := run("test", "-test-directory=tests", "-no-color"); err != nil {
		t.Fatalf("terraform singleton plan failed: %v\n%s", err, output)
	}

	for _, testCase := range []struct {
		name  string
		value string
	}{
		{
			name: "two elements",
			value: `[
      { enabled = true },
      { enabled = false },
    ]`,
		},
		{
			name: "keyed object bypass",
			value: `{
      first  = { enabled = true }
      second = { enabled = false }
    }`,
		},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			writeConfiguration(testCase.value)
			output, err := run("validate", "-no-color")
			if err == nil {
				t.Fatalf("terraform accepted %s; want tuple rejection", testCase.name)
			}
			diagnostic := string(output)
			if !strings.Contains(diagnostic, "Invalid value for input variable") || !strings.Contains(diagnostic, "tuple required") {
				t.Fatalf("terraform rejection for %s = %q, want input-variable tuple diagnostic", testCase.name, diagnostic)
			}
		})
	}
}

func TestModuleSingleBlocksApplyStrictTupleToDottedNestedPath(t *testing.T) {
	_, root := syntheticRoot(t, syntheticRootOptions{
		Schema: metadata.JsonObject{
			"block": metadata.JsonObject{
				"attributes": metadata.JsonObject{
					"name": metadata.JsonObject{"type": "string", "required": true},
				},
				"block_types": metadata.JsonObject{
					"outer": metadata.JsonObject{
						"nesting_mode": "list",
						"block": metadata.JsonObject{
							"attributes": metadata.JsonObject{},
							"block_types": metadata.JsonObject{
								"capabilities": metadata.JsonObject{
									"nesting_mode": "set",
									"block": metadata.JsonObject{
										"attributes": metadata.JsonObject{
											"enabled": metadata.JsonObject{"type": "bool", "optional": true},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		OverrideText: `{"module_single_blocks":["outer.capabilities"]}`,
	})
	rendered, err := RenderModuleFiles(root, "sample_resource")
	if err != nil {
		t.Fatalf("RenderModuleFiles(nested module_single_blocks): %v", err)
	}
	variables, _ := rendered.Get(FileVariables)
	mustMatch(t, variables, `outer = optional\(list\(object\(\{`)
	mustMatch(t, variables, `capabilities = optional\(tuple\(\[object\(\{`)
	main, _ := rendered.Get(FileMain)
	mustMatch(t, main, `for_each = outer\.value\.capabilities == null \? \[\] : outer\.value\.capabilities`)
}

func TestModuleSingleBlocksFailOnMissingConflictingOrStaleSchemaPaths(t *testing.T) {
	baseBlock := func() metadata.JsonObject {
		return metadata.JsonObject{
			"attributes": metadata.JsonObject{
				"name": metadata.JsonObject{"type": "string", "required": true},
			},
			"block_types": metadata.JsonObject{
				"capabilities": metadata.JsonObject{
					"nesting_mode": "list",
					"block":        metadata.JsonObject{"attributes": metadata.JsonObject{}},
				},
			},
		}
	}
	tests := []struct {
		name      string
		path      string
		mutate    func(metadata.JsonObject)
		wantError string
	}{
		{"missing", "absent", func(metadata.JsonObject) {}, "does not exist"},
		{"stale", "capabilities", func(block metadata.JsonObject) {
			block["block_types"].(metadata.JsonObject)["capabilities"].(metadata.JsonObject)["max_items"] = float64(1)
		}, "already singleton"},
		{"minimum conflict", "capabilities", func(block metadata.JsonObject) {
			block["block_types"].(metadata.JsonObject)["capabilities"].(metadata.JsonObject)["min_items"] = float64(2)
		}, "min_items greater than one"},
	}
	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			block := baseBlock()
			testCase.mutate(block)
			_, root := syntheticRoot(t, syntheticRootOptions{
				Schema:       metadata.JsonObject{"block": block},
				OverrideText: fmt.Sprintf(`{"module_single_blocks":[%q]}`, testCase.path),
			})
			_, err := RenderModuleFiles(root, "sample_resource")
			if err == nil || !strings.Contains(err.Error(), testCase.wantError) {
				t.Fatalf("RenderModuleFiles(module_single_blocks) error = %v, want error containing %q", err, testCase.wantError)
			}
		})
	}
}

// TestResourceOwnedMainOverrideAndJSONSampleComeOnlyThroughTheLoader ports
// "resource-owned main override and JSON sample come only through the
// loader".
func TestResourceOwnedMainOverrideAndJSONSampleComeOnlyThroughTheLoader(t *testing.T) {
	_, root := syntheticRoot(t, syntheticRootOptions{
		MainOverride: "# resource-owned override\n",
		Sample:       metadata.JsonObject{"name": "chosen", "extra": float64(7)},
	})
	output := t.TempDir()

	mainOverride, err := root.LoadResourceMainOverride("sample_resource")
	if err != nil {
		t.Fatalf("LoadResourceMainOverride: %v", err)
	}
	if mainOverride == nil || *mainOverride != "# resource-owned override\n" {
		t.Fatalf("LoadResourceMainOverride = %v, want %q", mainOverride, "# resource-owned override\n")
	}

	rendered, err := RenderModuleFiles(root, "sample_resource")
	if err != nil {
		t.Fatalf("RenderModuleFiles: %v", err)
	}
	main, _ := rendered.Get(FileMain)
	if main != "# resource-owned override\n" {
		t.Errorf("main.tf = %q, want %q", main, "# resource-owned override\n")
	}

	sample, _ := rendered.Get(FileSampleTfvars)
	var decoded struct {
		Items struct {
			Example map[string]any `json:"example"`
		} `json:"items"`
	}
	if err := json.Unmarshal([]byte(sample), &decoded); err != nil {
		t.Fatalf("unmarshal sample: %v", err)
	}
	want := map[string]any{
		"extra": float64(7),
		"name":  "chosen",
		"rules": []any{map[string]any{"enabled": true}},
	}
	if !reflect.DeepEqual(decoded.Items.Example, want) {
		t.Errorf("sample.items.example = %#v, want %#v", decoded.Items.Example, want)
	}

	generated, err := GenerateModule(root, "sample_resource", GenerateModuleOptions{
		OutputRoot: output,
		FormatHCL:  IdentityFormatter,
	})
	if err != nil {
		t.Fatalf("GenerateModule: %v", err)
	}
	if len(generated.Files) != 7 {
		t.Errorf("generated.Files length = %d, want 7", len(generated.Files))
	}

	validated, err := ValidateGeneratedModuleTree(output, []string{"sample_resource"})
	if err != nil {
		t.Fatalf("ValidateGeneratedModuleTree: %v", err)
	}
	if !reflect.DeepEqual(validated, []string{"sample_resource"}) {
		t.Errorf("ValidateGeneratedModuleTree = %v, want [sample_resource]", validated)
	}
}

// TestSingleInputBlocksWrapOneObjectWhileComputedOnlyBlocksDisappear ports
// "single input blocks wrap one object while computed-only blocks
// disappear".
func TestSingleInputBlocksWrapOneObjectWhileComputedOnlyBlocksDisappear(t *testing.T) {
	_, root := syntheticRoot(t, syntheticRootOptions{
		Schema: metadata.JsonObject{
			"block": metadata.JsonObject{
				"attributes": metadata.JsonObject{
					"name": metadata.JsonObject{"type": "string", "required": true},
				},
				"block_types": metadata.JsonObject{
					"settings": metadata.JsonObject{
						"nesting_mode": "single",
						"block": metadata.JsonObject{
							"attributes": metadata.JsonObject{
								"on": metadata.JsonObject{"type": "bool", "optional": true},
							},
						},
					},
					"observed": metadata.JsonObject{
						"nesting_mode": "set",
						"block": metadata.JsonObject{
							"attributes": metadata.JsonObject{
								"value": metadata.JsonObject{"type": "string", "computed": true},
							},
						},
					},
				},
			},
		},
	})
	rendered, err := RenderModuleFiles(root, "sample_resource")
	if err != nil {
		t.Fatalf("RenderModuleFiles: %v", err)
	}
	main, _ := rendered.Get(FileMain)
	mustMatch(t, main, `each\.value\.settings == null \? \[\] : \[each\.value\.settings\]`)
	variables, _ := rendered.Get(FileVariables)
	mustMatch(t, variables, `settings = optional\(object\(\{`)
	mustNotMatch(t, main, `dynamic "observed"`)
	mustNotMatch(t, variables, `observed =`)
}

// TestFractionalSampleOverrideNumbersRetainExactPythonJSONSpelling ports
// "fractional sample override numbers retain exact Python JSON spelling".
func TestFractionalSampleOverrideNumbersRetainExactPythonJSONSpelling(t *testing.T) {
	_, root := syntheticRoot(t, syntheticRootOptions{
		OverrideText: "{\"sample\":{\"half\":0.5,\"negative_zero\":-0.0,\"scientific\":1e-6}}\n",
	})
	rendered, err := RenderModuleFiles(root, "sample_resource")
	if err != nil {
		t.Fatalf("RenderModuleFiles: %v", err)
	}
	sample, _ := rendered.Get(FileSampleTfvars)
	mustMatch(t, sample, `"half": 0\.5`)
	mustMatch(t, sample, `"negative_zero": -0\.0`)
	mustMatch(t, sample, `"scientific": 1e-06`)
}

// TestAllActiveResourcesGenerateAndValidateACompleteTemporaryTree ports
// "all active resources generate and validate a complete temporary tree".
func TestAllActiveResourcesGenerateAndValidateACompleteTemporaryTree(t *testing.T) {
	root := committedRoot(t)
	output := t.TempDir()

	types := ActiveGeneratedResourceTypes(root)
	if len(types) != 151 {
		t.Fatalf("ActiveGeneratedResourceTypes length = %d, want 151", len(types))
	}
	generated, err := GenerateActiveModules(root, GenerateModuleOptions{
		OutputRoot: output,
		FormatHCL:  IdentityFormatter,
	})
	if err != nil {
		t.Fatalf("GenerateActiveModules: %v", err)
	}
	if len(generated) != 151 {
		t.Fatalf("generated length = %d, want 151", len(generated))
	}
	total := 0
	for _, module := range generated {
		total += len(module.Files)
	}
	if total != 1057 {
		t.Errorf("total generated files = %d, want 1057", total)
	}
	validated, err := ValidateGeneratedModuleTree(output, ActiveGeneratedResourceTypes(root))
	if err != nil {
		t.Fatalf("ValidateGeneratedModuleTree: %v", err)
	}
	if len(validated) != 151 {
		t.Errorf("validated length = %d, want 151", len(validated))
	}
}

// packSetFile is the minimal shape this test reads from a committed
// packs/<name>.packset.json document: just enough to physically reduce a pack
// root to the packs (and shared components) a profile actually needs.
type packSetFile struct {
	Packs  []string `json:"packs"`
	Shared []string `json:"shared"`
}

func readPackSetFile(t *testing.T, path string) packSetFile {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var doc packSetFile
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("unmarshal %s: %v", path, err)
	}
	return doc
}

// copyDir recursively copies src to dst.
func copyDir(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.WalkDir(src, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		relative, relErr := filepath.Rel(src, path)
		if relErr != nil {
			return relErr
		}
		target := filepath.Join(dst, relative)
		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if mkErr := os.MkdirAll(filepath.Dir(target), 0o755); mkErr != nil {
			return mkErr
		}
		return os.WriteFile(target, data, 0o644)
	})
	if err != nil {
		t.Fatalf("copyDir %s -> %s: %v", src, dst, err)
	}
}

// TestEveryCommittedProfileDrivesGenerationFromItsPhysicallyReducedPackRoot
// ports "every committed profile drives generation from its physically
// reduced pack root".
func TestEveryCommittedProfileDrivesGenerationFromItsPhysicallyReducedPackRoot(t *testing.T) {
	root := repoRoot(t)
	expected := map[string]int{
		"full": 151, "zscaler": 151, "zcc": 7, "zia": 74, "zpa": 54, "ztc": 16,
		"empty": 0, "aws": 0, "cloudflare": 0, "google": 0, "netbox": 0,
	}
	profileNames := make([]string, 0, len(expected))
	for name := range expected {
		profileNames = append(profileNames, name)
	}
	sort.Strings(profileNames)

	for _, profileName := range profileNames {
		count := expected[profileName]
		t.Run(profileName, func(t *testing.T) {
			directory := t.TempDir()
			output := t.TempDir()
			profilePath := filepath.Join(root, "packs", profileName+".packset.json")
			doc := readPackSetFile(t, profilePath)
			for _, name := range doc.Packs {
				copyDir(t, filepath.Join(root, "packs", name), filepath.Join(directory, name))
			}
			for _, name := range doc.Shared {
				copyDir(t, filepath.Join(root, "packs", "_shared", name), filepath.Join(directory, "_shared", name))
			}
			loaded, err := metadata.LoadPackRoot(metadata.LoadPackRootOptions{
				PacksRoot:   directory,
				ProfilePath: &profilePath,
			})
			if err != nil {
				t.Fatalf("LoadPackRoot: %v", err)
			}
			generated, err := GenerateActiveModules(loaded, GenerateModuleOptions{
				OutputRoot: output,
				FormatHCL:  IdentityFormatter,
			})
			if err != nil {
				t.Fatalf("GenerateActiveModules: %v", err)
			}
			if len(generated) != count {
				t.Fatalf("generated length = %d, want %d", len(generated), count)
			}
			total := 0
			for _, module := range generated {
				total += len(module.Files)
			}
			if total != count*7 {
				t.Errorf("total generated files = %d, want %d", total, count*7)
			}
			if _, err := ValidateGeneratedModuleTree(output, ActiveGeneratedResourceTypes(loaded)); err != nil {
				t.Errorf("ValidateGeneratedModuleTree: %v", err)
			}
		})
	}
}

// TestHCLFormatterMatchesTerraformAcrossFullGeneratedCorpus proves that the
// in-process token formatter is byte-identical to terraform fmt for every HCL
// artifact produced by the full 151-resource profile. Terraform formats one
// temporary tree recursively so this differential gate does not recreate the
// per-file subprocess cost that production has removed.
func TestHCLFormatterMatchesTerraformAcrossFullGeneratedCorpus(t *testing.T) {
	if testing.Short() {
		t.Skip("full generated-corpus Terraform differential skipped under -short")
	}
	executable := terraformExecutable(t)
	root := committedRoot(t)
	formatter := NewHCLFormatter()
	oracleRoot := t.TempDir()

	type formattedFile struct {
		path string
		want string
	}
	var formatted []formattedFile
	for _, resourceType := range ActiveGeneratedResourceTypes(root) {
		rendered, err := RenderModuleFiles(root, resourceType)
		if err != nil {
			t.Fatalf("RenderModuleFiles(%s): %v", resourceType, err)
		}
		for _, name := range ExpectedModuleFiles {
			if !needsTerraformFormat(name) {
				continue
			}
			source, ok := rendered.Get(name)
			if !ok {
				t.Fatalf("RenderModuleFiles(%s) omitted %s", resourceType, name)
			}
			want, err := formatter.FormatHCL(source)
			if err != nil {
				t.Fatalf("FormatHCL(%s/%s): %v", resourceType, name, err)
			}
			path := filepath.Join(oracleRoot, resourceType, string(name))
			if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
				t.Fatalf("MkdirAll(%s): %v", filepath.Dir(path), err)
			}
			if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
				t.Fatalf("WriteFile(%s): %v", path, err)
			}
			formatted = append(formatted, formattedFile{path: path, want: want})
		}
	}

	command := exec.Command(executable, "fmt", "-recursive", oracleRoot)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("terraform fmt -recursive %s: %v\n%s", oracleRoot, err, output)
	}
	for _, file := range formatted {
		got, err := os.ReadFile(file.path)
		if err != nil {
			t.Fatalf("ReadFile(%s): %v", file.path, err)
		}
		if string(got) != file.want {
			relative, relErr := filepath.Rel(oracleRoot, file.path)
			if relErr != nil {
				relative = file.path
			}
			t.Errorf("%s differs after hclwrite.Format and terraform fmt", relative)
		}
	}
	if len(formatted) != 151*5 {
		t.Errorf("compared = %d, want %d", len(formatted), 151*5)
	}
}

// TestMissingMetadataAndUnsupportedNestingModesFailLoudly ports "missing
// metadata and unsupported nesting modes fail loudly".
func TestMissingMetadataAndUnsupportedNestingModesFailLoudly(t *testing.T) {
	_, noPin := syntheticRoot(t, syntheticRootOptions{OmitPin: true})
	if _, err := RenderModuleFiles(noPin, "sample_resource"); err == nil || !strings.Contains(err.Error(), "no version pin") {
		t.Errorf("noPin: err = %v, want message containing %q", err, "no version pin")
	}

	_, noSource := syntheticRoot(t, syntheticRootOptions{OmitSource: true})
	if _, err := RenderModuleFiles(noSource, "sample_resource"); err == nil || !strings.Contains(err.Error(), "no source") {
		t.Errorf("noSource: err = %v, want message containing %q", err, "no source")
	}

	_, unsupported := syntheticRoot(t, syntheticRootOptions{
		Schema: metadata.JsonObject{
			"block": metadata.JsonObject{
				"attributes": metadata.JsonObject{
					"name": metadata.JsonObject{"type": "string", "required": true},
				},
				"block_types": metadata.JsonObject{
					"settings": metadata.JsonObject{
						"nesting_mode": "group",
						"block": metadata.JsonObject{
							"attributes": metadata.JsonObject{
								"on": metadata.JsonObject{"type": "bool", "optional": true},
							},
						},
					},
				},
			},
		},
	})
	if _, err := RenderModuleFiles(unsupported, "sample_resource"); err == nil || !strings.Contains(err.Error(), `unsupported nesting_mode "group"`) {
		t.Errorf("unsupported: err = %v, want message containing %q", err, `unsupported nesting_mode "group"`)
	}
}

// TestTreeValidationAndFormatterFailuresPreserveConcreteDiagnostics ports
// "tree validation and Terraform formatter failures preserve concrete
// diagnostics" while exercising the in-process formatter's fail-closed path.
func TestTreeValidationAndFormatterFailuresPreserveConcreteDiagnostics(t *testing.T) {
	directory := t.TempDir()

	if _, err := ValidateGeneratedModuleTree(directory, []string{"sample_resource"}); err == nil ||
		!strings.Contains(err.Error(), filepath.Join("sample_resource", "main.tf")) {
		t.Errorf("ValidateGeneratedModuleTree: err = %v, want message containing %q", err, filepath.Join("sample_resource", "main.tf"))
	}

	if _, err := NewHCLFormatter().FormatHCL("resource \"x\" \"y\" {\n"); err == nil ||
		!strings.Contains(err.Error(), "generated HCL is invalid") {
		t.Errorf("FormatHCL invalid source: err = %v, want generated-HCL diagnostic", err)
	}
}

func mustMatch(t *testing.T, text, pattern string) {
	t.Helper()
	if !regexp.MustCompile(pattern).MatchString(text) {
		t.Errorf("expected match for %s in:\n%s", pattern, text)
	}
}

func mustNotMatch(t *testing.T, text, pattern string) {
	t.Helper()
	if regexp.MustCompile(pattern).MatchString(text) {
		t.Errorf("expected no match for %s in:\n%s", pattern, text)
	}
}
