# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

resource "cloudflare_load_balancer_monitor" "this" {
  for_each = var.items

  account_id       = each.value.account_id
  allow_insecure   = each.value.allow_insecure
  consecutive_down = each.value.consecutive_down
  consecutive_up   = each.value.consecutive_up
  description      = each.value.description
  expected_body    = each.value.expected_body
  expected_codes   = each.value.expected_codes
  follow_redirects = each.value.follow_redirects
  header           = each.value.header
  interval         = each.value.interval
  method           = each.value.method
  path             = each.value.path
  port             = each.value.port
  probe_zone       = each.value.probe_zone
  retries          = each.value.retries
  timeout          = each.value.timeout
  type             = each.value.type
}
