# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "cloudflare_load_balancer_monitor instances, keyed by a stable identifier."
  type = map(object({
    account_id       = string
    allow_insecure   = optional(bool)
    consecutive_down = optional(number)
    consecutive_up   = optional(number)
    description      = optional(string)
    expected_body    = optional(string)
    expected_codes   = optional(string)
    follow_redirects = optional(bool)
    header           = optional(map(list(string)))
    interval         = optional(number)
    method           = optional(string)
    path             = optional(string)
    port             = optional(number)
    probe_zone       = optional(string)
    retries          = optional(number)
    timeout          = optional(number)
    type             = optional(string)
  }))
}
