import { LosslessNumber } from "lossless-json";

import {
  canonicalPythonNumberToken,
  pythonFiniteFloatToken,
} from "../json/python-number.js";
import { sortedStrings } from "../json/python-compatible.js";
import { renderHclQuotedString } from "./import-moves.js";

export const HCL_TFVARS_HEADER =
  "# Generated by infrawright. Do not edit; regenerate via make transform/adopt.";

const BARE_KEY = /^[A-Za-z_][A-Za-z0-9_]*$/;

type HclRecord = Readonly<Record<string, unknown>>;

export type HclTfvarsComments = Readonly<Record<string, string>>;

function isRecord(value: unknown): value is HclRecord {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return false;
  }
  const prototype = Object.getPrototypeOf(value) as unknown;
  return prototype === Object.prototype || prototype === null;
}

function requireRecord(value: unknown, label: string): HclRecord {
  if (!isRecord(value)) throw new TypeError(`${label} must be a JSON object`);
  return value;
}

export function hclTfvarsCommentKey(
  itemKey: string,
  field: string,
  index: number | null = null,
): string {
  return JSON.stringify([itemKey, field, index]);
}

function commentMap(
  comments: HclTfvarsComments,
): ReadonlyMap<string, string> {
  const output = new Map<string, string>();
  for (const key of Object.keys(comments)) {
    const text = comments[key];
    if (typeof text !== "string") throw new TypeError("HCL tfvars comments are malformed");
    if (text.includes("\n") || text.includes("\r")) {
      throw new TypeError("HCL tfvars comments must be single-line");
    }
    output.set(key, text);
  }
  return output;
}

function quotedKey(key: string): string {
  return renderHclQuotedString(key);
}

function attributeKey(key: string): string {
  return BARE_KEY.test(key) ? key : quotedKey(key);
}

function pythonLength(value: string): number {
  return Array.from(value).length;
}

function isMultilineValue(value: unknown): boolean {
  return (Array.isArray(value) && value.length > 0)
    || (isRecord(value) && Object.keys(value).length > 0);
}

function scalarLiteral(value: unknown): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "string") return renderHclQuotedString(value);
  if (value instanceof LosslessNumber) {
    const token = canonicalPythonNumberToken(value.toString());
    if (token === null) {
      throw new TypeError("non-finite number cannot render as HCL");
    }
    return token;
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new TypeError(`non-finite float ${String(value)} cannot render as HCL`);
    }
    if (Object.is(value, -0)) return "-0.0";
    if (Number.isInteger(value)) {
      if (!Number.isSafeInteger(value)) {
        throw new TypeError("unsafe native integer cannot render losslessly as HCL");
      }
      return String(value);
    }
    const token = pythonFiniteFloatToken(value);
    if (token === null) throw new TypeError("non-finite number cannot render as HCL");
    return token;
  }
  throw new TypeError(`unsupported HCL tfvars value: ${typeof value}`);
}

function singlelineLiteral(value: unknown): string {
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
  } else if (isRecord(value)) {
    if (Object.keys(value).length === 0) return "{}";
  } else {
    return scalarLiteral(value);
  }
  throw new TypeError("expected single-line HCL tfvars value");
}

function fieldComment(
  comments: ReadonlyMap<string, string>,
  itemKey: string | null,
  field: string,
): string | null {
  if (itemKey === null) return null;
  return comments.get(hclTfvarsCommentKey(itemKey, field)) ?? null;
}

function listComment(
  comments: ReadonlyMap<string, string>,
  itemKey: string | null,
  field: string | null,
  index: number,
): string | null {
  if (itemKey === null || field === null) return null;
  return comments.get(hclTfvarsCommentKey(itemKey, field, index)) ?? null;
}

function appendSinglelineGroup(
  lines: string[],
  group: readonly (readonly [string, string, unknown])[],
  indent: number,
  comments: ReadonlyMap<string, string>,
  itemKey: string | null,
): void {
  if (group.length === 0) return;
  const width = Math.max(...group.map(([, token]) => pythonLength(token)));
  const entries = group.map(([key, token, value]) => {
    const prefix = `${" ".repeat(indent)}${token}${" ".repeat(width - pythonLength(token))} = `;
    return {
      base: prefix + singlelineLiteral(value),
      comment: fieldComment(comments, itemKey, key),
    };
  });
  const commentWidth = Math.max(
    0,
    ...entries.filter((entry) => entry.comment !== null).map((entry) => pythonLength(entry.base)),
  );
  for (const entry of entries) {
    lines.push(entry.comment === null
      ? entry.base
      : `${entry.base}${" ".repeat(commentWidth - pythonLength(entry.base) + 1)}# ${entry.comment}`);
  }
}

function appendListElement(
  lines: string[],
  value: unknown,
  indent: number,
  comment: string | null,
  commentWidth = 0,
): void {
  const prefix = " ".repeat(indent);
  if (!isMultilineValue(value)) {
    const base = `${prefix}${singlelineLiteral(value)},`;
    lines.push(comment === null
      ? base
      : `${base}${" ".repeat(commentWidth - pythonLength(base) + 1)}# ${comment}`);
    return;
  }
  const suffix = comment === null ? "," : `, # ${comment}`;
  if (isRecord(value)) {
    lines.push(`${prefix}{`);
    appendObjectBody(lines, value, indent + 2, new Map(), null, false, false);
    lines.push(`${prefix}}${suffix}`);
    return;
  }
  if (!Array.isArray(value)) throw new TypeError("expected HCL list value");
  lines.push(`${prefix}[`);
  for (const nested of value) appendListElement(lines, nested, indent + 2, null);
  lines.push(`${prefix}]${suffix}`);
}

function appendListAssignment(
  lines: string[],
  prefix: string,
  values: readonly unknown[],
  indent: number,
  comments: ReadonlyMap<string, string>,
  itemKey: string | null,
  field: string | null,
): void {
  if (values.length === 0) {
    lines.push(`${prefix}[]`);
    return;
  }
  lines.push(`${prefix}[`);
  const elementIndent = indent + 2;
  const entries = values.map((value, index) => ({
    value,
    comment: listComment(comments, itemKey, field, index),
  }));
  const commentWidth = Math.max(0, ...entries.map((entry) => {
    return entry.comment !== null && !isMultilineValue(entry.value)
      ? pythonLength(`${" ".repeat(elementIndent)}${singlelineLiteral(entry.value)},`)
      : 0;
  }));
  for (const entry of entries) {
    appendListElement(lines, entry.value, elementIndent, entry.comment, commentWidth);
  }
  lines.push(`${" ".repeat(indent)}]`);
}

function appendMultilineAssignment(
  lines: string[],
  prefix: string,
  value: unknown,
  indent: number,
  comments: ReadonlyMap<string, string>,
  itemKey: string | null,
  field: string,
): void {
  if (isRecord(value)) {
    lines.push(`${prefix}{`);
    appendObjectBody(lines, value, indent + 2, comments, itemKey, false, false);
    lines.push(`${" ".repeat(indent)}}`);
    return;
  }
  if (!Array.isArray(value)) throw new TypeError("expected multiline HCL value");
  appendListAssignment(lines, prefix, value, indent, comments, itemKey, field);
}

function appendObjectBody(
  lines: string[],
  mapping: HclRecord,
  indent: number,
  comments: ReadonlyMap<string, string>,
  itemKey: string | null,
  quoteAllKeys: boolean,
  topLevelItems: boolean,
): void {
  const keys = sortedStrings(Object.keys(mapping));
  let group: Array<readonly [string, string, unknown]> = [];
  for (const key of keys) {
    const token = quoteAllKeys ? quotedKey(key) : attributeKey(key);
    const value = mapping[key];
    if (isMultilineValue(value)) {
      appendSinglelineGroup(lines, group, indent, comments, itemKey);
      group = [];
      const nextItemKey = topLevelItems ? key : Array.isArray(value) ? itemKey : null;
      appendMultilineAssignment(
        lines,
        `${" ".repeat(indent)}${token} = `,
        value,
        indent,
        comments,
        nextItemKey,
        key,
      );
    } else {
      group.push([key, token, value]);
    }
  }
  appendSinglelineGroup(lines, group, indent, comments, itemKey);
}

/** Match engine.hcl_tfvars.render_tfvars_hcl byte-for-byte. */
export function renderTfvarsHcl(
  items: HclRecord,
  comments: HclTfvarsComments = {},
  varName = "items",
): string {
  if (!BARE_KEY.test(varName)) {
    throw new TypeError("tfvars variable name must be a bare HCL identifier");
  }
  const indexedComments = commentMap(comments);
  const data = requireRecord(items, "tfvars items");
  if (Object.keys(data).length === 0) return `${HCL_TFVARS_HEADER}\n${varName} = {}\n`;
  const lines = [HCL_TFVARS_HEADER, `${varName} = {`];
  appendObjectBody(lines, data, 2, indexedComments, null, true, true);
  lines.push("}");
  return `${lines.join("\n")}\n`;
}
