"""Generate isolated per-resource Terraform env roots from the registry.

One root per (tenant, resource_type): envs/<tenant>/<resource_type>/. Each
calls a single module, keeping state blast-radius per resource (user's choice).
The tenant label is an opaque filesystem-safe identifier ([A-Za-z0-9_.-]+);
the Makefile gates enforce this. API targeting comes from env vars at plan
time, never from the label. Authoring-side; output committed; never hand-edited.
Stdlib-only, Python 3.6-floor — see AGENTS.md rules 5-7.
"""
import json
import os
import subprocess
import sys

from engine import artifacts
from engine import deployment
from engine import expression_bindings
from engine import packs

ENVS_ROOT = "envs"
EXPRESSION_BINDINGS_TF = "expression_bindings.tf"


def _provider_of(resource_type):
    return packs.provider_of(resource_type)


def _config_file(tenant, resource_type):
    return artifacts.config_file(tenant, resource_type)


def _expression_bindings_file(tenant, resource_type):
    return artifacts.expression_bindings_file(tenant, resource_type)


def _generated_expression_bindings_file(tenant, resource_type):
    return artifacts.generated_expression_bindings_file(tenant, resource_type)


def _tenant_env_dir(tenant, out_root=None):
    return artifacts.tenant_env_dir(tenant, out_root=out_root)


def _env_root_dir(tenant, resource_type, out_root=None):
    return artifacts.env_root_under(tenant, resource_type, out_root=out_root)


def _env_root_label_dir(tenant, label, out_root=None):
    if out_root is None:
        return artifacts.env_root_for_label(tenant, label)
    return os.path.join(out_root, tenant, label)


def _module_dir(resource_type):
    return os.path.join(deployment.module_dir(), resource_type)


def _config_ref(tenant, resource_type, env_dir):
    return os.path.relpath(_config_file(tenant, resource_type), env_dir)


def expand_resources(selectors):
    """Expand optional resource/product selectors to generated resource types."""
    return artifacts.expand_resources(selectors)


def _module_source(resource_type, env_dir):
    module_src = os.path.relpath(_module_dir(resource_type), env_dir)
    if not module_src.startswith(("../", "./", "/")):
        module_src = "./" + module_src  # never a Terraform registry ref
    return module_src


def _expression_items_local(label, resource_type):
    if label == resource_type:
        return "infrawright_expression_bound_items"
    return "infrawright_%s_expression_bound_items" % resource_type


def render_env_main(label, member_types, tenant, env_dir, backend=None,
                    expression_binding_types=None):
    member_types = sorted(member_types)
    if not member_types:
        raise ValueError("env root %s must contain at least one resource type" % label)
    providers = sorted(set(_provider_of(resource_type)
                           for resource_type in member_types))
    if len(providers) != 1:
        raise ValueError(
            "env root %s spans providers: %s" % (label, ", ".join(providers))
        )
    provider = providers[0]
    if backend:
        backend_lines = (
            '  backend "%s" {\n'
            "    # Partial configuration. Storage details come from a\n"
            "    # work-side file at init: make plan BACKEND_CONFIG=<file>\n"
            "    # (copy backend.conf.example). The state key is derived\n"
            "    # per root: %s/%s.tfstate\n"
            "  }\n" % (backend, tenant, label)
        )
    else:
        backend_lines = (
            "  # local state — opt into remote state with\n"
            "  # make gen-env TENANT=%s BACKEND=azurerm\n" % tenant
        )
    expression_binding_types = set(expression_binding_types or [])
    member_blocks = []
    for resource_type in member_types:
        var_name = artifacts.tfvars_var_name(resource_type)
        module_items = "var.%s" % var_name
        if resource_type in expression_binding_types:
            module_items = "local.%s" % _expression_items_local(
                label, resource_type)
        member_blocks.append(
            'variable "%s" {\n'
            "  # opaque at the root; the module enforces the strict type.\n"
            "  type = any\n"
            "}\n\n"
            'module "%s" {\n'
            '  source = "%s"\n'
            "  items = %s\n"
            "}" % (
                var_name,
                resource_type,
                _module_source(resource_type, env_dir),
                module_items,
            )
        )
    return (
        "# GENERATED by engine.gen_env for tenant %r — do not edit.\n"
        "# Regenerate: make gen-env TENANT=%s\n\n"
        "terraform {\n"
        '  required_version = ">= 1.5"\n'
        "  required_providers {\n"
        "    %s = {\n"
        '      source = "%s"\n'
        "    }\n"
        "  }\n"
        "%s"
        "}\n\n"
        'provider "%s" {\n'
        "  # credentials via provider environment variables\n"
        "}\n\n%s\n"
        % (
            tenant, tenant, provider, packs.provider_sources()[provider],
            backend_lines, provider, "\n\n".join(member_blocks),
        )
    )


def render_env_expression_bindings(bindings, resource_type=None, label=None):
    if resource_type is None:
        return expression_bindings.render_hcl(bindings)
    return expression_bindings.render_hcl(
        bindings,
        items_var=artifacts.tfvars_var_name(resource_type),
        local_name=_expression_items_local(label or resource_type, resource_type),
    )


def _render_env_root_expression_bindings(label, bindings_by_type):
    sections = []
    for resource_type in sorted(bindings_by_type):
        text = render_env_expression_bindings(
            bindings_by_type[resource_type],
            resource_type=resource_type,
            label=label,
        )
        if text:
            sections.append(text.rstrip())
    if not sections:
        return ""
    return "\n\n".join(sections) + "\n"


def _validate_expression_bindings_against_config(bindings, config_file,
                                                var_name="items"):
    if not os.path.exists(config_file):
        raise ValueError(
            "expression bindings require projected config at %s" % config_file
        )
    if not config_file.endswith(".json"):
        # HCL tfvars cannot be read back (no HCL parser in the engine); skip
        # the binding/config cross-check rather than crash on non-JSON bytes.
        sys.stderr.write(
            "skip expression binding validation for %s "
            "(hcl tfvars; validation reads json only)\n" % config_file
        )
        return
    with open(config_file, encoding="utf-8") as f:
        config = json.load(f)
    items = config.get(var_name) if isinstance(config, dict) else None
    if not isinstance(items, dict):
        raise ValueError("%s must contain a %s object" % (config_file, var_name))
    expression_bindings.apply_bindings(items, bindings)


def _merge_binding_layers(layers):
    by_key_path = {}
    for bindings in layers:
        for binding in bindings:
            by_key_path[(binding["key"], binding["path"])] = binding
    return [
        by_key_path[key]
        for key in sorted(by_key_path)
    ]


def _load_expression_binding_layers(tenant, resource_type):
    layers = []
    for path in (
            _generated_expression_bindings_file(tenant, resource_type),
            _expression_bindings_file(tenant, resource_type),
    ):
        if os.path.exists(path):
            layers.append(expression_bindings.load_bindings(
                path, resource_type))
    return _merge_binding_layers(layers)


def _render_env_root_readme(label, member_types, tenant, env_dir=None):
    env_dir = env_dir or _env_root_label_dir(tenant, label)
    config_refs = [
        "%s=%s" % (
            artifacts.tfvars_var_name(resource_type),
            _config_ref(tenant, resource_type, env_dir),
        )
        for resource_type in sorted(member_types)
    ]
    return (
        "# %s / %s (generated env root)\n\n"
        "Grouped Terraform root for `%s` on tenant `%s`. GENERATED — do not\n"
        "edit (AGENTS.md rule 6); regenerate with `make gen-env TENANT=%s`.\n"
        "Config is loaded at plan time from the tenant's config dir, relative to\n"
        "this root: `%s`.\n"
        % (tenant, label, ", ".join(sorted(member_types)), tenant, tenant,
           "`, `".join(config_refs))
    )


def render_env_readme(resource_type, tenant, env_dir=None):
    env_dir = env_dir or _env_root_dir(tenant, resource_type)
    config_ref = _config_ref(tenant, resource_type, env_dir)
    return (
        "# %s / %s (generated env root)\n\n"
        "Isolated Terraform root for `%s` on tenant `%s`. GENERATED — do not\n"
        "edit (AGENTS.md rule 6); regenerate with `make gen-env TENANT=%s`.\n"
        "Config is loaded at plan time from the tenant's config dir, relative to\n"
        "this root: `%s`.\n"
        % (tenant, resource_type, resource_type, tenant, tenant, config_ref)
    )


def render_env_test(resource_type, tenant, env_dir=None, has_config=False,
                    config_format="json", var_name="items"):
    """Render the smoke test HCL for an env root.

    Always emits an empty_plan run block (mock provider, no credentials).
    When has_config is True, appends a config_plan block that loads the
    committed config via jsondecode(file(...)). Regenerate with
    ``make gen-env TENANT=<label>``; regenerating after adding config
    upgrades the smoke test automatically — check-envs keeps it honest.
    """
    provider = _provider_of(resource_type)
    env_dir = env_dir or _env_root_dir(tenant, resource_type)
    base = (
        "# GENERATED smoke test — the root composes and plans against a\n"
        "# mocked provider; no credentials. Regenerate: make gen-env TENANT=%s\n"
        'mock_provider "%s" {}\n\n'
        'run "empty_plan" {\n'
        "  command = plan\n\n"
        "  variables {\n"
        "    %s = {}\n"
        "  }\n"
        "}\n" % (tenant, provider, var_name)
    )
    if not has_config or config_format != "json":
        return base
    config_ref = _config_ref(tenant, resource_type, env_dir)
    config_block = (
        '\nrun "config_plan" {\n'
        "  command = plan\n\n"
        "  variables {\n"
        '    %s = jsondecode(file("%s")).%s\n'
        "  }\n"
        "}\n" % (var_name, config_ref, var_name)
    )
    return base + config_block


def render_env_root_test(label, member_types, tenant, env_dir=None,
                         has_config_by_type=None, config_format="json"):
    member_types = sorted(member_types)
    if len(member_types) == 1:
        resource_type = member_types[0]
        return render_env_test(
            resource_type,
            tenant,
            env_dir=env_dir,
            has_config=(has_config_by_type or {}).get(resource_type, False),
            config_format=config_format,
            var_name=artifacts.tfvars_var_name(resource_type),
        )
    providers = sorted(set(_provider_of(resource_type)
                           for resource_type in member_types))
    if len(providers) != 1:
        raise ValueError(
            "env root %s spans providers: %s" % (label, ", ".join(providers))
        )
    env_dir = env_dir or _env_root_label_dir(tenant, label)
    lines = [
        "# GENERATED smoke test — the root composes and plans against a",
        "# mocked provider; no credentials. Regenerate: make gen-env TENANT=%s"
        % tenant,
        'mock_provider "%s" {}' % providers[0],
        "",
        'run "empty_plan" {',
        "  command = plan",
        "",
        "  variables {",
    ]
    for resource_type in member_types:
        lines.append("    %s = {}" % artifacts.tfvars_var_name(resource_type))
    lines.extend(["  }", "}"])
    if config_format == "json" and has_config_by_type:
        configured = [
            resource_type for resource_type in member_types
            if has_config_by_type.get(resource_type)
        ]
        if configured:
            lines.extend([
                "",
                'run "config_plan" {',
                "  command = plan",
                "",
                "  variables {",
            ])
            for resource_type in configured:
                var_name = artifacts.tfvars_var_name(resource_type)
                lines.append(
                    '    %s = jsondecode(file("%s")).%s'
                    % (var_name, _config_ref(tenant, resource_type, env_dir),
                       var_name)
                )
            lines.extend(["  }", "}"])
    return "\n".join(lines) + "\n"


def _fmt(text):
    proc = subprocess.run(
        ["terraform", "fmt", "-"], input=text.encode(), stdout=subprocess.PIPE, check=True
    )
    return proc.stdout.decode()


def generate_env(tenant, out_root=None, fmt=True, backend=None,
                 selectors=None):
    """Generate (or faithfully regenerate) a tenant's env roots.

    The backend choice is recorded as data in envs/<tenant>/.backend so a
    later regeneration WITHOUT the backend argument (e.g. the check-envs
    drift gate) reproduces the same roots instead of silently reverting
    to local state.
    """
    artifacts.validate_tenant(tenant)
    selected_resources = expand_resources(selectors or [])
    selected_labels = sorted(set(artifacts.root_label(resource_type)
                                 for resource_type in selected_resources))
    tenant_env_dir = _tenant_env_dir(tenant, out_root=out_root)
    marker = os.path.join(tenant_env_dir, ".backend")
    if backend is None and os.path.exists(marker):
        with open(marker, encoding="utf-8") as f:
            backend = f.read().strip() or None
    os.makedirs(tenant_env_dir, exist_ok=True)
    if backend:
        with open(marker, "w", encoding="utf-8") as f:
            f.write(backend + "\n")
    for label in selected_labels:
        member_types = artifacts.root_members(label)
        base = _env_root_label_dir(tenant, label, out_root=out_root)
        os.makedirs(base, exist_ok=True)
        bindings_by_type = {}
        for resource_type in member_types:
            bindings = _load_expression_binding_layers(tenant, resource_type)
            if not bindings:
                continue
            _validate_expression_bindings_against_config(
                bindings,
                _config_file(tenant, resource_type),
                var_name=artifacts.tfvars_var_name(resource_type),
            )
            bindings_by_type[resource_type] = bindings
        main_text = render_env_main(
            label,
            member_types,
            tenant,
            base,
            backend=backend,
            expression_binding_types=sorted(bindings_by_type),
        )
        if fmt:
            main_text = _fmt(main_text)
        with open(os.path.join(base, "main.tf"), "w", encoding="utf-8") as f:
            f.write(main_text)
        sys.stderr.write("wrote %s\n" % os.path.join(base, "main.tf"))
        expression_dest = os.path.join(base, EXPRESSION_BINDINGS_TF)
        if bindings_by_type:
            expression_text = _render_env_root_expression_bindings(
                label, bindings_by_type)
            if fmt:
                expression_text = _fmt(expression_text)
            with open(expression_dest, "w", encoding="utf-8") as f:
                f.write(expression_text)
            sys.stderr.write("wrote %s\n" % expression_dest)
        elif os.path.exists(expression_dest):
            os.remove(expression_dest)
            sys.stderr.write("removed stale %s\n" % expression_dest)
        with open(os.path.join(base, "README.md"), "w", encoding="utf-8") as f:
            if (len(member_types) == 1
                    and artifacts.root_label(member_types[0])
                    == member_types[0]):
                f.write(render_env_readme(member_types[0], tenant, env_dir=base))
            else:
                f.write(_render_env_root_readme(
                    label, member_types, tenant, env_dir=base))
        tests_dir = os.path.join(base, "tests")
        os.makedirs(tests_dir, exist_ok=True)
        # Config existence is evaluated against the repo's config dir regardless
        # of out_root — committed config drives committed tests.
        has_config_by_type = dict(
            (resource_type, os.path.exists(_config_file(tenant, resource_type)))
            for resource_type in member_types
        )
        test_text = render_env_root_test(
            label, member_types, tenant, env_dir=base,
            has_config_by_type=has_config_by_type,
            config_format=deployment.tfvars_format())
        if fmt:
            test_text = _fmt(test_text)
        with open(os.path.join(tests_dir, "smoke.tftest.hcl"), "w", encoding="utf-8") as f:
            f.write(test_text)
        sys.stderr.write("wrote %s\n" % os.path.join(tests_dir, "smoke.tftest.hcl"))
        for resource_type in member_types:
            config_file = _config_file(tenant, resource_type)
            if not has_config_by_type[resource_type]:
                sys.stderr.write(
                    "NOTE %s: no config at %s — smoke test is STUB-only "
                    "(composes + plans an empty root; does NOT exercise config). "
                    "Materialize the config and re-run gen-env to upgrade it.\n"
                    % (resource_type, config_file))


USAGE = (
    "usage: python -m engine.gen_env <tenant> "
    "[--backend <backend>] [resource|product ...]\n"
)


def _parse_args(argv):
    if not argv:
        raise ValueError(USAGE.strip())
    tenant = argv[0]
    backend = None
    selectors = []
    i = 1
    while i < len(argv):
        if argv[i] == "--backend":
            if i + 1 >= len(argv):
                raise ValueError("--backend requires a value")
            backend = argv[i + 1]
            i += 2
        else:
            selectors.append(argv[i])
            i += 1
    return tenant, backend, selectors


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    try:
        tenant, backend, selectors = _parse_args(argv)
        generate_env(tenant, backend=backend, selectors=selectors)
    except ValueError as exc:
        sys.stderr.write("error: %s\n" % exc)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
