"""Generate isolated per-resource Terraform env roots from the registry.

One root per (tenant, resource_type): envs/<tenant>/<resource_type>/. Each
calls a single module, keeping state blast-radius per resource (user's choice).
The tenant label is an opaque filesystem-safe identifier ([A-Za-z0-9_.-]+);
the Makefile gates enforce this. API targeting comes from env vars at plan
time, never from the label. Authoring-side; output committed; never hand-edited.
Stdlib-only, Python 3.6-floor — see AGENTS.md rules 5-7.
"""
import os
import subprocess
import sys

from engine import ops
from engine import packs

ENVS_ROOT = "envs"


def _provider_of(resource_type):
    return packs.provider_of(resource_type)


def _config_file(tenant, resource_type):
    return ops.config_file(tenant, resource_type)


def _tenant_env_dir(tenant, out_root=None):
    return ops.tenant_env_dir(tenant, out_root=out_root)


def _env_root_dir(tenant, resource_type, out_root=None):
    return ops.env_root_under(tenant, resource_type, out_root=out_root)


def _config_ref(tenant, resource_type, env_dir):
    return os.path.relpath(_config_file(tenant, resource_type), env_dir)


def expand_resources(selectors):
    """Expand optional resource/product selectors to generated resource types."""
    return ops.expand_resources(selectors)


def render_env_main(resource_type, tenant, env_dir, backend=None):
    provider = _provider_of(resource_type)
    module_src = os.path.relpath(os.path.join("modules", resource_type), env_dir)
    if not module_src.startswith(("../", "./", "/")):
        module_src = "./" + module_src  # never a Terraform registry ref
    if backend:
        backend_lines = (
            '  backend "%s" {\n'
            "    # Partial configuration. Storage details come from a\n"
            "    # work-side file at init: make plan BACKEND_CONFIG=<file>\n"
            "    # (copy backend.conf.example). The state key is derived\n"
            "    # per root: %s/%s.tfstate\n"
            "  }\n" % (backend, tenant, resource_type)
        )
    else:
        backend_lines = (
            "  # local state — opt into remote state with\n"
            "  # make gen-env TENANT=%s BACKEND=azurerm\n" % tenant
        )
    return (
        "# GENERATED by engine.gen_env for tenant %r — do not edit.\n"
        "# Regenerate: make gen-env TENANT=%s\n\n"
        "terraform {\n"
        '  required_version = ">= 1.5"\n'
        "  required_providers {\n"
        "    %s = {\n"
        '      source = "%s"\n'
        "    }\n"
        "  }\n"
        "%s"
        "}\n\n"
        'provider "%s" {\n'
        "  # credentials via provider environment variables\n"
        "}\n\n"
        'variable "items" {\n'
        "  # opaque at the root; the module enforces the strict type.\n"
        "  type = any\n"
        "}\n\n"
        'module "%s" {\n'
        '  source = "%s"\n'
        "  items = var.items\n"
        "}\n"
        % (
            tenant, tenant, provider, packs.provider_sources()[provider],
            backend_lines, provider,
            resource_type, module_src,
        )
    )


def render_env_readme(resource_type, tenant, env_dir=None):
    env_dir = env_dir or _env_root_dir(tenant, resource_type)
    config_ref = _config_ref(tenant, resource_type, env_dir)
    return (
        "# %s / %s (generated env root)\n\n"
        "Isolated Terraform root for `%s` on tenant `%s`. GENERATED — do not\n"
        "edit (AGENTS.md rule 6); regenerate with `make gen-env TENANT=%s`.\n"
        "Config is loaded at plan time from the tenant's config dir, relative to\n"
        "this root: `%s`.\n"
        % (tenant, resource_type, resource_type, tenant, tenant, config_ref)
    )


def render_env_test(resource_type, tenant, env_dir=None, has_config=False):
    """Render the smoke test HCL for an env root.

    Always emits an empty_plan run block (mock provider, no credentials).
    When has_config is True, appends a config_plan block that loads the
    committed config via jsondecode(file(...)). Regenerate with
    ``make gen-env TENANT=<label>``; regenerating after adding config
    upgrades the smoke test automatically — check-envs keeps it honest.
    """
    provider = _provider_of(resource_type)
    env_dir = env_dir or _env_root_dir(tenant, resource_type)
    base = (
        "# GENERATED smoke test — the root composes and plans against a\n"
        "# mocked provider; no credentials. Regenerate: make gen-env TENANT=%s\n"
        'mock_provider "%s" {}\n\n'
        'run "empty_plan" {\n'
        "  command = plan\n\n"
        "  variables {\n"
        "    items = {}\n"
        "  }\n"
        "}\n" % (tenant, provider)
    )
    if not has_config:
        return base
    config_ref = _config_ref(tenant, resource_type, env_dir)
    config_block = (
        '\nrun "config_plan" {\n'
        "  command = plan\n\n"
        "  variables {\n"
        '    items = jsondecode(file("%s")).items\n'
        "  }\n"
        "}\n" % config_ref
    )
    return base + config_block


def _fmt(text):
    proc = subprocess.run(
        ["terraform", "fmt", "-"], input=text.encode(), stdout=subprocess.PIPE, check=True
    )
    return proc.stdout.decode()


def generate_env(tenant, out_root=None, fmt=True, backend=None,
                 selectors=None):
    """Generate (or faithfully regenerate) a tenant's env roots.

    The backend choice is recorded as data in envs/<tenant>/.backend so a
    later regeneration WITHOUT the backend argument (e.g. the check-envs
    drift gate) reproduces the same roots instead of silently reverting
    to local state.
    """
    tenant_env_dir = _tenant_env_dir(tenant, out_root=out_root)
    marker = os.path.join(tenant_env_dir, ".backend")
    if backend is None and os.path.exists(marker):
        with open(marker, encoding="utf-8") as f:
            backend = f.read().strip() or None
    os.makedirs(tenant_env_dir, exist_ok=True)
    if backend:
        with open(marker, "w", encoding="utf-8") as f:
            f.write(backend + "\n")
    for resource_type in expand_resources(selectors or []):
        base = _env_root_dir(tenant, resource_type, out_root=out_root)
        os.makedirs(base, exist_ok=True)
        main_text = render_env_main(resource_type, tenant, base, backend=backend)
        if fmt:
            main_text = _fmt(main_text)
        with open(os.path.join(base, "main.tf"), "w", encoding="utf-8") as f:
            f.write(main_text)
        sys.stderr.write("wrote %s\n" % os.path.join(base, "main.tf"))
        with open(os.path.join(base, "README.md"), "w", encoding="utf-8") as f:
            f.write(render_env_readme(resource_type, tenant, env_dir=base))
        tests_dir = os.path.join(base, "tests")
        os.makedirs(tests_dir, exist_ok=True)
        # Config existence is evaluated against the repo's config dir regardless
        # of out_root — committed config drives committed tests.
        config_file = _config_file(tenant, resource_type)
        has_config = os.path.exists(config_file)
        test_text = render_env_test(
            resource_type, tenant, env_dir=base, has_config=has_config)
        if fmt:
            test_text = _fmt(test_text)
        with open(os.path.join(tests_dir, "smoke.tftest.hcl"), "w", encoding="utf-8") as f:
            f.write(test_text)
        sys.stderr.write("wrote %s\n" % os.path.join(tests_dir, "smoke.tftest.hcl"))
        if not has_config:
            sys.stderr.write(
                "NOTE %s: no config at %s — smoke test is STUB-only "
                "(composes + plans an empty root; does NOT exercise config). "
                "Materialize the config and re-run gen-env to upgrade it.\n"
                % (resource_type, config_file))


USAGE = (
    "usage: python -m engine.gen_env <tenant> "
    "[--backend <backend>] [resource|product ...]\n"
)


def _parse_args(argv):
    if not argv:
        raise ValueError(USAGE.strip())
    tenant = argv[0]
    backend = None
    selectors = []
    i = 1
    while i < len(argv):
        if argv[i] == "--backend":
            if i + 1 >= len(argv):
                raise ValueError("--backend requires a value")
            backend = argv[i + 1]
            i += 2
        else:
            selectors.append(argv[i])
            i += 1
    return tenant, backend, selectors


def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    try:
        tenant, backend, selectors = _parse_args(argv)
        generate_env(tenant, backend=backend, selectors=selectors)
    except ValueError as exc:
        sys.stderr.write("error: %s\n" % exc)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
