"""Generate Terraform modules from the committed provider schema dumps.

Authoring-side tool: runs here via `python -m engine.gen_module`. Public demo
modules are generated on demand; private overlays may choose whether to commit
their generated module sets. Stdlib-only, Python 3.6-floor syntax — see
AGENTS.md rules 5-7.
"""
import json
import os
import re
import subprocess
import sys
from engine import deployment
from engine import packs
from engine.registry import generated_types
from engine.tfschema import (
    attr_type,
    block_is_single,
    block_has_sensitive,
    classify_attributes,
    hcl_type,
    input_block_types,
    load_resource,
    resource_input_attrs,
)


def _header(resource_type, provider):
    return (
        "# GENERATED by engine.gen_module from packs/%s/schemas/provider/%s.json"
        " — do not edit.\n# Regenerate: python -m engine.gen_module\n\n"
        % (provider, provider)
    )


_PROVIDER_SOURCES = packs.provider_sources()

# The provider pins are owned by pack schema-extract HCL — the same file that
# produces the committed schema dumps. Generated modules MUST carry the version
# that the dumps (and thus variables.tf types) were built from, or a deploy-time
# `terraform init` can resolve a newer provider whose retyped/renamed attributes
# break plan or silently diverge from what was validated. Reading the pins from
# one place keeps a version bump in pack metadata and generated modules aligned.
def _load_provider_pins(path=None):
    """Parse {provider: version} from a required_providers main.tf.

    Matches the `xxx = { source = "...", version = "..." }` blocks in the
    pack's schema-extract HCL so modules pin exactly the versions the schema
    dumps were extracted under. Fails loudly if the file is missing or advertises
    no versioned provider — a silent {} would regenerate modules with no
    constraint, reintroducing the unpinned-deploy bug.
    """
    if path is None:
        path = packs.schema_extract_path()
    if not os.path.exists(path):
        raise ValueError(
            "provider pins not found: %s is missing — generation reads the "
            "pins from there (the file the schema dumps are extracted under). "
            "Restore it or pass an explicit path." % path
        )
    with open(path, encoding="utf-8") as f:
        text = f.read()
    pins = {}
    block_re = re.compile(
        r'(\w+)\s*=\s*\{[^}]*?version\s*=\s*"([^"]+)"', re.DOTALL
    )
    for name, version in block_re.findall(text):
        pins[name] = version
    if not pins:
        raise ValueError(
            "no versioned providers found in %s — every required_providers "
            "entry needs a version line so generated modules can pin it. Add "
            "version = \"x.y.z\" beside each source." % path
        )
    return pins


_PROVIDER_VERSION_CONSTRAINTS = packs.provider_pins()


def _provider_of(resource_type):
    return packs.provider_of(resource_type)


def _block_object_type(block, indent):
    """HCL object({...}) type for a nested block's input shape."""
    cls = classify_attributes(block)
    pad = " " * (indent + 2)
    lines = []
    for name in cls["required"] + cls["optional"]:
        attr_t = hcl_type(attr_type(block["attributes"][name]), indent + 2)
        lines.append("%s%s = optional(%s)" % (pad, name, attr_t))
    for name, bt in input_block_types(block).items():
        lines.append(
            "%s%s = optional(%s)" % (pad, name, _block_input_type(bt, indent + 2, name))
        )
    return "object({\n%s\n%s})" % ("\n".join(lines), " " * indent)


def _block_input_type(block_type, indent, name="<unknown>"):
    inner = _block_object_type(block_type["block"], indent)
    mode = block_type["nesting_mode"]
    if block_is_single(block_type):
        # One instance max (nesting "single" or max_items=1): typed as a
        # bare object; main.tf wraps [x] in the dynamic block's for_each.
        return inner
    if mode in ("list", "set"):
        return "%s(%s)" % (mode, inner)
    raise ValueError("unsupported nesting_mode %r" % mode)


def _render_block_body(block, ref, indent, top_level=False):
    """Body lines for a resource or dynamic-content block.

    ref: expression prefix for reading values (e.g. "each.value" or
    "applications.value"). Computed-only attributes are never assigned; at
    the resource top level the computed `id` (resource identity) is dropped too
    (resource_input_attrs), the same exclusion the schema and typecheck apply.
    """
    pad = " " * indent
    cls = resource_input_attrs(block) if top_level else classify_attributes(block)
    names = cls["required"] + cls["optional"]
    lines = []
    for name in names:
        lines.append("%s%s = %s.%s" % (pad, name, ref, name))
    for name, bt in input_block_types(block).items():
        source = "%s.%s" % (ref, name)
        if block_is_single(bt):
            iterable = "%s == null ? [] : [%s]" % (source, source)
        else:
            iterable = "%s == null ? [] : %s" % (source, source)
        lines.append("")
        lines.append('%sdynamic "%s" {' % (pad, name))
        lines.append("%s  for_each = %s" % (pad, iterable))
        lines.append("%s  content {" % pad)
        lines.extend(_render_block_body(bt["block"], "%s.value" % name, indent + 4))
        lines.append("%s  }" % pad)
        lines.append("%s}" % pad)
    return lines


def render_main(resource_type, resource_schema):
    body = _render_block_body(resource_schema["block"], "each.value", 2,
                             top_level=True)
    return (
        _header(resource_type, _provider_of(resource_type))
        + 'resource "%s" "this" {\n' % resource_type
        + "  for_each = var.items\n\n"
        + "\n".join(body)
        + "\n}\n"
    )


def render_variables(resource_type, resource_schema):
    block = resource_schema["block"]
    cls = resource_input_attrs(block)  # drops the top-level resource-identity id
    lines = []
    for name in cls["required"]:
        lines.append("    %s = %s" % (name, hcl_type(attr_type(block["attributes"][name]))))
    for name in cls["optional"]:
        lines.append(
            "    %s = optional(%s)" % (name, hcl_type(attr_type(block["attributes"][name])))
        )
    for name, bt in input_block_types(block).items():
        lines.append("    %s = optional(%s)" % (name, _block_input_type(bt, 4, name)))
    return (
        _header(resource_type, _provider_of(resource_type))
        + 'variable "items" {\n'
        + '  description = "%s instances, keyed by a stable identifier."\n'
        % resource_type
        + "  type = map(object({\n%s\n  }))\n}\n" % "\n".join(lines)
    )


_SAMPLE_VALUES = {"string": "example", "bool": True, "number": 1}


def render_outputs(resource_type, resource_schema):
    block = resource_schema["block"]
    attrs = block.get("attributes") or {}
    deprecated = sorted(n for n, a in attrs.items() if a.get("deprecated"))
    header = _header(resource_type, _provider_of(resource_type))
    sensitive_line = "  sensitive   = true\n" if block_has_sensitive(block) else ""
    if deprecated:
        # Exposing the whole resource object would READ the deprecated
        # attribute(s) and emit a "Deprecated value used" warning on every
        # plan. Project them out: list only the kept members, so the dying
        # field is never referenced. (e.g. zpa_policy_access_rule.rule_order.)
        kept = [n for n in sorted(attrs) if not attrs[n].get("deprecated")]
        members = kept + sorted((block.get("block_types") or {}).keys())
        projection = "\n".join("      %s = v.%s" % (m, m) for m in members)
        out = (
            header
            + 'output "items" {\n'
            + '  description = "All managed %s resources (excludes deprecated: '
            '%s), keyed as in var.items."\n' % (resource_type, ", ".join(deprecated))
            + sensitive_line
            + "  value = {\n    for k, v in %s.this : k => {\n%s\n    }\n  }\n}\n"
            % (resource_type, projection)
        )
    else:
        out = (
            header
            + 'output "items" {\n'
            + '  description = "All managed %s resources, keyed as in var.items."\n'
            % resource_type
            + sensitive_line
            + "  value = %s.this\n}\n" % resource_type
        )
    if attrs.get("name", {}).get("required") and "id" in attrs:
        out += (
            '\noutput "name_to_id" {\n'
            + '  description = "Map of resource name to provider-assigned id."\n'
            + "  value = { for k, v in %s.this : v.name => v.id }\n}\n" % resource_type
        )
    return out


def render_readme(resource_type, resource_schema):
    return (
        "# %s (generated module)\n\n"
        "Manages `%s` via a typed `items` map. GENERATED — do not edit by\n"
        "hand (AGENTS.md rule 6). Regenerate with `python -m engine.gen_module` "
        "or `make check-modules`.\n"
        % (resource_type, resource_type)
    )


def render_versions(resource_type, resource_schema):
    provider = _provider_of(resource_type)
    source = _PROVIDER_SOURCES[provider]
    version_line = ""
    if provider in _PROVIDER_VERSION_CONSTRAINTS:
        version_line = '      version = "%s"\n' % _PROVIDER_VERSION_CONSTRAINTS[provider]
    return (
        _header(resource_type, provider)
        + "terraform {\n"
        + "  required_providers {\n"
        + '    %s = {\n' % provider
        + '      source = "%s"\n' % source
        + version_line
        + "    }\n"
        + "  }\n"
        + "}\n"
    )


def _sample_value(enc):
    """Return a minimal sample value for a required attribute type encoding."""
    if isinstance(enc, str):
        return _SAMPLE_VALUES.get(enc, "example")
    # complex type: ["set"/"list"/"map"/"object", inner]
    if isinstance(enc, list) and len(enc) == 2:
        kind, inner = enc
        if kind in ("set", "list"):
            return [_sample_value(inner)]
        if kind == "map":
            return {"example": _sample_value(inner)}
        if kind == "object" and isinstance(inner, dict):
            # without this, a required list-of-object attr sampled [[]]
            # and the module smoke test failed with a cryptic type error
            return dict((name, _sample_value(t))
                        for name, t in sorted(inner.items()))
    return []


def _sample_item(block):
    """Minimal VALID item for a block: required attributes plus any required
    (min_items>=1) nested block — a set/list block carries one entry, a
    single block an object. Without the block terraform rejects the sample
    ("Insufficient <name> blocks are required")."""
    cls = classify_attributes(block)
    item = {}
    for name in cls["required"]:
        item[name] = _sample_value(attr_type(block["attributes"][name]))
    for name, bt in input_block_types(block).items():
        if (bt.get("min_items") or 0) >= 1:
            inner = _sample_item(bt["block"])
            item[name] = inner if block_is_single(bt) else [inner]
    return item


def render_sample(resource_type, resource_schema, sample_override=None):
    item = _sample_item(resource_schema["block"])
    if sample_override:
        item.update(sample_override)
    return json.dumps({"items": {"example": item}}, indent=2, sort_keys=True) + "\n"


def render_test(resource_type, resource_schema):
    provider = _provider_of(resource_type)
    return (
        "# GENERATED smoke test — plan against a mocked provider; no credentials.\n"
        'mock_provider "%s" {}\n\n'
        "run \"defaults_plan\" {\n"
        "  command = plan\n\n"
        "  assert {\n"
        "    condition     = length(var.items) == 1\n"
        '    error_message = "sample fixture must contain exactly one item"\n'
        "  }\n"
        "}\n" % provider
    )


MODULES_ROOT = "modules"
EXPECTED_MODULE_FILES = (
    "main.tf",
    "variables.tf",
    "outputs.tf",
    "versions.tf",
    "README.md",
    os.path.join("tests", "defaults.tftest.hcl"),
    os.path.join("tests", "sample.auto.tfvars.json"),
)


def _fmt(text):
    """Pipe rendered HCL through terraform fmt for canonical formatting.

    Generation is authoring-side only (AGENTS.md / README), so requiring
    terraform here is fine; fail loudly rather than committing unformatted
    output that module drift checks would reject.
    """
    proc = subprocess.run(
        ["terraform", "fmt", "-"], input=text.encode(), stdout=subprocess.PIPE, check=True
    )
    return proc.stdout.decode()


def _load_json_override(resource_type, overrides_root):
    """Load packs/<provider>/overrides/<resource_type>.json if it exists."""
    path = os.path.join(overrides_root, resource_type + ".json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def generate_module(resource_type, out_root=None, overrides_root=None, fmt=True):
    if out_root is None:
        out_root = deployment.module_dir()
    if overrides_root is None:
        overrides_root = packs.overrides_dir_for(resource_type)
    rs = load_resource(resource_type)
    base = os.path.join(out_root, resource_type)
    os.makedirs(os.path.join(base, "tests"), exist_ok=True)
    json_override = _load_json_override(resource_type, overrides_root)
    override_main = os.path.join(overrides_root, resource_type, "main.tf")
    if os.path.exists(override_main):
        with open(override_main, encoding="utf-8") as f:
            main_text = f.read()
    else:
        main_text = render_main(resource_type, rs)
    files = {
        "variables.tf": render_variables(resource_type, rs),
        "versions.tf": render_versions(resource_type, rs),
        "main.tf": main_text,
        "outputs.tf": render_outputs(resource_type, rs),
        "README.md": render_readme(resource_type, rs),
        os.path.join("tests", "defaults.tftest.hcl"): render_test(resource_type, rs),
        os.path.join("tests", "sample.auto.tfvars.json"): render_sample(
            resource_type, rs, sample_override=json_override.get("sample")
        ),
    }
    for rel, text in sorted(files.items()):
        if fmt and (rel.endswith(".tf") or rel.endswith(".tftest.hcl")):
            text = _fmt(text)
        with open(os.path.join(base, rel), "w", encoding="utf-8") as f:
            f.write(text)
        sys.stderr.write("wrote %s\n" % os.path.join(base, rel))


def validate_generated_module_tree(module_root, resource_types=None):
    """Fail loudly if any generated resource module is missing contract files."""
    resource_types = list(resource_types or generated_types())
    missing = []
    for resource_type in resource_types:
        base = os.path.join(module_root, resource_type)
        for rel in EXPECTED_MODULE_FILES:
            path = os.path.join(base, rel)
            if not os.path.isfile(path):
                missing.append(os.path.join(resource_type, rel))
    if missing:
        preview = "\n".join("  - %s" % path for path in missing[:20])
        extra = ""
        if len(missing) > 20:
            extra = "\n  ... %d more" % (len(missing) - 20)
        raise ValueError(
            "generated module tree %s is missing %d expected file(s):\n%s%s"
            % (module_root, len(missing), preview, extra)
        )
    return resource_types


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv:
        if len(argv) == 2 and argv[0] == "--check-output":
            validate_generated_module_tree(argv[1])
            sys.stderr.write("validated generated module tree %s\n" % argv[1])
            return 0
        sys.stderr.write(
            "usage: python -m engine.gen_module [--check-output <module_dir>]\n"
        )
        return 2
    for resource_type in generated_types():
        generate_module(resource_type)
    return 0


if __name__ == "__main__":
    sys.exit(main())
