"""Deterministic HCL .auto.tfvars rendering helpers.

JSON remains the default tfvars format. This module only provides the opt-in
HCL renderer and, in later phases, comment derivation for callers that select
HCL explicitly.

Determinism is part of the contract: rendered bytes and generated comments
must be derived solely from input data. Do not include timestamps, host data,
run identifiers, environment details, or any other generation-run metadata.

Terraform fmt calibration: fmt aligns equals signs only within contiguous
single-line object assignments; non-empty list/object assignments are not
padded and split alignment runs. Trailing comments are separated by one or
more spaces so the # markers align within a scalar run or list.
"""
import os
import re

from engine import lookup
from engine import packs

# engine.transform is imported lazily at the use sites: Phase B makes
# transform call this module, and a module-level circular import between the
# two can fail on the Python 3.6 floor.


HEADER = "# Generated by infrawright. Do not edit; regenerate via make transform/adopt."

_BARE_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def render_tfvars_hcl(items, comments=None):
    """Render projected items as fmt-canonical HCL tfvars text."""
    comments = comments or {}
    _validate_comments(comments)
    if not items:
        return HEADER + "\nitems = {}\n"

    lines = [HEADER, "items = {"]
    _append_object_body(
        lines, items, 2, comments=comments, quote_all_keys=True,
        top_level_items=True)
    lines.append("}")
    return "\n".join(lines) + "\n"


def derive_comments(resource_type, items, tenant, config_root=None):
    """Derive deterministic display-name comments from pack references."""
    refs = packs.references().get(resource_type)
    if not refs:
        return {}

    comments = {}
    lookups = {}
    missing = set()

    for item_key in sorted(items):
        item = items[item_key]
        if not isinstance(item, dict):
            continue
        for field in sorted(refs):
            if field not in item:
                continue
            value = item[field]
            if value is None:
                continue
            mapping = _lookup_for_referent(
                tenant, refs[field]["referent"], lookups, missing,
                config_root=config_root)
            if mapping is None:
                continue
            _derive_field_comments(comments, item_key, field, value, mapping)
    return comments


def _lookup_for_referent(tenant, referent, lookups, missing, config_root=None):
    if referent in lookups:
        return lookups[referent]
    if referent in missing:
        return None
    if not os.path.exists(
            lookup.lookup_path(tenant, referent, config_root=config_root)):
        missing.add(referent)
        return None
    lookups[referent] = lookup.load_lookup(
        tenant, referent, config_root=config_root)
    return lookups[referent]


def _derive_field_comments(comments, item_key, field, value, mapping):
    if isinstance(value, list):
        for index, element in enumerate(value):
            if element is None:
                continue
            comments[(item_key, field, index)] = _comment_display(
                lookup.resolve_display(element, mapping))
        return
    comments[(item_key, field)] = _comment_display(
        lookup.resolve_display(value, mapping))


def _comment_display(display):
    return display.replace("\n", " ").replace("\r", " ")


def _validate_comments(comments):
    for text in comments.values():
        _check_comment_text(text)


def _check_comment_text(text):
    if "\n" in text or "\r" in text:
        raise ValueError("HCL tfvars comments must be single-line")


def _comment_text(comments, key):
    if key not in comments:
        return None
    text = comments[key]
    _check_comment_text(text)
    return text


def _quoted_key(key):
    from engine.transform import hcl_string_literal

    return hcl_string_literal(str(key))


def _attribute_key(key):
    text = str(key)
    if _BARE_KEY_RE.match(text):
        return text
    return _quoted_key(text)


def _key_width(keys):
    width = 0
    for key in keys:
        width = max(width, len(key))
    return width


def _padding(token, width):
    return " " * (width - len(token))


def _append_object_body(lines, mapping, indent, comments=None, item_key=None,
                        quote_all_keys=False, top_level_items=False):
    keys = sorted(mapping)
    rendered_keys = {}
    for key in keys:
        rendered_keys[key] = _quoted_key(key) if quote_all_keys else _attribute_key(key)
    group = []
    for key in keys:
        token = rendered_keys[key]
        value = mapping[key]
        if _is_multiline_value(value):
            _append_singleline_group(lines, group, indent, comments, item_key)
            group = []
            prefix = (" " * indent) + token + " = "
            if top_level_items:
                next_item_key = key
            elif isinstance(value, list):
                next_item_key = item_key
            else:
                next_item_key = None
            _append_multiline_assignment(
                lines, prefix, value, indent, comments=comments,
                item_key=next_item_key, field=key)
        else:
            group.append((key, token, value))
    _append_singleline_group(lines, group, indent, comments, item_key)


def _append_singleline_group(lines, group, indent, comments, item_key):
    if not group:
        return
    width = _key_width([token for _key, token, _value in group])
    entries = []
    comment_width = 0
    for key, token, value in group:
        prefix = (
            (" " * indent) + token + _padding(token, width) + " = "
        )
        base = prefix + _singleline_literal(value)
        comment = _field_comment(comments, item_key, key)
        if comment is not None:
            comment_width = max(comment_width, len(base))
        entries.append((base, comment))
    for base, comment in entries:
        if comment is not None:
            base += (" " * (comment_width - len(base) + 1)) + "# " + comment
        lines.append(base)


def _append_multiline_assignment(lines, prefix, value, indent, comments=None,
                                 item_key=None, field=None):
    if isinstance(value, dict):
        lines.append(prefix + "{")
        _append_object_body(
            lines, value, indent + 2, comments=comments, item_key=item_key)
        lines.append((" " * indent) + "}")
        return

    _append_list_assignment(lines, prefix, value, indent, comments, item_key,
                            field)


def _append_list_assignment(lines, prefix, values, indent, comments, item_key,
                            field):
    if not values:
        lines.append(prefix + "[]")
        return

    lines.append(prefix + "[")
    element_indent = indent + 2
    comments_by_index = []
    comment_width = 0
    for index, value in enumerate(values):
        comment = _list_comment(comments, item_key, field, index)
        comments_by_index.append(comment)
        if comment is not None and not _is_multiline_value(value):
            base = (
                (" " * element_indent) + _singleline_literal(value) + ","
            )
            comment_width = max(comment_width, len(base))
    for index, value in enumerate(values):
        _append_list_element(
            lines, value, element_indent, comments_by_index[index],
            comment_width)
    lines.append((" " * indent) + "]")


def _append_list_element(lines, value, indent, comment, comment_width=0):
    prefix = " " * indent
    if not _is_multiline_value(value):
        base = prefix + _singleline_literal(value) + ","
        if comment is not None:
            base += (" " * (comment_width - len(base) + 1)) + "# " + comment
        lines.append(base)
        return

    suffix = _comment_suffix(comment)
    if isinstance(value, dict):
        lines.append(prefix + "{")
        _append_object_body(lines, value, indent + 2)
        lines.append(prefix + "}" + suffix)
        return

    lines.append(prefix + "[")
    for nested in value:
        _append_list_element(lines, nested, indent + 2, None)
    lines.append(prefix + "]" + suffix)


def _comment_suffix(comment):
    if comment is None:
        return ","
    return ", # " + comment


def _field_comment(comments, item_key, field):
    if comments is None or item_key is None or field is None:
        return None
    return _comment_text(comments, (item_key, field))


def _list_comment(comments, item_key, field, index):
    if comments is None or item_key is None or field is None:
        return None
    return _comment_text(comments, (item_key, field, index))


def _scalar_literal(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        from engine.transform import hcl_string_literal

        return hcl_string_literal(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value != value or value in (float("inf"), float("-inf")):
            raise ValueError(
                "non-finite float %r cannot render as HCL" % value
            )
        return repr(value)
    raise TypeError("unsupported HCL tfvars value: %s" % type(value).__name__)


def _singleline_literal(value):
    if isinstance(value, dict):
        if not value:
            return "{}"
    elif isinstance(value, list):
        if not value:
            return "[]"
    else:
        return _scalar_literal(value)
    raise TypeError("expected single-line HCL tfvars value")


def _is_multiline_value(value):
    return (
        (isinstance(value, dict) and bool(value)) or
        (isinstance(value, list) and bool(value))
    )
