package tfrender

// hcl_tfvars.go ports node-src/domain/hcl-tfvars.ts: the byte-exact HCL
// tfvars renderer (`engine.hcl_tfvars.render_tfvars_hcl`'s Node-side
// counterpart). Vectors: node-tests/hcl-tfvars.test.ts, ported in full in
// hcl_tfvars_test.go (every test in that file is a pure library test; there
// is no CLI/runner-level test to skip).
//
// Value model: items/comments values are go/internal/canonjson.Value
// (nil / bool / string / json.Number / float64 / []any / map[string]any),
// exactly mirroring the TS source's `unknown`-typed walk. json.Number plays
// the role of the TS source's lossless-json LosslessNumber (an exact
// source-text numeric lexeme); float64 plays the role of a plain JS
// `number` literal constructed directly in Go rather than decoded from
// JSON text.
//
// Code-point vs UTF-16 alignment (see this port's task brief): the Node
// source's `pythonLength` helper is `Array.from(value).length`, which
// iterates a JS string by Unicode CODE POINT (Array.from on a string uses
// the string iterator protocol, which yields one entry per code point,
// combining surrogate pairs) -- not by UTF-16 code unit (`value.length`
// would count each surrogate-pair half separately). This is confirmed both
// by reading Array.from's iterator-protocol semantics and by
// node-tests/hcl-tfvars.test.ts's own "code-point lengths, not UTF-16
// lengths, control comment alignment" test, which asserts a single emoji
// (😀, one code point, two UTF-16 units) occupies one column of alignment.
// utf8.RuneCountInString is this port's direct equivalent: Go runes are
// Unicode code points, so counting runes in a (necessarily well-formed)
// UTF-8 Go string counts exactly the same units Array.from counts, with no
// surrogate-pair math required on either side.
import (
	"encoding/json"
	"fmt"
	"math"
	"regexp"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/dvmrry/infrawright-dev/go/internal/canonjson"
)

// HCLTfvarsHeader is the fixed HCL tfvars file header. Ports
// HCL_TFVARS_HEADER from node-src/domain/hcl-tfvars.ts.
const HCLTfvarsHeader = "# Generated by infrawright. Do not edit; regenerate via make transform/adopt."

// bareHCLIdentifier ports the BARE_KEY regexp from
// node-src/domain/hcl-tfvars.ts, reused for both attribute keys and the
// tfvars variable name (varName in RenderTfvarsHcl).
var bareHCLIdentifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// HclTfvarsComments is the Go analogue of the HclTfvarsComments type in
// node-src/domain/hcl-tfvars.ts: a flat map from HclTfvarsCommentKey-shaped
// keys to single-line comment text.
type HclTfvarsComments map[string]string

// hclTfvarsError is this file's local "throw new TypeError(...)" analogue:
// every failure path in the ported TS source throws a plain TypeError (not
// a procerr.ProcessFailure), so this file mirrors that with a plain error
// carrying the same message text, using panic/recover internally the same
// way go/internal/metadata's fail/MetadataError pattern does, so the many
// small recursive rendering helpers below can abandon a render from
// arbitrary depth without threading an error return through every call.
type hclTfvarsError struct{ message string }

func (e *hclTfvarsError) Error() string { return e.message }

func failHclTfvars(format string, args ...any) {
	panic(&hclTfvarsError{message: fmt.Sprintf(format, args...)})
}

// HclTfvarsCommentKey builds the internal lookup key HclTfvarsComments uses
// to associate a comment with one field (and, for list elements, one
// index) of one top-level item. Ports hclTfvarsCommentKey from
// node-src/domain/hcl-tfvars.ts.
//
// The TS source builds this key via `JSON.stringify([itemKey, field,
// index])`. That exact byte encoding is never observed outside this
// package -- HclTfvarsComments is always produced and consumed in-memory
// within one process (see deriveHclComments in transform_artifacts.go),
// never serialized to disk or compared against a fixed golden string by
// any ported test -- so this port is free to use any injective, stable
// encoding rather than reproducing JSON.stringify's exact escaping rules.
// strconv.Quote gives an unambiguous, collision-free encoding for the two
// string fields; index is rendered as a decimal literal or the literal
// "null", matching the TS source's third array element being either a
// number or null.
func HclTfvarsCommentKey(itemKey, field string, index *int) string {
	indexToken := "null"
	if index != nil {
		indexToken = strconv.Itoa(*index)
	}
	return "[" + strconv.Quote(itemKey) + "," + strconv.Quote(field) + "," + indexToken + "]"
}

// commentMap validates and copies comments into the map/lookup shape the
// rendering helpers below use. Ports the commentMap function from
// node-src/domain/hcl-tfvars.ts, minus its `typeof text !== "string"`
// check: HclTfvarsComments's Go type (map[string]string) already
// guarantees every value is a string, so that runtime check has no Go
// analogue to perform.
func commentMap(comments HclTfvarsComments) map[string]string {
	output := make(map[string]string, len(comments))
	for key, text := range comments {
		if strings.ContainsAny(text, "\n\r") {
			failHclTfvars("HCL tfvars comments must be single-line")
		}
		output[key] = text
	}
	return output
}

func quotedKey(key string) string {
	rendered, err := RenderHclQuotedString(key)
	if err != nil {
		// RenderHclQuotedString only fails for a NUL byte, which cannot
		// occur here: bareHCLIdentifier/attribute keys and the item keys
		// this package renders always originate from validated JSON text
		// (canonjson.Decode rejects raw NUL bytes inside strings via the
		// standard library's JSON string grammar) or from literal Go
		// source in this port's own tests.
		failHclTfvars("%s", err.Error())
	}
	return rendered
}

func attributeKey(key string) string {
	if bareHCLIdentifier.MatchString(key) {
		return key
	}
	return quotedKey(key)
}

// pythonLength counts value's Unicode code points, matching the Node
// source's `Array.from(value).length` -- see this file's package-level doc
// comment for why counting Go runes is the exact Go equivalent.
func pythonLength(value string) int {
	return utf8.RuneCountInString(value)
}

func isMultilineArray(value any) ([]any, bool) {
	arr, ok := value.([]any)
	return arr, ok && len(arr) > 0
}

func isMultilineRecord(value any) (map[string]any, bool) {
	rec, ok := value.(map[string]any)
	return rec, ok && len(rec) > 0
}

// isMultilineValue reports whether value renders across multiple lines (a
// non-empty array or object). Ports isMultilineValue from
// node-src/domain/hcl-tfvars.ts.
func isMultilineValue(value any) bool {
	if _, ok := isMultilineArray(value); ok {
		return true
	}
	_, ok := isMultilineRecord(value)
	return ok
}

// jsNumberString renders the three non-finite float64 values (NaN, +Inf,
// -Inf) the way JavaScript's String(value) does, for the "non-finite
// float ... cannot render as HCL" error message scalarLiteral raises for
// them. Only used on that failure path; message text is otherwise
// unobserved by any ported test (which matches by /non-finite/ only).
func jsNumberString(value float64) string {
	switch {
	case math.IsNaN(value):
		return "NaN"
	case math.IsInf(value, 1):
		return "Infinity"
	default:
		return "-Infinity"
	}
}

const maxSafeInteger = 1<<53 - 1

func isSafeInteger(value float64) bool {
	return value == float64(int64(value)) && value >= -maxSafeInteger && value <= maxSafeInteger
}

// scalarLiteral renders one HCL scalar literal. Ports scalarLiteral from
// node-src/domain/hcl-tfvars.ts.
func scalarLiteral(value any) string {
	switch v := value.(type) {
	case nil:
		return "null"
	case bool:
		if v {
			return "true"
		}
		return "false"
	case string:
		return quotedKey(v)
	case json.Number:
		// The LosslessNumber branch: canonicalize the exact source lexeme
		// through Python's numeric model, matching
		// canonicalPythonNumberToken(value.toString()) in the TS source.
		token, err := canonjson.CanonicalNumberToken(string(v))
		if err != nil {
			failHclTfvars("non-finite number cannot render as HCL")
		}
		return token
	case float64:
		// The plain `number` branch.
		if math.IsNaN(v) || math.IsInf(v, 0) {
			failHclTfvars("non-finite float %s cannot render as HCL", jsNumberString(v))
		}
		if v == 0 && math.Signbit(v) {
			return "-0.0"
		}
		if v == math.Trunc(v) {
			if !isSafeInteger(v) {
				failHclTfvars("unsafe native integer cannot render losslessly as HCL")
			}
			return strconv.FormatInt(int64(v), 10)
		}
		token, err := canonjson.FiniteFloatToken(v)
		if err != nil {
			failHclTfvars("non-finite number cannot render as HCL")
		}
		return token
	default:
		failHclTfvars("unsupported HCL tfvars value: %T", value)
		return ""
	}
}

// singlelineLiteral renders a value known to fit on one line: an empty
// array/object, or any scalar. Ports singlelineLiteral from
// node-src/domain/hcl-tfvars.ts.
func singlelineLiteral(value any) string {
	if arr, ok := value.([]any); ok {
		if len(arr) == 0 {
			return "[]"
		}
		failHclTfvars("expected single-line HCL tfvars value")
	}
	if rec, ok := value.(map[string]any); ok {
		if len(rec) == 0 {
			return "{}"
		}
		failHclTfvars("expected single-line HCL tfvars value")
	}
	return scalarLiteral(value)
}

func fieldComment(comments map[string]string, itemKey *string, field string) *string {
	if itemKey == nil {
		return nil
	}
	if text, ok := comments[HclTfvarsCommentKey(*itemKey, field, nil)]; ok {
		return &text
	}
	return nil
}

func listComment(comments map[string]string, itemKey, field *string, index int) *string {
	if itemKey == nil || field == nil {
		return nil
	}
	idx := index
	if text, ok := comments[HclTfvarsCommentKey(*itemKey, *field, &idx)]; ok {
		return &text
	}
	return nil
}

type singlelineGroupEntry struct {
	key   string
	token string
	value any
}

// appendSinglelineGroup ports appendSinglelineGroup from
// node-src/domain/hcl-tfvars.ts.
func appendSinglelineGroup(
	lines *[]string,
	group []singlelineGroupEntry,
	indent int,
	comments map[string]string,
	itemKey *string,
) {
	if len(group) == 0 {
		return
	}
	width := 0
	for _, entry := range group {
		if n := pythonLength(entry.token); n > width {
			width = n
		}
	}
	type renderedEntry struct {
		base    string
		comment *string
	}
	entries := make([]renderedEntry, len(group))
	for i, entry := range group {
		prefix := strings.Repeat(" ", indent) + entry.token + strings.Repeat(" ", width-pythonLength(entry.token)) + " = "
		entries[i] = renderedEntry{
			base:    prefix + singlelineLiteral(entry.value),
			comment: fieldComment(comments, itemKey, entry.key),
		}
	}
	commentWidth := 0
	for _, entry := range entries {
		if entry.comment != nil {
			if n := pythonLength(entry.base); n > commentWidth {
				commentWidth = n
			}
		}
	}
	for _, entry := range entries {
		if entry.comment == nil {
			*lines = append(*lines, entry.base)
		} else {
			*lines = append(*lines, entry.base+strings.Repeat(" ", commentWidth-pythonLength(entry.base)+1)+"# "+*entry.comment)
		}
	}
}

// appendListElement ports appendListElement from
// node-src/domain/hcl-tfvars.ts.
func appendListElement(lines *[]string, value any, indent int, comment *string, commentWidth int) {
	prefix := strings.Repeat(" ", indent)
	if !isMultilineValue(value) {
		base := prefix + singlelineLiteral(value) + ","
		if comment == nil {
			*lines = append(*lines, base)
		} else {
			*lines = append(*lines, base+strings.Repeat(" ", commentWidth-pythonLength(base)+1)+"# "+*comment)
		}
		return
	}
	suffix := ","
	if comment != nil {
		suffix = ", # " + *comment
	}
	if rec, ok := isMultilineRecord(value); ok {
		*lines = append(*lines, prefix+"{")
		appendObjectBody(lines, rec, indent+2, map[string]string{}, nil, false, false)
		*lines = append(*lines, prefix+"}"+suffix)
		return
	}
	arr, ok := isMultilineArray(value)
	if !ok {
		failHclTfvars("expected HCL list value")
	}
	*lines = append(*lines, prefix+"[")
	for _, nested := range arr {
		appendListElement(lines, nested, indent+2, nil, 0)
	}
	*lines = append(*lines, prefix+"]"+suffix)
}

// appendListAssignment ports appendListAssignment from
// node-src/domain/hcl-tfvars.ts.
func appendListAssignment(
	lines *[]string,
	prefix string,
	values []any,
	indent int,
	comments map[string]string,
	itemKey, field *string,
) {
	if len(values) == 0 {
		*lines = append(*lines, prefix+"[]")
		return
	}
	*lines = append(*lines, prefix+"[")
	elementIndent := indent + 2
	type listEntry struct {
		value   any
		comment *string
	}
	entries := make([]listEntry, len(values))
	for i, value := range values {
		entries[i] = listEntry{value: value, comment: listComment(comments, itemKey, field, i)}
	}
	commentWidth := 0
	for _, entry := range entries {
		if entry.comment != nil && !isMultilineValue(entry.value) {
			candidate := strings.Repeat(" ", elementIndent) + singlelineLiteral(entry.value) + ","
			if n := pythonLength(candidate); n > commentWidth {
				commentWidth = n
			}
		}
	}
	for _, entry := range entries {
		appendListElement(lines, entry.value, elementIndent, entry.comment, commentWidth)
	}
	*lines = append(*lines, strings.Repeat(" ", indent)+"]")
}

// appendMultilineAssignment ports appendMultilineAssignment from
// node-src/domain/hcl-tfvars.ts.
func appendMultilineAssignment(
	lines *[]string,
	prefix string,
	value any,
	indent int,
	comments map[string]string,
	itemKey *string,
	field string,
) {
	if rec, ok := isMultilineRecord(value); ok {
		*lines = append(*lines, prefix+"{")
		appendObjectBody(lines, rec, indent+2, comments, itemKey, false, false)
		*lines = append(*lines, strings.Repeat(" ", indent)+"}")
		return
	}
	arr, ok := value.([]any)
	if !ok {
		failHclTfvars("expected multiline HCL value")
	}
	appendListAssignment(lines, prefix, arr, indent, comments, itemKey, &field)
}

// appendObjectBody ports appendObjectBody from
// node-src/domain/hcl-tfvars.ts.
func appendObjectBody(
	lines *[]string,
	mapping map[string]any,
	indent int,
	comments map[string]string,
	itemKey *string,
	quoteAllKeys bool,
	topLevelItems bool,
) {
	keys := make([]string, 0, len(mapping))
	for key := range mapping {
		keys = append(keys, key)
	}
	keys = canonjson.SortedStrings(keys)

	var group []singlelineGroupEntry
	for _, key := range keys {
		token := key
		if quoteAllKeys {
			token = quotedKey(key)
		} else {
			token = attributeKey(key)
		}
		value := mapping[key]
		if isMultilineValue(value) {
			appendSinglelineGroup(lines, group, indent, comments, itemKey)
			group = nil
			var nextItemKey *string
			if topLevelItems {
				k := key
				nextItemKey = &k
			} else if _, isArr := value.([]any); isArr {
				nextItemKey = itemKey
			}
			appendMultilineAssignment(
				lines,
				strings.Repeat(" ", indent)+token+" = ",
				value,
				indent,
				comments,
				nextItemKey,
				key,
			)
		} else {
			group = append(group, singlelineGroupEntry{key: key, token: token, value: value})
		}
	}
	appendSinglelineGroup(lines, group, indent, comments, itemKey)
}

// RenderTfvarsHcl matches engine.hcl_tfvars.render_tfvars_hcl byte-for-byte.
// Ports renderTfvarsHcl from node-src/domain/hcl-tfvars.ts.
func RenderTfvarsHcl(items map[string]any, comments HclTfvarsComments, varName string) (rendered string, err error) {
	defer func() {
		if r := recover(); r != nil {
			if e, ok := r.(*hclTfvarsError); ok {
				rendered, err = "", e
				return
			}
			panic(r)
		}
	}()
	if !bareHCLIdentifier.MatchString(varName) {
		failHclTfvars("tfvars variable name must be a bare HCL identifier")
	}
	indexedComments := commentMap(comments)
	if len(items) == 0 {
		return HCLTfvarsHeader + "\n" + varName + " = {}\n", nil
	}
	lines := []string{HCLTfvarsHeader, varName + " = {"}
	appendObjectBody(&lines, items, 2, indexedComments, nil, true, true)
	lines = append(lines, "}")
	return strings.Join(lines, "\n") + "\n", nil
}
