"""Tests for engine.gen_env."""
import io
import json
import os
import re
import sys
import tempfile
import unittest

from engine import deployment
from engine import transform
from engine.gen_env import (
    expand_resources,
    render_env_expression_bindings,
    render_env_main,
    render_env_root_test,
    render_env_test,
)


class RenderEnvMainTest(unittest.TestCase):
    def _root_env_dir(self, resource_type, tenant):
        return os.path.join(
            "envs",
            tenant,
            resource_type,
        )

    def _grouped_deployment(self, groups):
        td = tempfile.mkdtemp(prefix="genenv-roots-")
        dep = os.path.join(td, "deployment.json")
        with open(dep, "w", encoding="utf-8") as f:
            json.dump({"roots": {"zpa": {"groups": groups}}}, f)
        saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
        os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep

        def cleanup():
            if saved is None:
                os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
            else:
                os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved
            __import__("shutil").rmtree(td, ignore_errors=True)

        self.addCleanup(cleanup)

    def test_singleton_explicit_group_smoke_test_uses_namespaced_var(self):
        from engine.gen_env import render_env_root_test

        self._grouped_deployment({"zpa_solo": ["zpa_segment_group"]})
        out = render_env_root_test(
            "zpa_solo",
            ["zpa_segment_group"],
            "tenant",
            has_config_by_type={"zpa_segment_group": True},
        )
        self.assertIn("    zpa_segment_group_items = {}\n", out)
        self.assertIn(
            ")).zpa_segment_group_items\n", out)
        self.assertNotIn("\n    items = {}", out)

    def test_ungrouped_root_matches_legacy_golden(self):
        out = render_env_main(
            "zpa_segment_group",
            ["zpa_segment_group"],
            "zs2",
            self._root_env_dir("zpa_segment_group", "zs2"),
        )
        self.assertEqual(out, (
            "# GENERATED by engine.gen_env for tenant 'zs2' — do not edit.\n"
            "# Regenerate: make gen-env TENANT=zs2\n\n"
            "terraform {\n"
            "  required_version = \">= 1.5\"\n"
            "  required_providers {\n"
            "    zpa = {\n"
            "      source = \"zscaler/zpa\"\n"
            "    }\n"
            "  }\n"
            "  # local state — opt into remote state with\n"
            "  # make gen-env TENANT=zs2 BACKEND=azurerm\n"
            "}\n\n"
            "provider \"zpa\" {\n"
            "  # credentials via provider environment variables\n"
            "}\n\n"
            "variable \"items\" {\n"
            "  # opaque at the root; the module enforces the strict type.\n"
            "  type = any\n"
            "}\n\n"
            "module \"zpa_segment_group\" {\n"
            "  source = \"../../../modules/zpa_segment_group\"\n"
            "  items = var.items\n"
            "}\n"
        ))

    def test_grouped_two_member_root_golden(self):
        self._grouped_deployment({
            "zpa_custom": ["zpa_server_group", "zpa_segment_group"],
        })

        out = render_env_main(
            "zpa_custom",
            ["zpa_server_group", "zpa_segment_group"],
            "zs2",
            self._root_env_dir("zpa_custom", "zs2"),
        )

        self.assertEqual(out, (
            "# GENERATED by engine.gen_env for tenant 'zs2' — do not edit.\n"
            "# Regenerate: make gen-env TENANT=zs2\n\n"
            "terraform {\n"
            "  required_version = \">= 1.5\"\n"
            "  required_providers {\n"
            "    zpa = {\n"
            "      source = \"zscaler/zpa\"\n"
            "    }\n"
            "  }\n"
            "  # local state — opt into remote state with\n"
            "  # make gen-env TENANT=zs2 BACKEND=azurerm\n"
            "}\n\n"
            "provider \"zpa\" {\n"
            "  # credentials via provider environment variables\n"
            "}\n\n"
            "variable \"zpa_segment_group_items\" {\n"
            "  # opaque at the root; the module enforces the strict type.\n"
            "  type = any\n"
            "}\n\n"
            "module \"zpa_segment_group\" {\n"
            "  source = \"../../../modules/zpa_segment_group\"\n"
            "  items = var.zpa_segment_group_items\n"
            "}\n\n"
            "variable \"zpa_server_group_items\" {\n"
            "  # opaque at the root; the module enforces the strict type.\n"
            "  type = any\n"
            "}\n\n"
            "module \"zpa_server_group\" {\n"
            "  source = \"../../../modules/zpa_server_group\"\n"
            "  items = var.zpa_server_group_items\n"
            "}\n"
        ))

    def test_zpa_segment_group_root(self):
        out = render_env_main(
            "zpa_segment_group",
            ["zpa_segment_group"],
            "zs2",
            self._root_env_dir("zpa_segment_group", "zs2"))
        self.assertIn("# GENERATED", out)
        self.assertIn('source = "../../../modules/zpa_segment_group"', out)
        self.assertIn("items = var.items", out)
        self.assertIn('variable "items"', out)
        self.assertIn("type = any", out)
        self.assertIn("zscaler/zpa", out)

    def test_expression_bindings_root_uses_merged_local_items(self):
        out = render_env_main(
            "zpa_application_segment",
            ["zpa_application_segment"],
            "zs2",
            self._root_env_dir("zpa_application_segment", "zs2"),
            expression_binding_types=["zpa_application_segment"],
        )

        self.assertIn(
            "items = local.infrawright_expression_bound_items",
            out,
        )
        self.assertNotIn("items = var.items", out)

    def test_module_source_uses_deployment_module_dir(self):
        with tempfile.TemporaryDirectory() as td:
            dep = os.path.join(td, "deployment.json")
            with open(dep, "w", encoding="utf-8") as f:
                f.write(json.dumps({"module_dir": "private/modules/zia-v4.3.0"}))
            saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
            os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep
            try:
                out = render_env_main(
                    "zia_url_categories",
                    ["zia_url_categories"],
                    "tenant-a",
                    os.path.join("private", "envs", "tenant-a", "zia_url_categories"),
                )
            finally:
                if saved is None:
                    os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
                else:
                    os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved
            self.assertIn(
                'source = "../../../modules/zia-v4.3.0/zia_url_categories"',
                out,
            )

    def test_zia_provider(self):
        out = render_env_main(
            "zia_url_categories",
            ["zia_url_categories"],
            "zs2",
            self._root_env_dir("zia_url_categories", "zs2"))
        self.assertIn("zscaler/zia", out)
        self.assertNotIn("zscaler/zpa", out)

    def test_label_is_opaque_string_only(self):
        # any label works; never parsed
        for label in ("zs2", "zscalertwo", "dev", "gov-beta_1"):
            out = render_env_main(
                "zpa_segment_group",
                ["zpa_segment_group"],
                label,
                self._root_env_dir("zpa_segment_group", label))
            self.assertIn(label, out)

    def test_no_backend_block_by_default(self):
        out = render_env_main(
            "zpa_segment_group",
            ["zpa_segment_group"],
            "zs2",
            self._root_env_dir("zpa_segment_group", "zs2"))
        self.assertNotIn('backend "', out)

    def test_backend_block_is_partial_with_derived_key_hint(self):
        # backend=azurerm emits an EMPTY (partial) backend block — values
        # come from -backend-config at init; the per-root state key is
        # documented inline so the operator can see the blob layout.
        out = render_env_main(
            "zpa_segment_group",
            ["zpa_segment_group"],
            "zs2",
            self._root_env_dir("zpa_segment_group", "zs2"),
            backend="azurerm")
        self.assertIn('backend "azurerm" {', out)
        self.assertIn("zs2/zpa_segment_group.tfstate", out)
        # partial: no storage values baked into the public template
        self.assertNotIn("storage_account_name", out)

    def test_grouped_backend_key_uses_root_label(self):
        self._grouped_deployment({
            "zpa_custom": ["zpa_server_group", "zpa_segment_group"],
        })

        out = render_env_main(
            "zpa_custom",
            ["zpa_server_group", "zpa_segment_group"],
            "zs2",
            self._root_env_dir("zpa_custom", "zs2"),
            backend="azurerm",
        )

        self.assertIn("zs2/zpa_custom.tfstate", out)

    def test_grouped_module_addresses_match_import_addresses(self):
        self._grouped_deployment({
            "zpa_custom": ["zpa_server_group", "zpa_segment_group"],
        })

        out = render_env_main(
            "zpa_custom",
            ["zpa_server_group", "zpa_segment_group"],
            "zs2",
            self._root_env_dir("zpa_custom", "zs2"),
        )
        imports = transform.render_imports(
            "zpa_segment_group",
            {"example": {"id": "123"}},
            {"import_id": "{id}"},
        )

        self.assertIn('module "zpa_segment_group"', out)
        self.assertIn(
            'to = module.zpa_segment_group.zpa_segment_group.this["example"]',
            imports,
        )

    def test_grouped_config_plan_references_per_member_config_files(self):
        self._grouped_deployment({
            "zpa_custom": ["zpa_server_group", "zpa_segment_group"],
        })

        out = render_env_root_test(
            "zpa_custom",
            ["zpa_server_group", "zpa_segment_group"],
            "zs2",
            env_dir=self._root_env_dir("zpa_custom", "zs2"),
            has_config_by_type={
                "zpa_segment_group": True,
                "zpa_server_group": True,
            },
        )

        self.assertIn(
            'zpa_segment_group_items = '
            'jsondecode(file("../../../config/zs2/'
            'zpa_segment_group.auto.tfvars.json")).zpa_segment_group_items',
            out,
        )
        self.assertIn(
            'zpa_server_group_items = '
            'jsondecode(file("../../../config/zs2/'
            'zpa_server_group.auto.tfvars.json")).zpa_server_group_items',
            out,
        )


class GenerateEnvTest(unittest.TestCase):
    def test_writes_root_files(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            generate_env("zs2", out_root=td, fmt=False)
            base = os.path.join(td, "zs2", "zpa_segment_group")
            self.assertTrue(os.path.exists(os.path.join(base, "main.tf")))
            self.assertTrue(os.path.exists(os.path.join(base, "README.md")))

    def test_invalid_tenant_rejected_before_writing_env_root(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            with self.assertRaises(ValueError):
                generate_env(
                    "../x", out_root=td, fmt=False,
                    selectors=["zia_rule_labels"])
            self.assertEqual(os.listdir(td), [])

    def test_tenant_with_separator_rejected_before_writing_env_root(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            with self.assertRaises(ValueError):
                generate_env(
                    "bad/tenant", out_root=td, fmt=False,
                    selectors=["zia_rule_labels"])
            self.assertEqual(os.listdir(td), [])

    def test_invalid_selector_rejected_before_writing_env_root(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            with self.assertRaises(ValueError):
                generate_env(
                    "tenant", out_root=td, fmt=False,
                    selectors=["../zia_rule_labels"])
            self.assertEqual(os.listdir(td), [])

    def test_main_rejects_invalid_tenant_before_writing_env_root(self):
        from engine.gen_env import main
        with tempfile.TemporaryDirectory() as td:
            dep = os.path.join(td, "deployment.json")
            with open(dep, "w", encoding="utf-8") as f:
                f.write(json.dumps({"overlay": td}))
            saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
            os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep
            old_err = sys.stderr
            sys.stderr = io.StringIO()
            try:
                self.assertEqual(main(["../../etc", "zia_rule_labels"]), 2)
                self.assertIn("TENANT must match", sys.stderr.getvalue())
                self.assertFalse(os.path.exists(os.path.join(td, "envs")))
            finally:
                sys.stderr = old_err
                if saved is None:
                    os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
                else:
                    os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved

    def test_scoped_generation_writes_only_selected_root(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            generate_env(
                "zs2", out_root=td, fmt=False,
                selectors=["zia_url_categories"])
            self.assertTrue(os.path.exists(os.path.join(
                td, "zs2", "zia_url_categories", "main.tf"
            )))
            self.assertFalse(os.path.exists(os.path.join(
                td, "zs2", "zpa_segment_group", "main.tf"
            )))

    def test_grouped_generation_writes_shared_root_for_member_selector(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            dep = os.path.join(td, "deployment.json")
            with open(dep, "w", encoding="utf-8") as f:
                f.write(json.dumps({
                    "roots": {
                        "zpa": {
                            "groups": {
                                "zpa_custom": [
                                    "zpa_segment_group",
                                    "zpa_server_group",
                                ],
                            },
                        },
                    },
                }))
            saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
            os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep
            try:
                generate_env(
                    "zs2", out_root=td, fmt=False,
                    selectors=["zpa_segment_group"])
                grouped = os.path.join(td, "zs2", "zpa_custom", "main.tf")
                self.assertTrue(os.path.exists(grouped))
                self.assertFalse(os.path.exists(os.path.join(
                    td, "zs2", "zpa_segment_group", "main.tf"
                )))
                with open(grouped, encoding="utf-8") as f:
                    main_tf = f.read()
                self.assertIn('module "zpa_segment_group"', main_tf)
                self.assertIn('module "zpa_server_group"', main_tf)
            finally:
                if saved is None:
                    os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
                else:
                    os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved

    def test_config_plan_reference_resolves_to_committed_config(self):
        from engine.gen_env import generate_env
        tenant = "demo"
        resource_type = "zia_url_categories"
        repo_deployment = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "deployment.json",
        )
        saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
        os.environ["INFRAWRIGHT_DEPLOYMENT"] = repo_deployment
        try:
            config_path = os.path.join(
                deployment.config_dir(tenant),
                resource_type + ".auto.tfvars.json",
            )
            self.assertTrue(os.path.exists(config_path), config_path)
            with tempfile.TemporaryDirectory() as td:
                generate_env(
                    tenant, out_root=td, fmt=False, selectors=[resource_type])
                env_root_dir = os.path.join(td, tenant, resource_type)
                smoke_path = os.path.join(env_root_dir, "tests", "smoke.tftest.hcl")
                with open(smoke_path, encoding="utf-8") as f:
                    smoke = f.read()
                match = re.search(r'jsondecode\(file\("([^"]+)"\)\)', smoke)
                self.assertIsNotNone(match, smoke)
                resolved = os.path.normpath(os.path.join(env_root_dir, match.group(1)))
                self.assertEqual(
                    resolved,
                    os.path.normpath(os.path.abspath(config_path)),
                )
        finally:
            if saved is None:
                os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
            else:
                os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved

    def test_expression_binding_file_writes_env_root_overlay(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            dep = os.path.join(td, "deployment.json")
            with open(dep, "w", encoding="utf-8") as f:
                f.write(json.dumps({"overlay": td}))
            saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
            os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep
            try:
                tenant = "tenant"
                resource_type = "zpa_application_segment"
                config_dir = os.path.join(td, "config", tenant)
                os.makedirs(config_dir)
                with open(
                    os.path.join(
                        config_dir, resource_type + ".auto.tfvars.json"),
                    "w",
                    encoding="utf-8",
                ) as f:
                    json.dump({
                        "items": {
                            "example": {
                                "clientless_app_config": {
                                    "username": "svc-user",
                                    "password": None,
                                },
                            },
                        },
                    }, f)
                with open(
                    os.path.join(
                        config_dir, resource_type + ".expressions.json"),
                    "w",
                    encoding="utf-8",
                ) as f:
                    json.dump({
                        "resources": {
                            "zpa_application_segment.example": {
                                "clientless_app_config.password": {
                                    "expression": "var.zpa_client_secret",
                                    "sensitive": True,
                                },
                            },
                        },
                    }, f)
                generate_env(
                    tenant,
                    out_root=os.path.join(td, "generated-envs"),
                    fmt=False,
                    selectors=[resource_type],
                )
                base = os.path.join(
                    td, "generated-envs", tenant, resource_type)
                with open(os.path.join(base, "main.tf"), encoding="utf-8") as f:
                    self.assertIn(
                        "items = local.infrawright_expression_bound_items",
                        f.read(),
                    )
                with open(
                    os.path.join(base, "expression_bindings.tf"),
                    encoding="utf-8",
                ) as f:
                    overlay = f.read()
                self.assertIn('variable "zpa_client_secret"', overlay)
                self.assertIn("sensitive = true", overlay)
                self.assertIn("password = var.zpa_client_secret", overlay)
            finally:
                if saved is None:
                    os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
                else:
                    os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved

    def test_literal_expression_like_string_without_sidecar_stays_var_items(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            dep = os.path.join(td, "deployment.json")
            with open(dep, "w", encoding="utf-8") as f:
                f.write(json.dumps({"overlay": td}))
            saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
            os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep
            try:
                tenant = "tenant"
                resource_type = "zpa_application_segment"
                config_dir = os.path.join(td, "config", tenant)
                os.makedirs(config_dir)
                with open(
                    os.path.join(
                        config_dir, resource_type + ".auto.tfvars.json"),
                    "w",
                    encoding="utf-8",
                ) as f:
                    json.dump({
                        "items": {
                            "example": {
                                "clientless_app_config": {
                                    "password": "var.zpa_client_secret",
                                },
                            },
                        },
                    }, f)

                generate_env(
                    tenant,
                    out_root=os.path.join(td, "generated-envs"),
                    fmt=False,
                    selectors=[resource_type],
                )

                base = os.path.join(
                    td, "generated-envs", tenant, resource_type)
                self.assertFalse(os.path.exists(os.path.join(
                    base, "expression_bindings.tf",
                )))
                with open(os.path.join(base, "main.tf"), encoding="utf-8") as f:
                    main_tf = f.read()
                self.assertIn("items = var.items", main_tf)

                generated_text = ""
                for root, _, filenames in os.walk(base):
                    for filename in filenames:
                        path = os.path.join(root, filename)
                        with open(path, encoding="utf-8") as f:
                            generated_text += f.read()
                self.assertNotIn(
                    "password = var.zpa_client_secret",
                    generated_text,
                )
            finally:
                if saved is None:
                    os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
                else:
                    os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved

    def test_expression_binding_missing_parent_fails_closed(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            dep = os.path.join(td, "deployment.json")
            with open(dep, "w", encoding="utf-8") as f:
                f.write(json.dumps({"overlay": td}))
            saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
            os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep
            try:
                tenant = "tenant"
                resource_type = "zpa_application_segment"
                config_dir = os.path.join(td, "config", tenant)
                os.makedirs(config_dir)
                with open(
                    os.path.join(
                        config_dir, resource_type + ".auto.tfvars.json"),
                    "w",
                    encoding="utf-8",
                ) as f:
                    json.dump({"items": {"example": {}}}, f)
                with open(
                    os.path.join(
                        config_dir, resource_type + ".expressions.json"),
                    "w",
                    encoding="utf-8",
                ) as f:
                    json.dump({
                        "resources": {
                            "zpa_application_segment.example": {
                                "clientless_app_config.password": {
                                    "expression": "var.zpa_client_secret",
                                },
                            },
                        },
                    }, f)

                with self.assertRaises(ValueError):
                    generate_env(
                        tenant,
                        out_root=os.path.join(td, "generated-envs"),
                        fmt=False,
                        selectors=[resource_type],
                    )
            finally:
                if saved is None:
                    os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
                else:
                    os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved

    def test_expression_binding_missing_leaf_fails_closed(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            dep = os.path.join(td, "deployment.json")
            with open(dep, "w", encoding="utf-8") as f:
                f.write(json.dumps({"overlay": td}))
            saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
            os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep
            try:
                tenant = "tenant"
                resource_type = "zpa_application_segment"
                config_dir = os.path.join(td, "config", tenant)
                os.makedirs(config_dir)
                with open(
                    os.path.join(
                        config_dir, resource_type + ".auto.tfvars.json"),
                    "w",
                    encoding="utf-8",
                ) as f:
                    json.dump({
                        "items": {
                            "example": {
                                "clientless_app_config": {
                                    "username": "svc-user",
                                },
                            },
                        },
                    }, f)
                with open(
                    os.path.join(
                        config_dir, resource_type + ".expressions.json"),
                    "w",
                    encoding="utf-8",
                ) as f:
                    json.dump({
                        "resources": {
                            "zpa_application_segment.example": {
                                "clientless_app_config.password": {
                                    "expression": "var.zpa_client_secret",
                                },
                            },
                        },
                    }, f)

                with self.assertRaises(ValueError):
                    generate_env(
                        tenant,
                        out_root=os.path.join(td, "generated-envs"),
                        fmt=False,
                        selectors=[resource_type],
                    )
            finally:
                if saved is None:
                    os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
                else:
                    os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved

    def test_expression_binding_file_removed_when_sidecar_is_absent(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            base = os.path.join(
                td, "tenant", "zpa_application_segment")
            os.makedirs(base)
            stale = os.path.join(base, "expression_bindings.tf")
            with open(stale, "w", encoding="utf-8") as f:
                f.write("# stale\n")
            generate_env(
                "tenant",
                out_root=td,
                fmt=False,
                selectors=["zpa_application_segment"],
            )
            self.assertFalse(os.path.exists(stale))


class RenderEnvExpressionBindingsTest(unittest.TestCase):
    def test_render_env_expression_bindings_delegates_to_hcl_renderer(self):
        from engine import expression_bindings

        bindings = expression_bindings.parse_bindings({
            "resources": {
                "zpa_application_segment.example": {
                    "clientless_app_config.password": {
                        "expression": "var.zpa_client_secret",
                        "sensitive": True,
                    },
                },
            },
        }, "zpa_application_segment")

        text = render_env_expression_bindings(bindings)
        self.assertIn(
            "infrawright_expression_bound_items = merge(var.items, {",
            text,
        )
        self.assertIn("password = var.zpa_client_secret", text)


class ExpandResourcesTest(unittest.TestCase):
    def test_exact_selector(self):
        self.assertEqual(
            expand_resources(["zia_url_categories"]),
            ["zia_url_categories"])

    def test_product_selector(self):
        resources = expand_resources(["zpa"])
        self.assertIn("zpa_segment_group", resources)
        self.assertTrue(all(rt.startswith("zpa_") for rt in resources))

    def test_unknown_selector_is_loud(self):
        with self.assertRaises(ValueError):
            expand_resources(["does_not_exist"])


class RenderEnvTestTest(unittest.TestCase):
    def test_mock_provider_matches_product(self):
        out = render_env_test("zpa_segment_group", "zs2", has_config=False)
        self.assertIn('mock_provider "zpa" {}', out)
        self.assertIn("command = plan", out)
        self.assertIn("items = {}", out)

    def test_zia_mock(self):
        out = render_env_test("zia_url_categories", "zs2", has_config=False)
        self.assertIn('mock_provider "zia" {}', out)

    def test_no_config_plan_when_has_config_false(self):
        out = render_env_test("zpa_segment_group", "zs2", has_config=False)
        self.assertNotIn("config_plan", out)

    def test_config_plan_present_when_has_config_true(self):
        out = render_env_test("zpa_segment_group", "zs2", has_config=True)
        self.assertIn('run "config_plan"', out)
        self.assertIn("command = plan", out)

    def test_hcl_config_does_not_emit_jsondecode_config_plan(self):
        out = render_env_test(
            "zpa_segment_group", "zs2", has_config=True,
            config_format="hcl")
        self.assertNotIn('run "config_plan"', out)
        self.assertNotIn("jsondecode", out)
        self.assertIn('run "empty_plan"', out)

    def test_config_plan_file_path_correct(self):
        out = render_env_test("zpa_segment_group", "zs2", has_config=True)
        self.assertIn(
            'file("../../../config/zs2/zpa_segment_group.auto.tfvars.json")',
            out,
        )

    def test_config_plan_file_path_demo_tenant(self):
        out = render_env_test("zia_url_categories", "demo", has_config=True)
        self.assertIn(
            'file("../../../config/demo/zia_url_categories.auto.tfvars.json")',
            out,
        )

    def test_empty_plan_still_present_when_has_config_true(self):
        out = render_env_test("zpa_segment_group", "zs2", has_config=True)
        self.assertIn('run "empty_plan"', out)
        self.assertIn("items = {}", out)

    def test_config_ref_resolves_under_overlay(self):
        # With an overlay set, the smoke-test file() ref must STILL resolve to the
        # real (overlay-prefixed) config file — relpath has to cancel the prefix.
        # Regression guard for the env path math under a non-root overlay.
        import json
        import re
        import tempfile
        from engine.gen_env import render_env_test, _env_root_dir, _config_file
        rt, tenant = "zia_url_categories", "zs3"
        with tempfile.TemporaryDirectory() as td:
            dep = os.path.join(td, "deployment.json")
            with open(dep, "w", encoding="utf-8") as f:
                f.write(json.dumps({"overlay": "acme"}))
            saved = os.environ.get("INFRAWRIGHT_DEPLOYMENT")
            os.environ["INFRAWRIGHT_DEPLOYMENT"] = dep
            try:
                env_dir = _env_root_dir(tenant, rt)
                config_file = _config_file(tenant, rt)
                self.assertTrue(config_file.startswith(os.path.join("acme", "config")))
                out = render_env_test(rt, tenant, env_dir=env_dir, has_config=True)
                ref = re.search(r'file\("([^"]+)"\)', out).group(1)
                resolved = os.path.normpath(os.path.join(env_dir, ref))
                self.assertEqual(resolved, os.path.normpath(config_file))
            finally:
                if saved is None:
                    os.environ.pop("INFRAWRIGHT_DEPLOYMENT", None)
                else:
                    os.environ["INFRAWRIGHT_DEPLOYMENT"] = saved


class BackendMarkerTest(unittest.TestCase):
    def test_backend_choice_survives_regeneration(self):
        # The backend choice is data (envs/<t>/.backend): a later regen
        # WITHOUT the backend argument — exactly what check-envs does —
        # must reproduce the same roots, not revert them to local state.
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            generate_env("zs2", out_root=td, fmt=False, backend="azurerm")
            main_path = os.path.join(td, "zs2", "zpa_segment_group", "main.tf")
            with open(main_path, encoding="utf-8") as f:
                first = f.read()
            self.assertIn('backend "azurerm"', first)
            generate_env("zs2", out_root=td, fmt=False)  # no backend arg
            with open(main_path, encoding="utf-8") as f:
                second = f.read()
            self.assertEqual(first, second)

    def test_no_marker_no_backend(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            generate_env("zs2", out_root=td, fmt=False)
            self.assertFalse(
                os.path.exists(os.path.join(td, "zs2", ".backend"))
            )
            with open(os.path.join(td, "zs2", "zpa_segment_group", "main.tf"), encoding="utf-8") as f:
                self.assertNotIn('backend "', f.read())


class GenerateEnvWritesTest(unittest.TestCase):
    def test_writes_smoke_test(self):
        from engine.gen_env import generate_env
        with tempfile.TemporaryDirectory() as td:
            generate_env("zs2", out_root=td, fmt=False)
            self.assertTrue(os.path.exists(os.path.join(
                td, "zs2", "zpa_segment_group", "tests", "smoke.tftest.hcl"
            )))



class ReadmeContentTest(unittest.TestCase):
    def test_readme_names_tenant_resource_and_regen_command(self):
        from engine.gen_env import render_env_readme
        text = render_env_readme("zpa_segment_group", "acme")
        self.assertIn("acme", text)
        self.assertIn("zpa_segment_group", text)
        self.assertIn("make gen-env", text)


class HclBindingValidationSkipTest(unittest.TestCase):
    def test_hcl_config_skips_binding_validation_with_warning(self):
        from engine import gen_env

        tmp = tempfile.mkdtemp(prefix="genenv-hcl-bindings-")
        self.addCleanup(lambda: __import__("shutil").rmtree(tmp, True))
        config_path = os.path.join(tmp, "sample_resource.auto.tfvars")
        with open(config_path, "w", encoding="utf-8") as f:
            f.write("items = {}\n")

        stderr = io.StringIO()
        saved = sys.stderr
        sys.stderr = stderr
        try:
            gen_env._validate_expression_bindings_against_config(
                object(), config_path)
        finally:
            sys.stderr = saved
        self.assertIn(
            "skip expression binding validation", stderr.getvalue())
        self.assertIn("hcl tfvars", stderr.getvalue())


if __name__ == "__main__":
    unittest.main()
