# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

resource "cloudflare_zone" "this" {
  for_each = var.items

  account             = each.value.account
  name                = each.value.name
  type                = each.value.type
  vanity_name_servers = each.value.vanity_name_servers
}
