# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed cloudflare_zone resources, keyed as in var.items."
  value       = cloudflare_zone.this
}

output "name_to_id" {
  description = "Map of resource name to provider-assigned id."
  value       = { for k, v in cloudflare_zone.this : v.name => v.id }
}
