# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "cloudflare_zone instances, keyed by a stable identifier."
  type = map(object({
    account = object({
      id = optional(string)
    })
    name                = string
    type                = optional(string)
    vanity_name_servers = optional(list(string))
  }))
}
