package envgen

// TestSetBlockRenderDerivationEmitsCompleteLeafExpression extends the Part A
// render-derivation coverage in reference_resolvers_test.go to the one
// binding shape that family never exercised end to end: a reference field
// whose dotted path crosses a set-nested block
// (BindingContext.SetBlockFields), the "bind the complete block leaf" case
// pinned in isolation by set_block_binding_roundtrip_test.go. The expected
// expression_bindings.tf bytes are hand-pinned rather than re-derived
// through the same engine, so a set-block derivation regression fails this
// test instead of agreeing with itself. See
// docs/superpowers/specs/2026-07-31-sidecar-minimization-design.md Part A.

import (
	"path/filepath"
	"testing"

	"github.com/dvmrry/infrawright-dev/go/internal/metadata"
)

// syntheticSetBlockPackRoot builds the smallest pack universe carrying a
// set-nested reference field -- zia_firewall_filtering_network_service_groups
// .services.id, the shape set_block_binding_roundtrip_test.go's
// ziaSetBlockSchema names as "the downstream wave-2 blocker": a set block
// whose element carries a set(number) reference attribute. It is kept
// separate from syntheticRootForTopology (pack_scope_test.go) rather than
// added to it: that root's zpa_server_group/zia_url_filtering_rules nested
// reference fields are deliberately list-nested (several other tests pin
// their indexed-path behavior), and folding a set-nested block into an
// existing field there would change what those tests exercise. A dedicated,
// minimal root keeps this fixture's blast radius at zero.
func syntheticSetBlockPackRoot(t *testing.T) metadata.LoadedPackRoot {
	t.Helper()
	packsRoot := t.TempDir()

	computedString := func() metadata.JsonObject { return terraformTestAttribute("string", "computed") }
	optionalString := func() metadata.JsonObject { return terraformTestAttribute("string", "optional") }

	ziaSchemas := metadata.JsonObject{
		"zia_firewall_filtering_network_service": terraformTestBlock(metadata.JsonObject{
			"id":   computedString(),
			"name": optionalString(),
		}),
		"zia_firewall_filtering_network_service_groups": metadata.JsonObject{"block": metadata.JsonObject{
			"attributes": metadata.JsonObject{
				"id":   computedString(),
				"name": optionalString(),
			},
			"block_types": metadata.JsonObject{
				"services": metadata.JsonObject{
					"nesting_mode": "set",
					"block": metadata.JsonObject{"attributes": metadata.JsonObject{
						"id": terraformTestAttribute([]any{"set", "number"}, "required"),
					}},
				},
			},
		}},
	}
	ziaRegistry := metadata.JsonObject{}
	for resourceType := range ziaSchemas {
		ziaRegistry[resourceType] = metadata.JsonObject{"generate": true, "product": "zia"}
	}
	writeSyntheticTopologyPack(t, packsRoot, "zia", metadata.JsonObject{
		"pin":               "1.0.0",
		"provider_prefixes": metadata.JsonObject{"zia_": "zia"},
		"provider_sources":  metadata.JsonObject{"zia": "zscaler/zia"},
		"references": metadata.JsonObject{
			"zia_firewall_filtering_network_service_groups": metadata.JsonObject{
				"services.id": metadata.JsonObject{"name_field": "name", "referent": "zia_firewall_filtering_network_service"},
			},
		},
	}, ziaRegistry, ziaSchemas)

	profilePath := filepath.Join(packsRoot, "synthetic.packset.json")
	writeJSONFile(t, profilePath, metadata.JsonObject{
		"kind": metadata.PackSetKind, "version": 1,
		"packs": []any{"zia"}, "shared": []any{},
	})
	loaded, err := metadata.LoadPackRoot(metadata.LoadPackRootOptions{
		PacksRoot: packsRoot, ProfilePath: &profilePath,
	})
	if err != nil {
		t.Fatalf("LoadPackRoot(synthetic set-block fixture) error: %v", err)
	}
	return loaded
}

// setBlockExpectedBindingsTF is the hand-pinned expression_bindings.tf the
// fixture must render: the lookup-first set-block resolver locals plus the
// complete-leaf composite expression ("[{ id = [...] }]", the grammar
// TestCompositeExpressionAllowlist pins) substituted for group_one's whole
// services value.
const setBlockExpectedBindingsTF = `locals {
  iw_reference_lookup_zia_firewall_filtering_network_service = fileexists("${path.module}/../../../config/tenant/lookups/zia_firewall_filtering_network_service.lookup.json") ? try(jsondecode(file("${path.module}/../../../config/tenant/lookups/zia_firewall_filtering_network_service.lookup.json")).id_by_key, { for id, k in jsondecode(file("${path.module}/../../../config/tenant/lookups/zia_firewall_filtering_network_service.lookup.json")).key_by_id : k => id }) : {}
}

# GENERATED by engine.gen_env from expression bindings — do not edit.
# Regenerate: make gen-env TENANT=<tenant>

locals {
  iw_expression_bound_items = merge(var.items, {
    "group_one" = merge(var.items["group_one"], {
          services = [{ id = [try(data.terraform_remote_state.zia_firewall_filtering_network_service.outputs.iw_reference_ids.zia_firewall_filtering_network_service["service_one"], local.iw_reference_lookup_zia_firewall_filtering_network_service["service_one"])] }]
        })
  })
}
`

func TestSetBlockRenderDerivationEmitsCompleteLeafExpression(t *testing.T) {
	root := syntheticSetBlockPackRoot(t)
	workspace := temporaryDirectory(t, "infrawright-gen-env-set-block-derivation-")
	deploymentPath := filepath.Join(workspace, "deployment.json")
	writeJSONFile(t, deploymentPath, map[string]any{
		"overlay": workspace,
		"roots":   map[string]any{"zia": map[string]any{"cross_state_references": true}},
	})

	const referrerType = "zia_firewall_filtering_network_service_groups"
	const referentType = "zia_firewall_filtering_network_service"

	config := filepath.Join(workspace, "config", "tenant")
	writeJSONFile(t, filepath.Join(config, referentType+".auto.tfvars.json"), map[string]any{
		"items": map[string]any{"service_one": map[string]any{"name": "Service One"}},
	})
	writeJSONFile(t, filepath.Join(config, "lookups", referentType+".lookup.json"), map[string]any{
		"by_id":     map[string]any{"svc-1": "Service One"},
		"id_by_key": map[string]any{"service_one": "svc-1"},
		"key_by_id": map[string]any{"svc-1": "service_one"},
	})
	writeJSONFile(t, filepath.Join(config, referrerType+".auto.tfvars.json"), map[string]any{
		"items": map[string]any{"group_one": map[string]any{
			"name": "IoT Group",
			"services": []any{
				map[string]any{"id": []any{referentType + ".service_one"}},
			},
		}},
	})

	dep := loadDeploymentFile(t, deploymentPath)
	outputRoot := filepath.Join(workspace, "generated")
	diagnostics := make([]string, 0)
	if _, err := GenerateEnvironmentRoots(GenerateEnvironmentRootsOptions{
		Deployment:   dep,
		FormatHcl:    identityFormatter,
		OnDiagnostic: func(message string) { diagnostics = append(diagnostics, message) },
		OutputRoot:   &outputRoot,
		Root:         root,
		Selectors:    []string{referrerType},
		Tenant:       "tenant",
	}); err != nil {
		t.Fatalf("GenerateEnvironmentRoots error = %v, want nil", err)
	}

	// The derivation accounting proves the run actually derived the binding at
	// render time (no committed cache exists in this fixture to bridge from).
	if !containsString(diagnostics, "NOTE bindings: "+referrerType+": 1 bound, 0 skipped") {
		t.Fatalf("diagnostics = %v, want the render-derivation accounting", diagnostics)
	}
	derived := snapshotTree(t, filepath.Join(outputRoot, "tenant", referrerType))
	if got := derived[expressionBindingsTF]; got != setBlockExpectedBindingsTF {
		t.Errorf("%s derived at render =\n%q\nwant the hand-pinned set-block bytes:\n%q",
			expressionBindingsTF, got, setBlockExpectedBindingsTF)
	}
}
