# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

resource "cloudflare_list" "this" {
  for_each = var.items

  account_id  = each.value.account_id
  kind        = each.value.kind
  name        = each.value.name
  description = each.value.description
}
