# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "cloudflare_list instances, keyed by a stable identifier."
  type = map(object({
    account_id  = string
    kind        = string
    name        = string
    description = optional(string)
  }))
}
