import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

const ROOT = process.cwd();
const SCRIPT = path.join(ROOT, "scripts", "normalize-frozen-authority-provenance.mjs");
const POINTER =
  "See docs/python-oracle-contracts.md for the exact clean-checkout resurrection command.";

const PROFILES = [
  {
    name: "engine-ops",
    files: [
      "python-assessment-cli-v1.json",
      "python-differential-v1.json",
      "python-plan-cli-v1.json",
    ],
    property: "clean_checkout_resurrection",
    generator: "generate-engine-ops-authority.py",
  },
  {
    name: "environment",
    files: ["python-environment-roots-v1.json"],
    property: "producing_command",
    generator: "generate-python-environment-roots-authority.py",
  },
  {
    name: "reconcile-openapi",
    files: [
      "python-reconcile-schema-api-v1.json",
      "python-openapi-resource-map-v1.json",
    ],
    property: "producing_command",
    generator: "generate-reconcile-openapi-authority.py",
  },
  {
    name: "source-operation",
    files: [
      "python-source-operation-map-v1.json",
      "python-sdk-path-evidence-v1.json",
    ],
    property: "resurrection",
    generator: "generate-source-operation-authority.py",
  },
] as const;

test("frozen-authority provenance normalization preserves generated bytes outside the command", async (context) => {
  for (const profile of PROFILES) {
    const directory = await mkdtemp(path.join(os.tmpdir(), `iw-authority-${profile.name}-`));
    context.after(() => rm(directory, { force: true, recursive: true }));
    for (const file of profile.files) {
      await writeFile(
        path.join(directory, file),
        `{"large":9007199254740993,"${profile.property}":"run ${profile.generator}","tail":"unchanged"}\n`,
        "utf8",
      );
    }
    const result = spawnSync(process.execPath, [
      SCRIPT,
      "--profile",
      profile.name,
      "--fixtures-root",
      directory,
    ], { encoding: "utf8" });
    assert.equal(result.status, 0, result.stderr);
    for (const file of profile.files) {
      const bytes = await readFile(path.join(directory, file), "utf8");
      assert.equal(
        bytes,
        `{"large":9007199254740993,"${profile.property}":${JSON.stringify(POINTER)},"tail":"unchanged"}\n`,
      );
    }
  }
});

test("frozen-authority provenance normalization fails closed", async (context) => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "iw-authority-invalid-"));
  context.after(() => rm(directory, { force: true, recursive: true }));
  for (const file of PROFILES[0].files) {
    await writeFile(
      path.join(directory, file),
      '{"clean_checkout_resurrection":"wrong generator"}\n',
      "utf8",
    );
  }
  const result = spawnSync(process.execPath, [
    SCRIPT,
    "--profile",
    "engine-ops",
    "--fixtures-root",
    directory,
  ], { encoding: "utf8" });
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /does not reference generate-engine-ops-authority\.py/u);
});
