import assert from "node:assert/strict";
import {
  cp,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import { loadPackRoot, type LoadedPackRoot } from "../node-src/metadata/loader.js";
import {
  activeGeneratedResourceTypes,
  EXPECTED_MODULE_FILES,
  generateActiveModules,
  generateModule,
  renderModuleFiles,
  terraformHclFormatter,
  validateGeneratedModuleTree,
  type HclFormatter,
} from "../node-src/modules/generator.js";

const ROOT = process.cwd();
const IDENTITY_FORMATTER: HclFormatter = async (source) => source;

async function committedRoot(): Promise<LoadedPackRoot> {
  return loadPackRoot({
    packsRoot: path.join(ROOT, "packs"),
    profilePath: path.join(ROOT, "packsets", "full.json"),
    catalogPath: path.join(ROOT, "packsets", "full.json"),
  });
}

async function writeJson(pathname: string, value: unknown): Promise<void> {
  await mkdir(path.dirname(pathname), { recursive: true });
  await writeFile(pathname, `${JSON.stringify(value, null, 2)}\n`);
}

const SIMPLE_SCHEMA = {
  block: {
    attributes: {
      id: { type: "string", optional: true, computed: true },
      name: { type: "string", required: true },
      note: { type: "string", optional: true },
    },
    block_types: {
      rules: {
        nesting_mode: "set",
        min_items: 1,
        block: {
          attributes: {
            enabled: { type: "bool", required: true },
          },
        },
      },
    },
  },
};

async function syntheticRoot(options?: {
  readonly schema?: unknown;
  readonly pin?: string | null;
  readonly source?: string | null;
  readonly sample?: unknown;
  readonly overrideText?: string;
  readonly mainOverride?: string;
}): Promise<{ readonly directory: string; readonly root: LoadedPackRoot }> {
  const directory = await mkdtemp(path.join(os.tmpdir(), "infrawright-modules-"));
  const pack: Record<string, unknown> = {
    provider_prefixes: { sample_: "sample" },
  };
  if (options?.pin !== null) pack.pin = options?.pin ?? "1.2.3";
  if (options?.source !== null) {
    pack.provider_sources = { sample: options?.source ?? "example/sample" };
  }
  await writeJson(path.join(directory, "sample", "pack.json"), pack);
  await writeJson(path.join(directory, "sample", "registry.json"), {
    sample_resource: { generate: true, product: "sample" },
  });
  await writeJson(path.join(directory, "sample", "schemas", "provider", "sample.json"), {
    resource_schemas: { sample_resource: options?.schema ?? SIMPLE_SCHEMA },
  });
  if (options?.overrideText !== undefined) {
    const override = path.join(
      directory,
      "sample",
      "overrides",
      "sample_resource.json",
    );
    await mkdir(path.dirname(override), { recursive: true });
    await writeFile(override, options.overrideText);
  } else if (options?.sample !== undefined) {
    await writeJson(
      path.join(directory, "sample", "overrides", "sample_resource.json"),
      { sample: options.sample },
    );
  }
  if (options?.mainOverride !== undefined) {
    const main = path.join(
      directory,
      "sample",
      "overrides",
      "sample_resource",
      "main.tf",
    );
    await mkdir(path.dirname(main), { recursive: true });
    await writeFile(main, options.mainOverride);
  }
  const profile = path.join(directory, "profile.json");
  await writeJson(profile, {
    kind: "infrawright.pack-set",
    version: 1,
    packs: ["sample"],
    shared: [],
  });
  return {
    directory,
    root: await loadPackRoot({ packsRoot: directory, profilePath: profile }),
  };
}

test("renderer preserves the complete seven-file contract and core shapes", async () => {
  const root = await committedRoot();
  const segment = await renderModuleFiles(root, "zpa_segment_group");
  assert.deepEqual([...segment.files.keys()], EXPECTED_MODULE_FILES);
  assert.match(
    segment.files.get("main.tf") ?? "",
    /^# GENERATED by iw modules generate from packs\/zpa\/schemas\/provider\/zpa\.json — do not edit\.\n# Regenerate: make gen-modules\n/,
  );
  assert.doesNotMatch(segment.files.get("main.tf") ?? "", /python|engine\.gen_module/);
  assert.match(
    segment.files.get("README.md") ?? "",
    /Regenerate with `iw modules generate` or `make gen-modules`\./,
  );
  assert.doesNotMatch(segment.files.get("README.md") ?? "", /python|engine\.gen_module/);
  assert.match(segment.files.get("main.tf") ?? "", /for_each = var\.items/);
  assert.match(
    segment.files.get("main.tf") ?? "",
    /dynamic "applications"[\s\S]*each\.value\.applications == null \? \[\] : each\.value\.applications/,
  );
  assert.doesNotMatch(segment.files.get("main.tf") ?? "", /\n  id =/);
  assert.match(
    segment.files.get("variables.tf") ?? "",
    /type = map\(object\(\{[\s\S]*name = string[\s\S]*description = optional\(string\)/,
  );
  assert.match(segment.files.get("outputs.tf") ?? "", /output "name_to_id"/);
  assert.equal(
    segment.files.get("tests/sample.auto.tfvars.json"),
    '{\n  "items": {\n    "example": {\n      "name": "example"\n    }\n  }\n}\n',
  );

  const categories = await renderModuleFiles(root, "zia_url_categories");
  const variables = categories.files.get("variables.tf") ?? "";
  assert.match(variables, /scopes = optional\(set\(object\(\{/);
  assert.match(variables, /url_keyword_counts = optional\(object\(\{/);
  assert.match(variables, /scope_entities = optional\(object\(\{/);
  assert.doesNotMatch(variables, /category_id/);
  assert.doesNotMatch(categories.files.get("outputs.tf") ?? "", /name_to_id/);
});

test("samples, sensitive outputs, deprecated projection, and nested types match authority", async () => {
  const root = await committedRoot();
  const filtering = await renderModuleFiles(root, "zia_url_filtering_rules");
  const filteringSample = JSON.parse(
    filtering.files.get("tests/sample.auto.tfvars.json") ?? "{}",
  ) as { items: { example: { protocols: unknown } } };
  assert.deepEqual(filteringSample.items.example.protocols, ["ANY_RULE"]);

  const sensitive = await renderModuleFiles(root, "zia_location_management");
  assert.match(sensitive.files.get("outputs.tf") ?? "", /sensitive\s+= true/);

  const deprecated = await renderModuleFiles(root, "zpa_policy_access_rule");
  const deprecatedOutput = deprecated.files.get("outputs.tf") ?? "";
  assert.match(deprecatedOutput, /excludes deprecated: rule_order/);
  assert.doesNotMatch(deprecatedOutput, /rule_order = v\.rule_order/);

  const framework = await renderModuleFiles(root, "zcc_zia_posture");
  const frameworkVariables = framework.files.get("variables.tf") ?? "";
  assert.match(frameworkVariables, /high_trust_criteria = optional\(object\(\{/);
  assert.match(frameworkVariables, /cs = optional\(list\(object\(\{/);

  const requiredBlock = await renderModuleFiles(root, "zpa_policy_access_rule_reorder");
  const requiredSample = JSON.parse(
    requiredBlock.files.get("tests/sample.auto.tfvars.json") ?? "{}",
  ) as { items: { example: { rules: unknown[] } } };
  assert.equal(requiredSample.items.example.rules.length, 1);
});

test("resource-owned main override and JSON sample come only through the loader", async () => {
  const fixture = await syntheticRoot({
    mainOverride: "# resource-owned override\n",
    sample: { name: "chosen", extra: 7 },
  });
  const output = await mkdtemp(path.join(os.tmpdir(), "infrawright-output-"));
  try {
    assert.equal(
      await fixture.root.loadResourceMainOverride("sample_resource"),
      "# resource-owned override\n",
    );
    const rendered = await renderModuleFiles(fixture.root, "sample_resource");
    assert.equal(rendered.files.get("main.tf"), "# resource-owned override\n");
    const sample = JSON.parse(
      rendered.files.get("tests/sample.auto.tfvars.json") ?? "{}",
    ) as { items: { example: Record<string, unknown> } };
    assert.deepEqual(sample.items.example, {
      extra: 7,
      name: "chosen",
      rules: [{ enabled: true }],
    });
    const generated = await generateModule(fixture.root, "sample_resource", {
      outputRoot: output,
      formatHcl: IDENTITY_FORMATTER,
    });
    assert.equal(generated.files.length, 7);
    assert.deepEqual(
      await validateGeneratedModuleTree(output, ["sample_resource"]),
      ["sample_resource"],
    );
  } finally {
    await rm(fixture.directory, { recursive: true, force: true });
    await rm(output, { recursive: true, force: true });
  }
});

test("single input blocks wrap one object while computed-only blocks disappear", async () => {
  const fixture = await syntheticRoot({
    schema: {
      block: {
        attributes: { name: { type: "string", required: true } },
        block_types: {
          settings: {
            nesting_mode: "single",
            block: { attributes: { on: { type: "bool", optional: true } } },
          },
          observed: {
            nesting_mode: "set",
            block: { attributes: { value: { type: "string", computed: true } } },
          },
        },
      },
    },
  });
  try {
    const rendered = await renderModuleFiles(fixture.root, "sample_resource");
    assert.match(
      rendered.files.get("main.tf") ?? "",
      /each\.value\.settings == null \? \[\] : \[each\.value\.settings\]/,
    );
    assert.match(rendered.files.get("variables.tf") ?? "", /settings = optional\(object\(\{/);
    assert.doesNotMatch(rendered.files.get("main.tf") ?? "", /dynamic "observed"/);
    assert.doesNotMatch(rendered.files.get("variables.tf") ?? "", /observed =/);
  } finally {
    await rm(fixture.directory, { recursive: true, force: true });
  }
});

test("fractional sample override numbers retain exact Python JSON spelling", async () => {
  const fixture = await syntheticRoot({
    overrideText: '{"sample":{"half":0.5,"negative_zero":-0.0,"scientific":1e-6}}\n',
  });
  try {
    const rendered = await renderModuleFiles(fixture.root, "sample_resource");
    const sample = rendered.files.get("tests/sample.auto.tfvars.json") ?? "";
    assert.match(sample, /"half": 0\.5/);
    assert.match(sample, /"negative_zero": -0\.0/);
    assert.match(sample, /"scientific": 1e-06/);
  } finally {
    await rm(fixture.directory, { recursive: true, force: true });
  }
});

test("all active resources generate and validate a complete temporary tree", async () => {
  const root = await committedRoot();
  const output = await mkdtemp(path.join(os.tmpdir(), "infrawright-output-"));
  try {
    assert.equal(activeGeneratedResourceTypes(root).length, 151);
    const generated = await generateActiveModules(root, {
      outputRoot: output,
      formatHcl: IDENTITY_FORMATTER,
    });
    assert.equal(generated.length, 151);
    assert.equal(generated.reduce((sum, item) => sum + item.files.length, 0), 1057);
    assert.equal((await validateGeneratedModuleTree(
      output,
      activeGeneratedResourceTypes(root),
    )).length, 151);
  } finally {
    await rm(output, { recursive: true, force: true });
  }
});

test("every committed profile drives generation from its physically reduced pack root", async (context) => {
  const expected: Readonly<Record<string, number>> = {
    full: 151,
    zscaler: 151,
    zcc: 7,
    zia: 74,
    zpa: 54,
    ztc: 16,
    empty: 0,
    aws: 0,
    cloudflare: 0,
    google: 0,
    netbox: 0,
  };
  for (const [profileName, count] of Object.entries(expected)) {
    await context.test(profileName, async () => {
      const directory = await mkdtemp(path.join(os.tmpdir(), "infrawright-profile-"));
      const output = await mkdtemp(path.join(os.tmpdir(), "infrawright-output-"));
      try {
        const profilePath = path.join(ROOT, "packsets", `${profileName}.json`);
        const profile = JSON.parse(await readFile(profilePath, "utf8")) as {
          readonly packs: readonly string[];
          readonly shared: readonly string[];
        };
        for (const name of profile.packs) {
          await cp(path.join(ROOT, "packs", name), path.join(directory, name), {
            recursive: true,
          });
        }
        for (const name of profile.shared) {
          await cp(
            path.join(ROOT, "packs", "_shared", name),
            path.join(directory, "_shared", name),
            { recursive: true },
          );
        }
        const loaded = await loadPackRoot({
          packsRoot: directory,
          profilePath,
          catalogPath: path.join(ROOT, "packsets", "full.json"),
        });
        const generated = await generateActiveModules(loaded, {
          outputRoot: output,
          formatHcl: IDENTITY_FORMATTER,
        });
        assert.equal(generated.length, count);
        assert.equal(generated.reduce((sum, item) => sum + item.files.length, 0), count * 7);
        await validateGeneratedModuleTree(output, activeGeneratedResourceTypes(loaded));
      } finally {
        await rm(directory, { recursive: true, force: true });
        await rm(output, { recursive: true, force: true });
      }
    });
  }
});

test("all existing committed HCL goldens match after Terraform formatting", async () => {
  const root = await committedRoot();
  const formatter = terraformHclFormatter();
  const fixtures = path.join(ROOT, "tests", "fixtures", "gen");
  let compared = 0;
  for (const resourceType of (await readdir(fixtures)).sort()) {
    const base = path.join(fixtures, resourceType);
    if (!(await stat(base)).isDirectory()) continue;
    const rendered = await renderModuleFiles(root, resourceType);
    for (const file of (await readdir(base)).filter((name) => name.endsWith(".tf")).sort()) {
      const actual = await formatter(rendered.files.get(file as "main.tf") ?? "");
      assert.equal(actual, await readFile(path.join(base, file), "utf8"), `${resourceType}/${file}`);
      compared += 1;
    }
  }
  assert.equal(compared, 68);
});

test("missing metadata and unsupported nesting modes fail loudly", async () => {
  const noPin = await syntheticRoot({ pin: null });
  const noSource = await syntheticRoot({ source: null });
  const unsupported = await syntheticRoot({
    schema: {
      block: {
        attributes: { name: { type: "string", required: true } },
        block_types: {
          settings: {
            nesting_mode: "group",
            block: { attributes: { on: { type: "bool", optional: true } } },
          },
        },
      },
    },
  });
  try {
    await assert.rejects(() => renderModuleFiles(noPin.root, "sample_resource"), /no version pin/);
    await assert.rejects(() => renderModuleFiles(noSource.root, "sample_resource"), /no source/);
    await assert.rejects(
      () => renderModuleFiles(unsupported.root, "sample_resource"),
      /unsupported nesting_mode "group"/,
    );
  } finally {
    await rm(noPin.directory, { recursive: true, force: true });
    await rm(noSource.directory, { recursive: true, force: true });
    await rm(unsupported.directory, { recursive: true, force: true });
  }
});

test("tree validation and Terraform formatter failures preserve concrete diagnostics", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "infrawright-output-"));
  try {
    await assert.rejects(
      () => validateGeneratedModuleTree(directory, ["sample_resource"]),
      /sample_resource\/main\.tf/,
    );
    await assert.rejects(
      () => terraformHclFormatter({ executable: path.join(directory, "missing-terraform") })("x\n"),
      /ENOENT|spawn/,
    );
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});
