# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed cloudflare_load_balancer resources, keyed as in var.items."
  value       = cloudflare_load_balancer.this
}

output "name_to_id" {
  description = "Map of resource name to provider-assigned id."
  value       = { for k, v in cloudflare_load_balancer.this : v.name => v.id }
}
