# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "cloudflare_load_balancer instances, keyed by a stable identifier."
  type = map(object({
    default_pools = list(string)
    fallback_pool = string
    name          = string
    zone_id       = string
    adaptive_routing = optional(object({
      failover_across_pools = optional(bool)
    }))
    country_pools = optional(map(list(string)))
    description   = optional(string)
    enabled       = optional(bool)
    location_strategy = optional(object({
      mode       = optional(string)
      prefer_ecs = optional(string)
    }))
    networks  = optional(list(string))
    pop_pools = optional(map(list(string)))
    proxied   = optional(bool)
    random_steering = optional(object({
      default_weight = optional(number)
      pool_weights   = optional(map(number))
    }))
    region_pools = optional(map(list(string)))
    rules = optional(list(object({
      condition = optional(string)
      disabled  = optional(bool)
      fixed_response = optional(object({
        content_type = optional(string)
        location     = optional(string)
        message_body = optional(string)
        status_code  = optional(number)
      }))
      name = optional(string)
      overrides = optional(object({
        adaptive_routing = optional(object({
          failover_across_pools = optional(bool)
        }))
        country_pools = optional(map(list(string)))
        default_pools = optional(list(string))
        fallback_pool = optional(string)
        location_strategy = optional(object({
          mode       = optional(string)
          prefer_ecs = optional(string)
        }))
        pop_pools = optional(map(list(string)))
        random_steering = optional(object({
          default_weight = optional(number)
          pool_weights   = optional(map(number))
        }))
        region_pools     = optional(map(list(string)))
        session_affinity = optional(string)
        session_affinity_attributes = optional(object({
          drain_duration         = optional(number)
          headers                = optional(list(string))
          require_all_headers    = optional(bool)
          samesite               = optional(string)
          secure                 = optional(string)
          zero_downtime_failover = optional(string)
        }))
        session_affinity_ttl = optional(number)
        steering_policy      = optional(string)
        ttl                  = optional(number)
      }))
      priority   = optional(number)
      terminates = optional(bool)
    })))
    session_affinity = optional(string)
    session_affinity_attributes = optional(object({
      drain_duration         = optional(number)
      headers                = optional(list(string))
      require_all_headers    = optional(bool)
      samesite               = optional(string)
      secure                 = optional(string)
      zero_downtime_failover = optional(string)
    }))
    session_affinity_ttl = optional(number)
    steering_policy      = optional(string)
    ttl                  = optional(number)
  }))
}
