import path from "node:path";

import {
  ZIA_PROVIDER_NAME,
  ZIA_PROVIDER_SOURCE,
  ZIA_PROVIDER_VERSION,
  ZIA_URL_CATEGORIES_RESOURCE_TYPE,
} from "../domain/zia-url-categories.js";
import { ProcessFailure } from "../domain/errors.js";
import {
  assertZiaUrlCategoriesWorkspace,
  prepareZiaUrlCategoriesWorkspace,
  writeZiaUrlCategoryPrivateFile,
} from "./zia-url-categories-workspace.js";

/** Opaque tenant label — same gate as PR-1 artifact paths. */
const TENANT = /^(?!\.{1,2}$)[A-Za-z0-9_.-]+$/;

const MODULE_SET = `zia-v${ZIA_PROVIDER_VERSION}`;

export interface ZiaUrlCategoriesModulePaths {
  readonly envMain: string;
  readonly moduleMain: string;
  readonly moduleOutputs: string;
  readonly moduleVariables: string;
  readonly moduleVersions: string;
}

function fail(code: string, message: string, category: "domain" | "io" = "domain"): never {
  throw new ProcessFailure({ code, category, message });
}

/**
 * Exact post-fmt module files for zia_url_categories, matching
 * engine.gen_module render_* + terraform fmt (1.15.4) for this resource only.
 * Comments retain the Python authority name for migration compatibility.
 */
function renderModuleMain(): string {
  return (
    `# GENERATED by engine.gen_module from packs/${ZIA_PROVIDER_NAME}/schemas/provider/${ZIA_PROVIDER_NAME}.json — do not edit.\n`
    + "# Regenerate: python -m engine.gen_module\n"
    + "\n"
    + `resource "${ZIA_URL_CATEGORIES_RESOURCE_TYPE}" "this" {\n`
    + "  for_each = var.items\n"
    + "\n"
    + "  configured_name                           = each.value.configured_name\n"
    + "  custom_category                           = each.value.custom_category\n"
    + "  custom_ip_ranges_count                    = each.value.custom_ip_ranges_count\n"
    + "  custom_urls_count                         = each.value.custom_urls_count\n"
    + "  db_categorized_urls                       = each.value.db_categorized_urls\n"
    + "  description                               = each.value.description\n"
    + "  editable                                  = each.value.editable\n"
    + "  ip_ranges                                 = each.value.ip_ranges\n"
    + "  ip_ranges_retaining_parent_category       = each.value.ip_ranges_retaining_parent_category\n"
    + "  ip_ranges_retaining_parent_category_count = each.value.ip_ranges_retaining_parent_category_count\n"
    + "  keywords                                  = each.value.keywords\n"
    + "  keywords_retaining_parent_category        = each.value.keywords_retaining_parent_category\n"
    + "  regex_patterns                            = each.value.regex_patterns\n"
    + "  regex_patterns_retaining_parent_category  = each.value.regex_patterns_retaining_parent_category\n"
    + "  super_category                            = each.value.super_category\n"
    + "  type                                      = each.value.type\n"
    + "  url_type                                  = each.value.url_type\n"
    + "  urls                                      = each.value.urls\n"
    + "  urls_retaining_parent_category_count      = each.value.urls_retaining_parent_category_count\n"
    + "\n"
    + '  dynamic "scopes" {\n'
    + "    for_each = each.value.scopes == null ? [] : each.value.scopes\n"
    + "    content {\n"
    + "      type = scopes.value.type\n"
    + "\n"
    + '      dynamic "scope_entities" {\n'
    + "        for_each = scopes.value.scope_entities == null ? [] : [scopes.value.scope_entities]\n"
    + "        content {\n"
    + "          id = scope_entities.value.id\n"
    + "        }\n"
    + "      }\n"
    + "\n"
    + '      dynamic "scope_group_member_entities" {\n'
    + "        for_each = scopes.value.scope_group_member_entities == null ? [] : [scopes.value.scope_group_member_entities]\n"
    + "        content {\n"
    + "          id = scope_group_member_entities.value.id\n"
    + "        }\n"
    + "      }\n"
    + "    }\n"
    + "  }\n"
    + "\n"
    + '  dynamic "url_keyword_counts" {\n'
    + "    for_each = each.value.url_keyword_counts == null ? [] : [each.value.url_keyword_counts]\n"
    + "    content {\n"
    + "      retain_parent_keyword_count = url_keyword_counts.value.retain_parent_keyword_count\n"
    + "      retain_parent_url_count     = url_keyword_counts.value.retain_parent_url_count\n"
    + "      total_keyword_count         = url_keyword_counts.value.total_keyword_count\n"
    + "      total_url_count             = url_keyword_counts.value.total_url_count\n"
    + "    }\n"
    + "  }\n"
    + "}\n"
  );
}

function renderModuleVariables(): string {
  return (
    `# GENERATED by engine.gen_module from packs/${ZIA_PROVIDER_NAME}/schemas/provider/${ZIA_PROVIDER_NAME}.json — do not edit.\n`
    + "# Regenerate: python -m engine.gen_module\n"
    + "\n"
    + 'variable "items" {\n'
    + `  description = "${ZIA_URL_CATEGORIES_RESOURCE_TYPE} instances, keyed by a stable identifier."\n`
    + "  type = map(object({\n"
    + "    configured_name                           = optional(string)\n"
    + "    custom_category                           = optional(bool)\n"
    + "    custom_ip_ranges_count                    = optional(number)\n"
    + "    custom_urls_count                         = optional(number)\n"
    + "    db_categorized_urls                       = optional(set(string))\n"
    + "    description                               = optional(string)\n"
    + "    editable                                  = optional(bool)\n"
    + "    ip_ranges                                 = optional(set(string))\n"
    + "    ip_ranges_retaining_parent_category       = optional(set(string))\n"
    + "    ip_ranges_retaining_parent_category_count = optional(number)\n"
    + "    keywords                                  = optional(set(string))\n"
    + "    keywords_retaining_parent_category        = optional(set(string))\n"
    + "    regex_patterns                            = optional(set(string))\n"
    + "    regex_patterns_retaining_parent_category  = optional(set(string))\n"
    + "    super_category                            = optional(string)\n"
    + "    type                                      = optional(string)\n"
    + "    url_type                                  = optional(string)\n"
    + "    urls                                      = optional(list(string))\n"
    + "    urls_retaining_parent_category_count      = optional(number)\n"
    + "    scopes = optional(set(object({\n"
    + "      type = optional(string)\n"
    + "      scope_entities = optional(object({\n"
    + "        id = optional(list(number))\n"
    + "      }))\n"
    + "      scope_group_member_entities = optional(object({\n"
    + "        id = optional(list(number))\n"
    + "      }))\n"
    + "    })))\n"
    + "    url_keyword_counts = optional(object({\n"
    + "      retain_parent_keyword_count = optional(number)\n"
    + "      retain_parent_url_count     = optional(number)\n"
    + "      total_keyword_count         = optional(number)\n"
    + "      total_url_count             = optional(number)\n"
    + "    }))\n"
    + "  }))\n"
    + "}\n"
  );
}

function renderModuleOutputs(): string {
  return (
    `# GENERATED by engine.gen_module from packs/${ZIA_PROVIDER_NAME}/schemas/provider/${ZIA_PROVIDER_NAME}.json — do not edit.\n`
    + "# Regenerate: python -m engine.gen_module\n"
    + "\n"
    + 'output "items" {\n'
    + `  description = "All managed ${ZIA_URL_CATEGORIES_RESOURCE_TYPE} resources, keyed as in var.items."\n`
    + `  value       = ${ZIA_URL_CATEGORIES_RESOURCE_TYPE}.this\n`
    + "}\n"
  );
}

function renderModuleVersions(): string {
  return (
    `# GENERATED by engine.gen_module from packs/${ZIA_PROVIDER_NAME}/schemas/provider/${ZIA_PROVIDER_NAME}.json — do not edit.\n`
    + "# Regenerate: python -m engine.gen_module\n"
    + "\n"
    + "terraform {\n"
    + "  required_providers {\n"
    + `    ${ZIA_PROVIDER_NAME} = {\n`
    + `      source  = "${ZIA_PROVIDER_SOURCE}"\n`
    + `      version = "${ZIA_PROVIDER_VERSION}"\n`
    + "    }\n"
    + "  }\n"
    + "}\n"
  );
}

/** Match engine.gen_env._module_source for a single-resource env root. */
function moduleSource(moduleDir: string, envDir: string): string {
  let moduleSrc = path.relative(
    envDir,
    path.join(moduleDir, ZIA_URL_CATEGORIES_RESOURCE_TYPE),
  );
  if (path.sep !== "/") {
    moduleSrc = moduleSrc.split(path.sep).join("/");
  }
  if (
    !moduleSrc.startsWith("../")
    && !moduleSrc.startsWith("./")
    && !moduleSrc.startsWith("/")
  ) {
    moduleSrc = `./${moduleSrc}`;
  }
  return moduleSrc;
}

/**
 * Exact post-fmt env root main.tf matching engine.gen_env.render_env_main
 * for label/member zia_url_categories with local state (no backend).
 */
function renderEnvMain(tenant: string, moduleSrc: string): string {
  // Python %r for a safe opaque tenant yields single-quoted form.
  const tenantRepr = `'${tenant}'`;
  return (
    `# GENERATED by engine.gen_env for tenant ${tenantRepr} — do not edit.\n`
    + `# Regenerate: make gen-env TENANT=${tenant}\n`
    + "\n"
    + "terraform {\n"
    + '  required_version = ">= 1.5"\n'
    + "  required_providers {\n"
    + `    ${ZIA_PROVIDER_NAME} = {\n`
    + `      source = "${ZIA_PROVIDER_SOURCE}"\n`
    + "    }\n"
    + "  }\n"
    + "  # local state — opt into remote state with\n"
    + `  # make gen-env TENANT=${tenant} BACKEND=azurerm\n`
    + "}\n"
    + "\n"
    + `provider "${ZIA_PROVIDER_NAME}" {\n`
    + "  # credentials via provider environment variables\n"
    + "}\n"
    + "\n"
    + 'variable "items" {\n'
    + "  # opaque at the root; the module enforces the strict type.\n"
    + "  type = any\n"
    + "}\n"
    + "\n"
    + `module "${ZIA_URL_CATEGORIES_RESOURCE_TYPE}" {\n`
    + `  source = "${moduleSrc}"\n`
    + "  items  = var.items\n"
    + "}\n"
  );
}

function modulePaths(workspace: string, tenant: string): ZiaUrlCategoriesModulePaths {
  const moduleDir = path.join(
    workspace,
    "modules",
    MODULE_SET,
    ZIA_URL_CATEGORIES_RESOURCE_TYPE,
  );
  const envDir = path.join(workspace, "envs", tenant, ZIA_URL_CATEGORIES_RESOURCE_TYPE);
  return Object.freeze({
    envMain: path.join(envDir, "main.tf"),
    moduleMain: path.join(moduleDir, "main.tf"),
    moduleOutputs: path.join(moduleDir, "outputs.tf"),
    moduleVariables: path.join(moduleDir, "variables.tf"),
    moduleVersions: path.join(moduleDir, "versions.tf"),
  });
}

/** Write the five Terraform runtime files for zia_url_categories into workspace. */
export async function writeZiaUrlCategoriesModule(options: {
  readonly tenant: string;
  readonly workspace: string;
}): Promise<ZiaUrlCategoriesModulePaths> {
  if (
    typeof options.workspace !== "string"
    || !path.isAbsolute(options.workspace)
    || options.workspace.includes("\0")
  ) {
    return fail(
      "INVALID_ZIA_MODULE_WORKSPACE",
      "ZIA module workspace must be an absolute directory",
    );
  }
  if (!TENANT.test(options.tenant)) {
    return fail(
      "INVALID_ZIA_MODULE_TENANT",
      "tenant must match [A-Za-z0-9_.-]+ and not be . or ..",
    );
  }
  const layout = await prepareZiaUrlCategoriesWorkspace(options);
  const workspace = layout.root;
  await assertZiaUrlCategoriesWorkspace(layout);
  const paths = modulePaths(workspace, options.tenant);
  const moduleSetDir = path.join(workspace, "modules", MODULE_SET);
  const envDir = path.dirname(paths.envMain);
  const moduleSrc = moduleSource(moduleSetDir, envDir);
  const contents = Object.freeze({
    envMain: renderEnvMain(options.tenant, moduleSrc),
    moduleMain: renderModuleMain(),
    moduleOutputs: renderModuleOutputs(),
    moduleVariables: renderModuleVariables(),
    moduleVersions: renderModuleVersions(),
  });
  await Promise.all([
    writeZiaUrlCategoryPrivateFile(paths.moduleMain, contents.moduleMain),
    writeZiaUrlCategoryPrivateFile(paths.moduleVariables, contents.moduleVariables),
    writeZiaUrlCategoryPrivateFile(paths.moduleOutputs, contents.moduleOutputs),
    writeZiaUrlCategoryPrivateFile(paths.moduleVersions, contents.moduleVersions),
    writeZiaUrlCategoryPrivateFile(paths.envMain, contents.envMain),
  ]);
  await assertZiaUrlCategoriesWorkspace(layout, Object.values(paths));
  return paths;
}
