# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

resource "cloudflare_load_balancer_pool" "this" {
  for_each = var.items

  account_id          = each.value.account_id
  name                = each.value.name
  origins             = each.value.origins
  check_regions       = each.value.check_regions
  description         = each.value.description
  enabled             = each.value.enabled
  latitude            = each.value.latitude
  load_shedding       = each.value.load_shedding
  longitude           = each.value.longitude
  minimum_origins     = each.value.minimum_origins
  monitor             = each.value.monitor
  notification_email  = each.value.notification_email
  notification_filter = each.value.notification_filter
  origin_steering     = each.value.origin_steering
}
