# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "cloudflare_load_balancer_pool instances, keyed by a stable identifier."
  type = map(object({
    account_id = string
    name       = string
    origins = list(object({
      address = optional(string)
      enabled = optional(bool)
      header = optional(object({
        host = optional(list(string))
      }))
      name               = optional(string)
      port               = optional(number)
      virtual_network_id = optional(string)
      weight             = optional(number)
    }))
    check_regions = optional(list(string))
    description   = optional(string)
    enabled       = optional(bool)
    latitude      = optional(number)
    load_shedding = optional(object({
      default_percent = optional(number)
      default_policy  = optional(string)
      session_percent = optional(number)
      session_policy  = optional(string)
    }))
    longitude          = optional(number)
    minimum_origins    = optional(number)
    monitor            = optional(string)
    notification_email = optional(string)
    notification_filter = optional(object({
      origin = optional(object({
        disable = optional(bool)
        healthy = optional(bool)
      }))
      pool = optional(object({
        disable = optional(bool)
        healthy = optional(bool)
      }))
    }))
    origin_steering = optional(object({
      policy = optional(string)
    }))
  }))
}
