//go:build ignore

// generate_publicsuffix ports the exact flat ICANN+private suffix trie used by
// the repository-pinned tldts release into a package-local Go data file.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const (
	sourcePath       = "../../../node_modules/tldts/src/data/trie.ts"
	algorithmPath    = "../../../node_modules/tldts/src/suffix-trie.ts"
	licensePath      = "../../../node_modules/tldts/LICENSE"
	localLicensePath = "TLDTS_LICENSE.txt"
	packagePath      = "../../../node_modules/tldts/package.json"
	outputPath       = "publicsuffix_data.go"
	wantSourceID     = "9581fb7dfc0b3a2ed7aa7cb8cc7aa551adaeb8c4e88fec647d9259594f03da4f"
	wantAlgorithmID  = "02e0e5484472977e725cae95916ff26b4a1ccb08ea8b05ca53145b4fb1531e5a"
	wantLicenseID    = "c64182d48160db948b6aa97a984f1a32974ce4d2053900361264cd33853796cb"
	wantOutputID     = "76f9385c2f5a6f725bf05f4fea2a95f864afe65a18b4badca10ba7e8647933b1"
	wantVersion      = "7.4.8"
	wantGitHead      = "e46ca7aa952df519efae2d11dcdb4f3a817ac8e5"
)

var (
	arrayDeclaration = regexp.MustCompile(`^export const (nodeFlags|edgeStart|edgeLength|edgeChild) = /\*#__PURE__\*/ new (Uint8Array|Uint16Array)\(\[(.*)\]\);$`)
	labelDeclaration = regexp.MustCompile(`^export const labelText = (.*);$`)
	rootDeclaration  = regexp.MustCompile(`^export const (rulesRoot|exceptionsRoot) = ([0-9]+);$`)
)

func fail(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", arguments...)
	os.Exit(1)
}

func readPinned(path, wantHash string) []byte {
	content, err := os.ReadFile(path)
	if err != nil {
		fail("read %s: %v", path, err)
	}
	gotHash := fmt.Sprintf("%x", sha256.Sum256(content))
	if gotHash != wantHash {
		fail("%s SHA-256 = %s, want %s", path, gotHash, wantHash)
	}
	return content
}

func goName(input string) string {
	switch input {
	case "nodeFlags":
		return "publicSuffixNodeFlags"
	case "edgeStart":
		return "publicSuffixEdgeStart"
	case "edgeLength":
		return "publicSuffixEdgeLength"
	case "edgeChild":
		return "publicSuffixEdgeChild"
	case "rulesRoot":
		return "publicSuffixRulesRoot"
	case "exceptionsRoot":
		return "publicSuffixExceptionsRoot"
	default:
		panic("unknown generated name: " + input)
	}
}

func emitArray(output *bytes.Buffer, match []string) {
	typeName := "uint8"
	if match[2] == "Uint16Array" {
		typeName = "uint16"
	}
	fmt.Fprintf(output, "var %s = [...]%s{\n", goName(match[1]), typeName)
	values := strings.Split(match[3], ",")
	for index, value := range values {
		if index%32 == 0 {
			output.WriteByte('\t')
		}
		output.WriteString(value)
		output.WriteByte(',')
		if index%32 == 31 || index == len(values)-1 {
			output.WriteByte('\n')
		}
	}
	output.WriteString("}\n\n")
}

func main() {
	check := flag.Bool("check", false, "check that the generated public suffix data is current without writing it")
	live := flag.Bool("live", false, "with --check, rederive the generated data from the pinned tldts sources")
	flag.Parse()
	if flag.NArg() != 0 || *live && !*check {
		fail("usage: go run generate_publicsuffix.go [--check [--live]]")
	}

	readPinned(localLicensePath, wantLicenseID)
	if *check && !*live {
		readPinned(outputPath, wantOutputID)
		return
	}

	source := readPinned(sourcePath, wantSourceID)
	readPinned(algorithmPath, wantAlgorithmID)
	readPinned(licensePath, wantLicenseID)
	packageJSON, err := os.ReadFile(packagePath)
	if err != nil {
		fail("read %s: %v", packagePath, err)
	}
	var identity struct {
		Version string `json:"version"`
		GitHead string `json:"gitHead"`
	}
	if err := json.Unmarshal(packageJSON, &identity); err != nil {
		fail("decode %s: %v", packagePath, err)
	}
	if identity.Version != wantVersion || identity.GitHead != wantGitHead {
		fail("%s identity = %s/%s, want %s/%s", packagePath, identity.Version, identity.GitHead, wantVersion, wantGitHead)
	}

	var output bytes.Buffer
	output.WriteString(`// Code generated by go generate; DO NOT EDIT.
//
// Source: tldts 7.4.8, gitHead e46ca7aa952df519efae2d11dcdb4f3a817ac8e5
// npm integrity: sha512-htwgN/8KRB3z3vnC0BOETVh2m499g5GmyTK9Wq5JBLX3FNz6tSBveAd+fQhzy9hkjif8vy2jwDMR1sGhLtZl2A==
// src/data/trie.ts SHA-256: 9581fb7dfc0b3a2ed7aa7cb8cc7aa551adaeb8c4e88fec647d9259594f03da4f
// src/suffix-trie.ts SHA-256: 02e0e5484472977e725cae95916ff26b4a1ccb08ea8b05ca53145b4fb1531e5a
// LICENSE SHA-256: c64182d48160db948b6aa97a984f1a32974ce4d2053900361264cd33853796cb
// License and copyright notice: TLDTS_LICENSE.txt.

package resthttp

`)

	found := make(map[string]bool)
	scanner := bufio.NewScanner(bytes.NewReader(source))
	scanner.Buffer(make([]byte, 1024), len(source)+1)
	for scanner.Scan() {
		line := scanner.Text()
		if match := arrayDeclaration.FindStringSubmatch(line); match != nil {
			emitArray(&output, match)
			found[match[1]] = true
			continue
		}
		if match := labelDeclaration.FindStringSubmatch(line); match != nil {
			label, unquoteErr := strconv.Unquote(match[1])
			if unquoteErr != nil {
				fail("decode labelText: %v", unquoteErr)
			}
			fmt.Fprintf(&output, "const publicSuffixLabelText = %s\n\n", strconv.Quote(label))
			found["labelText"] = true
			continue
		}
		if match := rootDeclaration.FindStringSubmatch(line); match != nil {
			fmt.Fprintf(&output, "const %s = %s\n\n", goName(match[1]), match[2])
			found[match[1]] = true
		}
	}
	if err := scanner.Err(); err != nil {
		fail("scan %s: %v", sourcePath, err)
	}
	for _, name := range []string{"nodeFlags", "edgeStart", "edgeLength", "edgeChild", "labelText", "rulesRoot", "exceptionsRoot"} {
		if !found[name] {
			fail("%s did not declare %s", sourcePath, name)
		}
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		fail("format generated Go: %v", err)
	}
	if *check {
		current, readErr := os.ReadFile(outputPath)
		if readErr != nil {
			fail("read %s: %v", outputPath, readErr)
		}
		if !bytes.Equal(current, formatted) {
			fail("%s is stale; run go generate .", outputPath)
		}
		return
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fail("write %s: %v", outputPath, err)
	}
}
