// Code generated by mechanically transcribing
// node-src/generated/python-lower-15.1.ts. DO NOT EDIT BY HAND.
//
// The upstream TS file (in this same repository) carries its own
// provenance header:
//
//	Generated by tools/generate-python-lower-151.mjs. DO NOT EDIT.
//	Inputs are pinned official Unicode files; see
//	docs/python-lower-unicode-contract.md.
//
// This file was produced by transcribing that committed generated
// artifact with a throwaway Node script (not checked into this repo);
// see docs/python-lower-unicode-contract.md for the pinned Unicode
// Character Database inputs and their SHA-256 digests, reproduced
// below for reference. Regenerating this file (if
// python-lower-15.1.ts ever changes) means re-running an equivalent
// mechanical transcription, not hand-editing.
//
// UCD 15.1.0:
//
//	DerivedCoreProperties.txt sha256:f55d0db69123431a7317868725b1fcbf1eab6b265d756d1bd7f0f6d9f9ee108b
//	  https://www.unicode.org/Public/15.1.0/ucd/DerivedCoreProperties.txt
//	SpecialCasing.txt sha256:55a477efd933a52cd27e6a9bf70265bb2d8814af31aab07767abc8eb421f27ef
//	  https://www.unicode.org/Public/15.1.0/ucd/SpecialCasing.txt
//	UnicodeData.txt sha256:2fc713e6a31a87c4850a37fe2caffa4218180fadb5de86b43a143ddb4581fb86
//	  https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt
//
// UCD 16.0.0:
//
//	DerivedCoreProperties.txt sha256:39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd
//	  https://www.unicode.org/Public/16.0.0/ucd/DerivedCoreProperties.txt
//	SpecialCasing.txt sha256:8d5de354eef79f2395a54c9c7dcebbaf3d30fc962d0f85611ea97aa973a0c451
//	  https://www.unicode.org/Public/16.0.0/ucd/SpecialCasing.txt
//	UnicodeData.txt sha256:ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f
//	  https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
//
// UCD 17.0.0:
//
//	DerivedCoreProperties.txt sha256:24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08
//	  https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt
//	SpecialCasing.txt sha256:efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588
//	  https://www.unicode.org/Public/17.0.0/ucd/SpecialCasing.txt
//	UnicodeData.txt sha256:2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c
//	  https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt
package pyunicode

// UCDSourceFile records the provenance of one pinned Unicode Character
// Database input file used to generate the runtime deltas below.
type UCDSourceFile struct {
	SHA256 string
	URL    string
}

// UCDSources mirrors PYTHON_LOWER_151_UCD_SOURCES from
// node-src/generated/python-lower-15.1.ts: the pinned Unicode Character
// Database files (and their verified SHA-256 digests) that the upstream
// Node generator consumed to produce the runtime deltas below. It is
// provenance metadata only; PythonLower151 does not read it at runtime.
var UCDSources = map[string]map[string]UCDSourceFile{
	"15.1.0": {
		"DerivedCoreProperties.txt": {SHA256: "f55d0db69123431a7317868725b1fcbf1eab6b265d756d1bd7f0f6d9f9ee108b", URL: "https://www.unicode.org/Public/15.1.0/ucd/DerivedCoreProperties.txt"},
		"SpecialCasing.txt":         {SHA256: "55a477efd933a52cd27e6a9bf70265bb2d8814af31aab07767abc8eb421f27ef", URL: "https://www.unicode.org/Public/15.1.0/ucd/SpecialCasing.txt"},
		"UnicodeData.txt":           {SHA256: "2fc713e6a31a87c4850a37fe2caffa4218180fadb5de86b43a143ddb4581fb86", URL: "https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt"},
	},
	"16.0.0": {
		"DerivedCoreProperties.txt": {SHA256: "39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd", URL: "https://www.unicode.org/Public/16.0.0/ucd/DerivedCoreProperties.txt"},
		"SpecialCasing.txt":         {SHA256: "8d5de354eef79f2395a54c9c7dcebbaf3d30fc962d0f85611ea97aa973a0c451", URL: "https://www.unicode.org/Public/16.0.0/ucd/SpecialCasing.txt"},
		"UnicodeData.txt":           {SHA256: "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f", URL: "https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt"},
	},
	"17.0.0": {
		"DerivedCoreProperties.txt": {SHA256: "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08", URL: "https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt"},
		"SpecialCasing.txt":         {SHA256: "efc25faf19de21b92c1194c111c932e03d2a5eaf18194e33f1156e96de4c9588", URL: "https://www.unicode.org/Public/17.0.0/ucd/SpecialCasing.txt"},
		"UnicodeData.txt":           {SHA256: "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c", URL: "https://www.unicode.org/Public/17.0.0/ucd/UnicodeData.txt"},
	},
}

// RuntimeDelta describes the reviewed, closed set of codepoint ranges
// where a specific newer Unicode runtime disagrees with the frozen Python
// str.lower() Unicode 15.1 contract this package targets. Every *Ranges
// field is a flattened [first, last, first, last, ...] pair list,
// transcribed verbatim from PYTHON_LOWER_151_RUNTIME_DELTAS in
// node-src/generated/python-lower-15.1.ts, consumed via binary search
// (see inRanges in lower.go).
type RuntimeDelta struct {
	RuntimeUCDVersion                  string
	RuntimeOnlyLowercaseSourceRanges   []rune
	PythonOnlyLowercaseSourceRanges    []rune
	ChangedCommonLowercaseSourceRanges []rune
	RuntimeOnlyCasedRanges             []rune
	PythonOnlyCasedRanges              []rune
	RuntimeOnlyCaseIgnorableRanges     []rune
	PythonOnlyCaseIgnorableRanges      []rune
}

// RuntimeDeltas mirrors PYTHON_LOWER_151_RUNTIME_DELTAS from
// node-src/generated/python-lower-15.1.ts, keyed by the same runtime
// Unicode major.minor version strings Node reports via
// process.versions.unicode ("16.0", "17.0"). Go's stdlib unicode
// package does not carry either version (see lower.go for how this
// package actually classifies codepoints); this table is transcribed in
// full so it is available, reviewed, and ready if that ever changes.
var RuntimeDeltas = map[string]RuntimeDelta{
	"16.0": {
		RuntimeUCDVersion: "16.0.0",
		RuntimeOnlyLowercaseSourceRanges: []rune{
			0x1c89, 0x1c89,
			0xa7cb, 0xa7cc,
			0xa7da, 0xa7da,
			0xa7dc, 0xa7dc,
			0x10d50, 0x10d65,
		},
		PythonOnlyLowercaseSourceRanges:    []rune{},
		ChangedCommonLowercaseSourceRanges: []rune{},
		RuntimeOnlyCasedRanges: []rune{
			0x1c89, 0x1c8a,
			0xa7cb, 0xa7cd,
			0xa7da, 0xa7dc,
			0x10d50, 0x10d65,
			0x10d70, 0x10d85,
		},
		PythonOnlyCasedRanges: []rune{},
		RuntimeOnlyCaseIgnorableRanges: []rune{
			0x897, 0x897,
			0x10d4e, 0x10d4e,
			0x10d69, 0x10d6d,
			0x10d6f, 0x10d6f,
			0x10efc, 0x10efc,
			0x113bb, 0x113c0,
			0x113ce, 0x113ce,
			0x113d0, 0x113d0,
			0x113d2, 0x113d2,
			0x113e1, 0x113e2,
			0x11f5a, 0x11f5a,
			0x1611e, 0x16129,
			0x1612d, 0x1612f,
			0x16d40, 0x16d42,
			0x16d6b, 0x16d6c,
			0x1e5ee, 0x1e5ef,
		},
		PythonOnlyCaseIgnorableRanges: []rune{
			0x1171e, 0x1171e,
		},
	},
	"17.0": {
		RuntimeUCDVersion: "17.0.0",
		RuntimeOnlyLowercaseSourceRanges: []rune{
			0x1c89, 0x1c89,
			0xa7cb, 0xa7cc,
			0xa7ce, 0xa7ce,
			0xa7d2, 0xa7d2,
			0xa7d4, 0xa7d4,
			0xa7da, 0xa7da,
			0xa7dc, 0xa7dc,
			0x10d50, 0x10d65,
			0x16ea0, 0x16eb8,
		},
		PythonOnlyLowercaseSourceRanges:    []rune{},
		ChangedCommonLowercaseSourceRanges: []rune{},
		RuntimeOnlyCasedRanges: []rune{
			0x1c89, 0x1c8a,
			0xa7cb, 0xa7cf,
			0xa7d2, 0xa7d2,
			0xa7d4, 0xa7d4,
			0xa7da, 0xa7dc,
			0xa7f1, 0xa7f1,
			0x10d50, 0x10d65,
			0x10d70, 0x10d85,
			0x16ea0, 0x16eb8,
			0x16ebb, 0x16ed3,
		},
		PythonOnlyCasedRanges: []rune{
			0x295, 0x295,
		},
		RuntimeOnlyCaseIgnorableRanges: []rune{
			0x897, 0x897,
			0x1acf, 0x1add,
			0x1ae0, 0x1aeb,
			0xa7f1, 0xa7f1,
			0x10d4e, 0x10d4e,
			0x10d69, 0x10d6d,
			0x10d6f, 0x10d6f,
			0x10ec5, 0x10ec5,
			0x10efa, 0x10efc,
			0x113bb, 0x113c0,
			0x113ce, 0x113ce,
			0x113d0, 0x113d0,
			0x113d2, 0x113d2,
			0x113e1, 0x113e2,
			0x11b60, 0x11b60,
			0x11b62, 0x11b64,
			0x11b66, 0x11b66,
			0x11dd9, 0x11dd9,
			0x11f5a, 0x11f5a,
			0x1611e, 0x16129,
			0x1612d, 0x1612f,
			0x16d40, 0x16d42,
			0x16d6b, 0x16d6c,
			0x16ff2, 0x16ff3,
			0x1e5ee, 0x1e5ef,
			0x1e6e3, 0x1e6e3,
			0x1e6e6, 0x1e6e6,
			0x1e6ee, 0x1e6ef,
			0x1e6f5, 0x1e6f5,
			0x1e6ff, 0x1e6ff,
		},
		PythonOnlyCaseIgnorableRanges: []rune{
			0x1171e, 0x1171e,
		},
	},
}
