# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

resource "cloudflare_dns_record" "this" {
  for_each = var.items

  name     = each.value.name
  ttl      = each.value.ttl
  type     = each.value.type
  zone_id  = each.value.zone_id
  comment  = each.value.comment
  content  = each.value.content
  data     = each.value.data
  priority = each.value.priority
  proxied  = each.value.proxied
  settings = each.value.settings
  tags     = each.value.tags
}
