# GENERATED by engine.gen_env for tenant 'tenant' — do not edit.
# Regenerate: make gen-env TENANT=tenant

terraform {
  required_version = ">= 1.5"
  required_providers {
    sample = {
      source = "example/sample"
    }
  }
  # local state — opt into remote state with
  # make gen-env TENANT=tenant BACKEND=azurerm
}

provider "sample" {
  # credentials via provider environment variables
}

variable "items" {
  # opaque at the root; the module enforces the strict type.
  type = any
}

module "sample_resource" {
  source = "../../../modules/sample_resource"
  items  = var.items
}
