# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

resource "cloudflare_list_item" "this" {
  for_each = var.items

  account_id = each.value.account_id
  list_id    = each.value.list_id
  asn        = each.value.asn
  comment    = each.value.comment
  hostname   = each.value.hostname
  ip         = each.value.ip
  redirect   = each.value.redirect
}
