# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

output "items" {
  description = "All managed cloudflare_list_item resources, keyed as in var.items."
  value       = cloudflare_list_item.this
}
