# GENERATED by tools/gen_module.py from schemas/provider/cloudflare.json — do not edit.
# Regenerate: make generate

variable "items" {
  description = "cloudflare_list_item instances, keyed by a stable identifier."
  type = map(object({
    account_id = string
    list_id    = string
    asn        = optional(number)
    comment    = optional(string)
    hostname = optional(object({
      url_hostname = optional(string)
    }))
    ip = optional(string)
    redirect = optional(object({
      include_subdomains    = optional(bool)
      preserve_path_suffix  = optional(bool)
      preserve_query_string = optional(bool)
      source_url            = optional(string)
      status_code           = optional(number)
      subpath_matching      = optional(bool)
      target_url            = optional(string)
    }))
  }))
}
